<?php if($this->about_home):?>
	<h1 class="title-right"><span><?php echo $this->about_home['title'.LANG] ?></span></h1>
	<div class="rows-first">
		<?php echo html_entity_decode($this->about_home['content'.LANG]) ?>
	</div>
<?php endif;?>

<?php if(isset($this->list_adv_bottom) && sizeof($this->list_adv_bottom) > 0):?>
	<h1 class="title-right"><span><?php echo $this->lang['partner']?></span></h1>
  	<div class="rows-two">
  		<div class="slaids">
    		<div class="slaids_left">
      			<div class="slaids_right">
        			<span class="prev left_bat"></span>
                	<span class="next right_bat"></span>
                	<div class="gallery">
                		<ul>
                			<?php foreach ($this->list_adv_bottom as  $value):?>
                  				<li class="li_img">
                    				<div class="im">
                      					<a href="<?php echo $value['url']?>" target="<?php echo $value['type']?>" title="<?php echo $value['title'.LANG].' - '.$value['description']?>">
                     						<img src="<?php echo $this->baseUrl() ?>/public/userfiles/images/adv/<?php echo $value['pic_thumb']?>" alt="<?php echo $value['title'.LANG].' - '.$value['description']?>"/>
                     					</a>				
                      				</div>		  
                     			</li>  
                     		<?php endforeach;?>
                		</ul>
             		</div>
               </div>
            </div> 
		</div><!--End slaids Gallery-->
	</div><!--End rows tow--> 
<?php endif;?>