<div class="content">
	<script type="text/javascript">
	$(document).ready(function(){
	    $("#add-rows").click(function(){
	        $(".rows").before('<p><label>Support</label><input name="fullname[]" value="" maxlength="45" class="txt-large" /> <input name="support_phone[]" value="" maxlength="45" class="txt-small" /> <input name="support_value[]" value="" maxlength="45" class="txt-small" /> <input name="support_part[]" value="" maxlength="1" class="txt-very-tiny" /> <input name="order[]" value="" maxlength="1" class="txt-very-tiny" /> <input name="type[]" value="" maxlength="45" class="txt-small" /></p>');
	    });
	});
	</script>
	<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
	<fieldset>
		<legend><?php echo $this->lang['support'] ?></legend>
		<p class="rows"><a href="#" id="add-rows"><?php echo $this->lang['sys_addrow']?></a></p>
		<p>
			<label></label>
			<label class="label-txt-large">Name</label>
			<label class="label-txt-small">Phone</label>
			<label class="label-txt-small">Value</label>
			<label class="label-txt-very-tiny">Part</label>
			<label class="label-txt-very-tiny">Sort</label>
			<label class="label-txt-small">Type</label>
		</p>
		<?php foreach($this->items as $value):	?>
			<p class="clear">
				<label>Support</label>
				<input name="fullname[]" value="<?php echo $value['support_name'] ?>" maxlength="45" class="txt-large" />
				<input name="support_phone[]" value="<?php echo $value['support_phone'] ?>" maxlength="45" class="txt-small" />
				<input name="support_value[]" value="<?php echo $value['support_value'] ?>" maxlength="45" class="txt-small" />
				<input name="support_part[]" value="<?php echo $value['support_part'] ?>" maxlength="1" class="txt-very-tiny" />
				<input name="order[]" value="<?php echo $value['support_order'] ?>" maxlength="1" class="txt-very-tiny" />
				<input name="type[]" value="<?php echo $value['support_type'] ?>" maxlength="45" class="txt-small" />
			</p>
		<?php endforeach; ?>
		
		<p>
			<label>&nbsp;</label>
			<input type="submit" name="btnregister" value="  <?php echo $this->lang['sys_edit'] ?>  " class="login" /> <a href="javascript:history.back()" class="login-a"><?php echo $this->lang['sys_cancel'] ?></a>
		</p>
	</fieldset>
	</form>
</div>