<h1 class="title-pr"><?php echo $this->lang['product']?> &raquo; <?php echo $this->infocat['cat_title'.LANG] ?></h1>
<?php if (is_array($this->listsubcat)): ?>
	<?php foreach ($this->listsubcat as $value): ?>
		<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/product_cat/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg';?>
		<div class="new-pr">
			<div class="left-new-pr"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/cat/cid/<?php echo $value['cat_id'] ?>" title="<?php echo $value['cat_title'.LANG] ?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" alt="<?php echo $value['cat_title'.LANG] ?>" /></a></div>
			<div class="right-new-pr">
				<ul>
					<li><h1 class="title-h1-product"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/cat/cid/<?php echo $value['cat_id'] ?>" title="<?php echo $value['cat_title'.LANG] ?>"><strong><?php echo $value['cat_title'.LANG]?></strong></strong></a></h1>
						<!-- <p><span>Manufacture:</span> Example -1</p> -->
					</li>
					<li><?php echo $value['preview'.LANG] ?></li>
					<li><p class="all-pr" ><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/cat/cid/<?php echo $value['cat_id'] ?>" title="<?php echo $value['cat_title'.LANG] ?>">Chi tiết</a></p></li>
				</ul>
			</div>
		</div>
	<?php endforeach;?>
<?php else:?>
	<div id="allproduct">
		<?php if (is_array($this->productcat)): ?>
			<?php foreach ($this->productcat as $value): ?>
				<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/product/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg';?>
				<div class="bg-product">
					<div class="bd-top-pr"></div>
					<div class="product">
						<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" alt="<?php echo $value['title'.LANG] ?>" /></a>
						<h3 class="title-h3-pr"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h3>
						<?php echo html_entity_decode($value['preview'.LANG]) ?>
						<!-- <p><s>$35.99</s></p> -->
						<div class="all-buy">
							<div class="all-pr"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/order/id/<?php echo $value['record_id'] ?>" title="Mua hàng <?php echo $value['title'.LANG] ?>">Mua hàng</a></div>
							<div class="spe-price">
								<div class="spe-left-price"></div>
								<div class="spe-right-price"><span><?php echo $value['unit'] ?></span></div>
							</div>
						</div>
					</div>
					<div class="bd-btom-pr"></div>
				</div>
			<?php endforeach;?>
			<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');?>
		<?php else: ?>
			<?php echo $this->productcat ?>
		<?php endif;?>
	</div><!--End All product-->
<?php endif;?>