<h1 class="title-box"><span><?php echo $this->lang[$this->module] ?></span></h1>
<div class="frame-tent-right">
    <?php if (is_array($this->listcat)): ?>
        <div class="all-product">
            <?php foreach ($this->listcat as $value): ?>
                <?php
                    $picthumb = ($value['pic_thumb'] != '') ? '/public/userfiles/images/' . $this->module . '/' . $value['pic_thumb'] : TEMPLATE . '/images/no-images.jpg';
                    $url = (LANGURL != '') ? '/' . LANGURL . '/' . $this->module : '/' . $this->module;
                ?>
            <div class="product" style="float: left">
                    <div class="tent-product">
                        <div class="product-img">
                            <a href="<?php echo $this->baseUrl() . $url ?>/index/cat/id/<?php echo $value['cat_id'] ?>" title="<?php echo $value['cat_title' . LANG] ?>">
                                <img src="<?php echo $this->baseUrl() . $picthumb ?>" alt="<?php echo $value['cat_title' . LANG] ?>" />
                            </a>
                        </div><div class="clear"></div>

                        <h2 class="title-pro">
                            <a href="<?php echo $this->baseUrl() . $url ?>/index/cat/id/<?php echo $value['cat_id'] ?>" title="<?php echo $value['cat_title' . LANG] ?>">
                                <strong><?php echo $value['cat_title' . LANG] ?></strong>
                            </a>
                        </h2>
                        <p class="bton-pro">
                            <a class="bton-detail" href="<?php echo $this->baseUrl().$url ?>/index/cat/id/<?php echo $value['cat_id'] ?>" title="<?php echo $value['cat_title' . LANG] ?>">
                                Chi tiết
                            </a> 
                            <a href="order.html" title="ĐẶT HÀNG" class="bton-order">
                                ĐẶT HÀNG
                            </a> 
                        </p>
                    </div>
                </div>

            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <?php echo $this->listcat ?>
    <?php endif; ?>
</div>

<?php
if (DEBUG_MODE)
    var_dump($this->listcat);?>