<h1 class="title-right"><?php echo $this->lang['video']?> &raquo; <?php echo $this->infocat['cat_title'.LANG]?></h1> 
<div class="frame-video">
	<?php if(is_array($this->items)): ?>
		<?php foreach ($this->items as $value):
			$pic = ($value['pic_full']) ? $this->baseUrl().'/public/userfiles/images/video/'.$value['pic_full'] : $this->baseUrl().TEMPLATE.'/images/no-images.jpg';
		?>
		
		<div class="video-photo">
	    	<div class="video-photo-img">
	    		<a href="<?php echo $value['url']?>" rel="prettyPhoto" title="<?php echo $value['title'.LANG]?>">
	    			<img src="<?php echo $pic?>" alt="<?php echo $value['title'.LANG]?>"  />
	    		</a>
	    	</div>
			<h2 class="title-video">
				<a href="<?php echo $value['url']?>" rel="prettyPhoto" title="<?php echo $value['title'.LANG]?>">
					<?php echo $value['title'.LANG]?>
				</a>
			</h2>
		</div>
		<?php endforeach;?>
		 <div class="clear"></div>
	<?php	
	//	echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
	?>
	<?php else: ?>
		<p><?php echo $this->items; ?></p>
	<?php endif;?>

                      
</div><!--End frame video-->
<script type="text/javascript" charset="utf-8"> 
                      $(document).ready(function(){
                        $(".video-photo a[rel^='prettyPhoto']").prettyPhoto();
                      });
                    </script> 