<div id="content" class="c_villa">
	<div id="c_top">
	   <div id="box_left_villa" >
			<?php if(isset($this->menu_about)): ?>
				<div id="category_villa">
					<h3><?php echo $this->lang['about'] ?></h3>
					<ul>
						<?php 
							foreach($this->menu_about as $value){
								echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'about'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
							}
						?>
					</ul>
				</div>
			<?php endif; ?>
			
			<?php if(isset($this->menu_services)): ?>
				<div id="category_villa">
					<h3><?php echo $this->lang['services'] ?></h3>
					<ul>
						<?php 
							foreach($this->menu_services as $value){
								echo '<li><a href="'.$this->baseUrl().'/'.LANGURL. 'services'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
							}
						?>
					</ul>
				</div>
			<?php endif; ?>
          
		   <div class="line_space_villa"></div>
		   <div id="box_left_mod_2">   
			   <h3>Hỗ TRỢ TRỰC TUYẾN</h3>
			   <center>
				   <img src="images/ym_contact.png" alt="contact1" /><br />
				   <img src="images/ym_contact.png" alt="contact1" />
				</center>
		   </div>
	   </div>
	   
	   <div id="content_villa">
			<?php 
				echo '<h1 class="about">'.$this->escape($this->list['title'.LANG]).'</h1>';
				echo $this->xss($this->list['content'.LANG]);
			?>
	   </div>
	</div>
</div>