<p style="color: #0000ff;padding-top:10px"><strong>Hệ thống đã ghi nhận bình chọn của bạn.</strong></p>
<h3>Bạn biết gì về NukeViet 3?</h3>
<dl class="graph">
    <dt class="bar-title">Một bộ sourcecode cho web hoàn toàn mới.</dt>
    <dd class="bar-container">
        <div style="width: 0%;display: block;" id="bar1">&nbsp;</div>
        <strong>0%</strong>
    </dd>
    <dt class="bar-title">Mã nguồn mở, sử dụng miễn phí.</dt>
    <dd class="bar-container">
        <div style="width: 50%;display: block;background-color: rgb(0, 102, 204);" id="bar2">&nbsp;</div>
        <strong>5%</strong>
    </dd>
    <dt class="bar-title">Sử dụng xHTML, CSS và hỗ trợ Ajax</dt>
    <dd class="bar-container">
        <div style="width: 50%;display: block;" id="bar3">&nbsp;</div>
        <strong>50%</strong>
    </dd>
    <dt class="bar-title">Tất cả các ý kiến trên</dt>
    <dd class="bar-container">
        <div style="width: 59%;display: block;" id="bar4">&nbsp;</div>
        <strong>59%</strong>
    </dd>
</dl>
<p style="padding-top:10px">
    <strong>Tổng số</strong>: 2 lượt - <strong>Tính từ:</strong>
    Thứ hai - 31/05/2010  11:09
</p>