<div class="content">
	<?php if(count($this->error) > 0): ?>
		<ul class="error-li">
			<?php 
			foreach ($this->error as $value){
				echo '<li>'.$value.'</li>';
			}
			?>
		</ul>
	<?php endif; ?>
	<script type="text/javascript">
	$(document).ready(function(){
	    $("#add-rows").click(function(){
	        $(".rows").before('<p><label>Config</label><input name="config_namenew[]" value="" maxlength="45" class="txt-large" /> <input name="config_valuenew[]" value="" maxlength="45" class="txt-large" /> <input name="config_choicesnew[]" value="" maxlength="45" class="txt-large" /></p>');
	        return false;
	    });
	});
	</script>
	<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
	<fieldset>
		<legend>Cấu hình hệ thống</legend>
		<p class="rows"><a href="#" id="add-rows">Thêm dòng</a></p>
	    <?php
	        foreach($this->items as $item){
	        	echo '<p><label>Config</label>
	                    <input name="config_name[]" value="'.$item['config_name'].'" maxlength="45" class="txt-large" />
	                    <input name="config_value[]" value="'.$item['config_value'].'" maxlength="45" class="txt-large" />
	                    <input name="config_choices[]" value="'.$item['config_choices'].'" maxlength="45" class="txt-large" />';
	        }
		?>
		<p>
			<label>&nbsp;</label>
			<input type="submit" name="submit" value="  Chỉnh sửa  " class="login" /> <a href="/" class="login-a">Hủy bỏ</a>
		</p>
	</fieldset>
	</form>
</div>