<div class="content">
    <?php if (isset($this->item)): ?>
        <fieldset>
            <legend>Sửa bình luận</legend>
            <form id="contact" method="post" name="dangky" action="">
                <div class="col1">Tiêu đề</div>
                <div class="col2">
                    <input name="cmt_title" id="cmt_title" maxlength="45"  class="txt-very-large"  value="<?php echo $this->item['cmt_title'] ?>" />
                </div>
                <div class="clear space"></div>
                <div class="col1">Nội dung</div>
                <div class="col2">
                    <textarea name="cmt_content" id="cmt_content" rows="10" cols="80"><?php echo $this->item['cmt_content'] ?></textarea>
                </div>
                <div class="clear space"></div>
                <div class="col1">&nbsp;</div>
                <div class="col2">
                    <input type="submit" value="Sửa"  class="login" />
                </div>
                <div class="clear space"></div>
            </form>		
        </fieldset>

    <?php else: ?>
        <form name="frm" id="frm" action="" method="post">
            <input type="hidden" name="factive" value="" />
            <table>
                <thead>
                    <tr>
                        <th class="txt15"><input onclick="javascript: select_switch(this.checked);" type="checkbox" name="checkall" /></th>
                        <th><?php echo $this->lang['sys_title_cmt'] ?></th>
                        <th><?php echo $this->lang['sys_content_cmt'] ?></th>
                        <th><?php echo $this->lang['entry'] ?></th>
                        <th><?php echo $this->lang['user_cmt'] ?></th>
                        <th>Email</th>
                        <th><?php echo $this->lang['time'] ?></th>
                        <th><?php echo $this->lang['action'] ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ($this->items != '') {
                        $k = 1;
                        foreach ($this->items as $value) {
                            if ($value['cmt_enable'] == 0) {
                                $rowclass = ' class="disable"';
                            } else {
                                $rowclass = ($k % 2 == 0) ? '' : ' class="alt"';
                            }
                            $title = $this->escape($value['cmt_title' . LANG]);

                            echo '<tr' . $rowclass . '>
		               <td><input type="checkbox" name="ids[]" value="' . $value['cmt_id'] . '" /></td>
		               <td  class="tdcommment"><a rel="prettyPhoto[iframes]"  href="' . $this->baseUrl().'/'.$this->controller . '/index/view/id/' . $value['dos_module_item_record_id'] . '#cmt' . $value['cmt_id'] . '?iframe=true&width=100%&height=100%">' . $title . '</a></td>
		               <td>' . $value['cmt_content'] . '</td>
		               <td>' . $value['dos_module_item_record_name'] . '</td>
		               <td>' . $value['cmt_name'] . '</td>
                                    <td>' . $value['cmt_email'] . '</td>
		               <td>' . date('H:i d-m-Y',$value['cmt_date']). '</td>
		               <td><a href="' . $this->baseUrl() . $this->currentController . '/comment/id/' . $value['cmt_id'] . '" title="' . $this->lang['sys_edit'] . '">' . $this->lang['sys_edit'] . '</a></td>
		            </tr>';
                            $k++;
                        }
                    } else {
                        echo '<tr><td colspan="6">' . $this->lang['norecord'] . '</td></tr>';
                    }
                    ?>
                </tbody>
            </table>

            <div class="control-button">
                <img src="<?php echo $this->baseUrl() . TEMPLATE_ADMIN ?>/images/visible.png" alt="<?php echo $this->lang['sys_active'] ?>" align="left" /> 
                <a href="javascript:submit_list('enable', '');" title="<?php echo $this->lang['sys_active'] ?>">
                    <?php echo $this->lang['sys_active'] ?>
                </a>
            </div>
            <div class="control-button">
                <img src="<?php echo $this->baseUrl() . TEMPLATE_ADMIN ?>/images/hidden.png" alt="<?php echo $this->lang['sys_hidden'] ?>" align="left" /> 
                <a href="javascript:submit_list('disable', '');" title="<?php echo $this->lang['sys_hidden'] ?>">
                    <?php echo $this->lang['sys_hidden'] ?>
                </a>
            </div>
            <div class="control-button">
                <img src="<?php echo $this->baseUrl() . TEMPLATE_ADMIN ?>/images/delete.png" alt="<?php echo $this->lang['sys_delete'] ?>" align="left" /> 
                <a href="javascript:delete_list('');" title="<?php echo $this->lang['sys_delete'] ?>">
                    <?php echo $this->lang['sys_delete'] ?></a>
            </div>
            <script type="text/javascript" src="<?php echo $this->baseUrl() . TEMPLATE_ADMIN ?>/js/common.js"></script>
        </form>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    <?php endif; ?>
</div>


<script type="text/javascript" charset="utf-8"> 
    $(document).ready(function(){
        $(".tdcommment a[rel^='prettyPhoto[iframes]']").prettyPhoto();
    });
</script>