<h1 class="title-right"><?php echo $this->lang['news']?> &raquo; <?php echo $this->detailcat['cat_title'.LANG] ?></h1>

	
	<?php if(is_array($this->items)):?>
	 <?php foreach ($this->items as $value):?>
		<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/news/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg'; ?>
	 		<div class="masuring">
				<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>news/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>">
					<img src="<?php echo $this->baseUrl().$picthumb ?>" class="imgcon" style="float:left; alt="<?php echo $value['title'.LANG] ?>" /></a>
                   
                <h2 class="title-masuring"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>news/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h2>
     			<?php echo html_entity_decode($value['preview'.LANG]) ?>
     		</div><div class="clear"></div>
		<?php endforeach;?>
		<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
	<?php else: ?>
		<?php echo $this->items?>
	<?php endif;?>
	