<h1 class="title-right"><span><?php echo $this->item['title'.LANG] ?></span></h1>
<div class="rows-first">
	<?php echo html_entity_decode($this->item['content'.LANG]); ?>
	<form id="contact" method="post" action="" name="frm" onsubmit="return validatecheck();">
		<ul class="frame-contact">
	    	<li class="left"><p>Name: <span>*</span></p><input type="text" name="fullname" value="" /></li>
	        <li><p>Email: <span>*</span></p><input type="text" name="email" value="" /></li>
	        <li><p>Telephone: <span>*</span></p><input type="text" name="phone" value="" /></li>
	        <li><p>Content: <span>*</span></p><textarea name="content" rows="10" cols="" ></textarea></li>						
		</ul>                  
	    <p class="input-contact"><input type="submit" class="singin" title="Submit"  value="Submit"/>  <input type="reset" class="singin" value="Reset"/></p>
	</form>
	<script type="text/javascript" src="<?php echo $this->baseUrl().TEMPLATE ?>/js/contact.js"></script>
</div><!--End rows first-->