<div class="content">
	<?php if(count($this->error) > 0): ?>
		<ul class="error-li">
			<?php 
			foreach ($this->error as $value){
				echo '<li>'.$value.'</li>';
			}
			?>
		</ul>
	<?php endif; ?>
	
	<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
	<fieldset>
		<legend><?php echo $this->lang['sys_editpost'] ?></legend>
		<div class="col1"><?php echo $this->lang['catparent'] ?></div>
	    <div class="col2">
	        <select name="parentcat" id="parentcat">
	        <?php 
	        	foreach ($this->cat as $value){
	        		echo '<option value="'.$value['cat_id'].'">'.$value['title_prefix'].$value['cat_title'.LANG].'</option>';
	        	}
	        ?>
	        </select>
	    </div>
	    <div class="clear space"></div>
		
	    <?php
	        $lang = $this->langlist();
	        foreach($lang as $value){
	            echo '<div class="col1">'.$this->lang['sys_title'].' '.$value.'</div>
	                <div class="col2">
	                    <input name="title'.$value.'" value="'.$this->item['title'.$value].'" maxlength="100" class="txt-very-large" />
	                </div>
	                <div class="clear space"></div>';
	        }
	    ?>
	    
	    <div class="col1"><?php echo $this->lang['picture_thumb'] ?></div>
	    <div class="col2">
	    	<?php if($this->item['pic_thumb'] != null): ?>
	    		<input type="hidden" name="fileold_thumb" value="<?php echo $this->item['pic_thumb'] ?>" />
	    		<div class="border-img"><img src="<?php echo $this->baseUrl().'/public/userfiles/images/'.$this->controller.'/'.$this->item['pic_thumb'] ?>" alt="" /></div>
	    	<?php endif; ?>
	        <input type="file" name="file_thumb" size="48%" />
	    </div>
	    <div class="clear space"></div>
	    
	    <div class="col1"><?php echo $this->lang['sys_picture'] ?></div>
	    <div class="col2">
	        <input type="file" name="file_full" size="48%" />
	        <?php if($this->item['pic_full'] != null): ?>
	        	<input type="hidden" name="fileold_full" value="<?php echo $this->item['pic_full'] ?>" />
	        	<a href="<?php echo $this->baseUrl().'/public/userfiles/images/'.$this->controller.'/'.$this->item['pic_full'] ?>" class="nyroModal" title="<?php echo $this->item['title'.LANG] ?>"><strong>xem ảnh lớn</strong></a>
	    	<?php endif; ?>
	    </div>
	    <div class="clear space"></div>
	
	    <div class="col1"><?php echo $this->lang['sys_active'] ?></div>
	    <div class="col2 radio">
	        <input type="radio" checked="checked" name="active" id="active" value="1" /> <label for="active"><?php echo $this->lang['sys_active'] ?></label> &nbsp;&nbsp; <input type="radio"  name="active" id="deactive" value="0" /> <label for="deactive"><?php echo $this->lang['sys_hidden'] ?></label>
	    </div>
	    <div class="clear space"></div>
	    
	    <div class="col1">&nbsp;</div>
	    <div class="col2">
	        <input type="submit" name="submit" value="  <?php echo $this->lang['sys_edit'] ?>  " class="login" /> <a href="javascript:history.back()" class="login-a"><?php echo $this->lang['sys_cancel'] ?></a>
	    </div>
	    <div class="clear space"></div>
	</fieldset>
	</form>
	<script type="text/javascript">
		var the_form = window.document.frm;
		radio_list("<?php echo $this->item['enable'] ?>", the_form.active);
		select_list("<?php echo $this->item['dos_module_gallery_cat_cat_id'] ?>", the_form.parentcat);
	</script>
	<script type="text/javascript">
		$(function() {
		  $('.nyroModal').nyroModal();
		});
	</script>
</div>