<div class="content">
	<?php if(count($this->error) > 0): ?>
		<ul class="error-li">
			<?php 
			foreach ($this->error as $value){
				echo '<li>'.$value.'</li>';
			}
			?>
		</ul>
	<?php endif; ?>
	<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
	<fieldset>
		<legend>Thêm tài khoản quản lý</legend>
		<p>
			<label for="username">Username <span class="error">*</span></label>
			<input type="text" name="username" id="username" value="<?php echo $this->item['username']?>" maxlength="45" class="txt-large" />
		</p>
		<p>
			<label for="password">Mật khẩu <span class="error">*</span></label>
			<input type="password" name="password" id="password" value="<?php echo $this->item['password']?>" maxlength="45" class="txt-large" />
		</p>
		<p>
			<label for="email">Email <span class="error">*</span></label>
			<input type="text" name="email" id="email" value="<?php echo $this->item['email']?>" maxlength="45" class="txt-large" />
		</p>
		<p>
			<label for="full_name">Fullname <span class="error">*</span></label>
			<input type="text" name="full_name" id="full_name" value="<?php echo $this->item['full_name']?>" maxlength="150" class="txt-large" />
		</p>
		<p>
			<label for="active">Enable <span class="error">*</span></label>
			<select name="active" id="active" style="width: 198px">
				<option value="1"><?php echo $this->lang['sys_active'] ?></option>
				<option value="0"><?php echo $this->lang['sys_hidden'] ?></option>
			</select>
	    </p>
		<p>
			<label>&nbsp;</label>
			<input type="submit" name="submit" value="  <?php echo $this->lang['sys_add'] ?>  " class="login" /> <a href="javascript:history.back()" class="login-a" title="<?php echo $this->lang['sys_cancel'] ?>"><?php echo $this->lang['sys_cancel'] ?></a>
		</p>
	</fieldset>
	</form>
</div>