<h2><?php echo $this->lang['gallery']?></h2>
<div id="listfood2">
	<ul>
		<?php foreach ($this->list_gallery_cat as $value):
			$pic = ($value['pic_thumb']) ? $this->baseUrl().'/public/userfiles/images/gallery_cat/'.$value['pic_thumb'] : $this->baseUrl().TEMPLATE.'/images/no-gallery-thumb.jpg';
		?>
		<li>
			<a href="<?php echo $this->baseUrl().'/'.LANGURL.'gallery'.'/index/cat/id/'.$value['cat_id'].'/'.$this->noneUnicode($value['cat_title'.LANG]).'" title="'.$this->escape($value['cat_title'.LANG]) ?>"><img src="<?php echo $pic?>" alt="<?php echo $value['cat_title'.LANG]?>" /></a>
			<h6><?php echo $value['cat_title'.LANG]?></h6>
		</li>
		<?php endforeach;?>
	</ul>
</div>