<h1 class="title-right"><span><?php echo $this->lang['solution']?> &raquo; <?php echo $this->detailcat['cat_title'.LANG] ?></span></h1>

				<?php if(is_array($this->items)):?>
						<?php foreach ($this->items as $value): ?>
						<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/solution/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg'; ?>
						<div class="masuring">
		                	<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>solution/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" class="imgcon" style="float:left;" alt="<?php echo $value['title'.LANG] ?>" /></a>
		                    <h3><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>solution/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h3>
		                    <?php echo html_entity_decode($value['preview'.LANG]) ?>
		                </div><div class="clear"></div>
						<?php endforeach; ?>
					<?php else:?>
						<?php echo $this->items; ?>
				<?php endif;?>
				
				<?php if(is_array($this->list_solution_new)):?>
					<?php foreach ($this->list_solution_new as $value):?>
						<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/solution/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg'; ?>
						<div class="masuring">
		                	<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>solution/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" class="imgcon" style="float:left;" alt="<?php echo $value['title'.LANG] ?>" /></a>
		                    <h3><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>solution/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h3>
		                    <?php echo html_entity_decode($value['preview'.LANG]) ?>
		                </div><div class="clear"></div>
					<?php endforeach;?>
				<?php else: ?>
					<?php echo $this->list_solution_new?>
				<?php endif;?>
                <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
		