<div class="content">
	<?php if(count($this->error) > 0): ?>
		<ul class="error-li">
			<?php 
			foreach ($this->error as $value){
				echo '<li>'.$value.'</li>';
			}
			?>
		</ul>
	<?php endif; ?>
	
	<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
	<fieldset>
		<legend><?php echo $this->lang['sys_add'] ?></legend>
		<div class="col1"><?php echo $this->lang['catparent'] ?></div>
	    <div class="col2">
	        <select name="parentcat" id="parentcat">
	        <?php 
	        	foreach ($this->cat as $value){
	        		echo '<option value="'.$value['cat_id'].'">'.$value['title_prefix'].$value['cat_title'.LANG].'</option>';
	        	}
	        ?>
	        </select>
	    </div>
	    <div class="clear space"></div>
		
	    <?php
	        $lang = $this->langlist();
	        foreach($lang as $value){
	            echo '<div class="col1">'.$this->lang['supplier_title'].' '.$value.'</div>
	                <div class="col2">
	                    <input name="title'.$value.'" value="'.$this->items['title'.$value].'" maxlength="100" class="txt-very-large" />
	                </div>
	                <div class="clear space"></div>';
	        }
	    ?>
	    
	    <div class="col1">Slogan</div>
		<div class="col2">
			<input name="slogan" value="<?php echo $this->items['slogan']?>" maxlength="50" class="txt-very-large" />
		</div>
		<div class="clear space"></div>
		
		<div class="col1"><?php echo $this->lang['supplier_logo'] ?></div>
	    <div class="col2">
	        <input type="file" name="file_thumb" size="48%" />
	    </div>
	    <div class="clear space"></div>
		
		<div class="col1">Chuyên ngành</div>
		<div class="col2">
			<input name="expert" value="<?php echo $this->items['expert']?>" maxlength="100" class="txt-very-large" />
		</div>
		<div class="clear space"></div>
	    
	    <div class="col1">Địa chỉ</div>
		<div class="col2">
			<input name="address" value="<?php echo $this->items['address']?>" maxlength="200" class="txt-very-large" />
		</div>
		<div class="clear space"></div>
		
		<div class="col1">Liên hệ</div>
		<div class="col2">
			<input name="contact" value="<?php echo $this->items['contact']?>" maxlength="100" class="txt-very-large" />
		</div>
		<div class="clear space"></div>
		
		<div class="col1">Điện thoại <span style="color:red">*</span></div>
		<div class="col2">
			<input name="phone" value="<?php echo $this->items['phone']?>" maxlength="15" class="txt-very-large" />
		</div>
		<div class="clear space"></div>
		
		<div class="col1">Fax</div>
		<div class="col2">
			<input name="fax" value="<?php echo $this->items['fax']?>" maxlength="15" class="txt-very-large" />
		</div>
		<div class="clear space"></div>
		
		<div class="col1">Di động</div>
		<div class="col2">
			<input name="tel" value="<?php echo $this->items['tel']?>" maxlength="15" class="txt-very-large" />
		</div>
		<div class="clear space"></div>
		
		<div class="col1">Website</div>
		<div class="col2">
			<input name="website" value="<?php echo $this->items['website']?>" maxlength="200" class="txt-very-large" />
		</div>
		<div class="clear space"></div>
		
		<div class="col1">Email</div>
		<div class="col2">
			<input name="email" value="<?php echo $this->items['email']?>" maxlength="45" class="txt-very-large" />
		</div>
		<div class="clear space"></div>
	    
	    <?php 
	    	/*foreach($lang as $value){
	            echo '<div class="col1">'.$this->lang['sys_preview'].' '.$value.'</div>
	                <div class="col2">
	                    <textarea name="preview'.$value.'" cols="70" rows="10">'.$this->items['preview'.$value].'</textarea>
	                    <script type="text/javascript">
	                    //<![CDATA[
	                    	CKEDITOR.replace( \'preview'.$value.'\' );
	                    //]]>
	                    </script>
	                </div><div class="clear space"></div>';
	        }*/
	        foreach($lang as $value){
	            echo '<div class="col1">'.$this->lang['sys_detail'].' '.$value.'</div>
	                <div class="col2">
	                    <textarea name="detail'.$value.'" cols="70" rows="10">'.$this->items['detail'.$value].'</textarea>
	                    <script type="text/javascript">
	                    //<![CDATA[
	                    	CKEDITOR.replace( \'detail'.$value.'\' );
	                    //]]>
	                    </script>
	                </div><div class="clear space"></div>';
	        }
	    ?>
	    
	    <p class="rows"><a href="#" id="add-rows">Thêm hình đại diện</a></p>

	    <div class="col1"><?php echo $this->lang['sys_hot'] ?></div>
	    <div class="col2 radio">
	        <input type="radio" checked="checked" name="hot" id="nohot" value="0" /> <label for="nohot"><?php echo $this->lang['sys_nohot'] ?></label> &nbsp;&nbsp; <input type="radio" name="hot" id="hot" value="1" /> <label for="hot"><?php echo $this->lang['sys_hot'] ?></label>
	    </div>
	    <div class="clear space"></div>
	
	    <div class="col1"><?php echo $this->lang['sys_active'] ?></div>
	    <div class="col2 radio">
	        <input type="radio" checked="checked" name="active" id="active" value="1" /> <label for="active"><?php echo $this->lang['sys_active'] ?></label> &nbsp;&nbsp; <input type="radio"  name="active" id="deactive" value="0" /> <label for="deactive"><?php echo $this->lang['sys_hidden'] ?></label>
	    </div>
	    <div class="clear space"></div>
	    
	    <div class="col1">&nbsp;</div>
	    <div class="col2">
	        <input type="submit" name="submit" value="  <?php echo $this->lang['sys_add'] ?>  " class="login" /> <a href="javascript:history.back()" class="login-a"><?php echo $this->lang['sys_cancel'] ?></a>
	    </div>
	    <div class="clear space"></div>
	</fieldset>
	</form>
	<script type="text/javascript">
	$(document).ready(function(){
	    $("#add-rows").click(function(){
	        $(".rows").before('<div class="col1"><?php echo $this->lang['sys_picture'] ?></div><div class="col2"><input type="file" name="file_desc[]" size="48%" /></div><div class="clear space"></div>');
	        return false;
	    });
	});
	</script>
</div>