<div class="content">
	<?php if(count($this->error) > 0): ?>
		<ul class="error-li">
			<?php 
			foreach ($this->error as $value){
				echo '<li>'.$value.'</li>';
			}
			?>
		</ul>
	<?php endif; ?>
	<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
	<fieldset>
		<legend><?php echo $this->lang['sys_addcat'] ?></legend>
		<div class="col1"><?php echo $this->lang['catparent'] ?></div>
	    <div class="col2">
	        <select name="parent_id">
	        	<option value="0">Gốc</option>
	        	<?php 
	        		foreach($this->listcat as $value){
	        			echo '<option value="'.$value['cat_id'].'">'.$value['title_prefix'].$value['cat_title'.LANG].'</option>';
	        		}
	        	?>
	        </select>
	    </div>
	    <div class="clear space"></div>
	    
	    <?php
	        $lang = $this->langlist();
	        foreach($lang as $value){
	            echo '<div class="col1">'.$this->lang['sys_title'].' '.$value.'</div>
	                <div class="col2">
	                    <input name="cat_title'.$value.'" value="'.$this->item['cat_title'.$value].'" maxlength="45" class="txt-very-large" />
	                </div>
	                <div class="clear space"></div>';
	        }
	    ?>
		
	    <div class="col1"><?php echo $this->lang['picture_thumb'] ?></div>
	    <div class="col2">
	        <input type="file" name="file_thumb" size="48%" />
	    </div>
	    <div class="clear space"></div>
	    
	    <div class="col1"><?php echo $this->lang['sys_active'] ?></div>
	    <div class="col2 radio">
	        <input type="radio" checked="checked" name="active" id="active" value="1" /> <label for="active"><?php echo $this->lang['sys_active'] ?></label> &nbsp;&nbsp; <input type="radio"  name="active" id="deactive" value="0" /> <label for="deactive"><?php echo $this->lang['sys_hidden'] ?></label>
	    </div>
	    <div class="clear space"></div>
	    
	    <div class="col1">&nbsp;</div>
	    <div class="col2">
	        <input type="submit" name="submit" value="  <?php echo $this->lang['sys_add'] ?>  " class="login" /> <a href="/" class="login-a"><?php echo $this->lang['sys_cancel'] ?></a>
	    </div>
	    <div class="clear space"></div>
	</fieldset>
	</form>
	<script type="text/javascript">
		var the_form	= window.document.frm;
		radio_list("<?php echo $this->item['active'] ?>", the_form.active);
		select_list("<?php echo $this->item['parent_id'] ?>", the_form.parent_id);
	</script>
</div>