<h1 class="title-left"><span><?php echo $this->lang[$this->module]?></span></h1>
<div class="frame-tent-left">
	<?php if(is_array($this->item)): ?>
 		<h2 class="title-masuring"><?php echo $this->item['title']?></h2>
        <?php echo $this->item['content'] ?>        
    <?php endif;?>
    
    <?php if($this->otherItem){ ?>
    	<h2 class="title-others">Các Tin khác</h2>
		<ul class="sub-others">
    	<?php $i=0;	foreach ($this->otherItem as $value){if($i++ % 2==0){?>
        	<li>
        		<a href="<?php echo $this->baseUrl() ?>/tin-tuc/<?php echo $value['tag'] ?>.html" title='<?php echo $value['title']?>'>
        			<?php echo $value['title']?>
        		</a>
        	</li>    
        	<?php }else{ ?>
        	<li><p>
        		<a href="<?php echo $this->baseUrl() ?>/tin-tuc/<?php echo $value['tag'] ?>.html" title='<?php echo $value['title']?>'>
        			<?php echo $value['title']?>
        		</a>
        	</p></li>   
        <?php }}?>
        </ul>
     <?php }?>

</div><!--End frame tent-->
<div class="bd-bt-tenf-left"></div>