<h1 class="title-left"><span><?php echo $this->lang[$this->module]?></span></h1>
<div class="frame-tent-left">
	<?php if(is_array($this->item)): ?>
 		<h2 class="title-masuring"><?php echo $this->item['title'.LANG]?></h2>
        <?php echo html_entity_decode($this->item['content'.LANG]) ?>        
    <?php endif;?>
    
    <?php if(is_array($this->otherItem)){ ?>
    	<h2 class="title-others">Các Tin khác</h2>
		<ul class="sub-others">
    	<?php foreach ($this->otherItem as $value): ?>
        	<li>
        		<a href="<?php echo $this->baseUrl().'/'.LANGURL.$this->module ?>/index/view/id/<?php echo $value['record_id'] ?>/<?php echo $this->noneUnicode($value['title'.LANG])?>" title="<?php echo $value['title'.LANG]?>">
        			<?php echo $value['title'.LANG]?>
        		</a>
        	</li>        
        <?php endforeach;?>
        </ul>
     <?php }?>

</div><!--End frame tent-->
<div class="bd-bt-tenf-left"></div>