<h1 class="title-box"><span><?php echo $this->lang[$this->module] ?> &raquo; <?php echo $this->infocat['cat_title'.LANG] ?></span></h1>
<div class="frame-tent-right">
    <?php if (is_array($this->productcat)): ?>
        <div class="all-product">
            <?php foreach ($this->productcat as $value): ?>
                <?php
                $picthumb = ($value['pic_thumb'] != '') ? '/public/userfiles/images/' . $this->module . '/' . $value['pic_thumb'] : TEMPLATE . '/images/no-images.jpg';
                ?>
                <div class="product">
                    <div class="tent-product">
                        <div class="product-img">
                            <a href="<?php echo $this->baseUrl() ?>/san-pham/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title' . LANG] ?>">
                                <img src="<?php echo $this->baseUrl() . $picthumb ?>" alt="<?php echo $value['title' . LANG] ?>" />
                            </a>
                        </div><div class="clear"></div>

                        <h2 class="title-pro">
                            <a href="<?php echo $this->baseUrl() ?>/san-pham/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title' . LANG] ?>">
                                <strong><?php echo $value['title' . LANG] ?></strong>
                            </a>
                        </h2>
                        <p class="bton-pro">
                            <a class="bton-detail" href="<?php echo $this->baseUrl() ?>/san-pham/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title' . LANG] ?>">                             
                                <?php echo $this->lang['detail'] ?>
                            </a> 

                            <a href="<?php echo $this->baseUrl() . '/' . LANGURL ?>lien-he" title="<?php echo $this->lang['contact'] ?>" class="bton-order">
                                <?php echo $this->lang['contact'] ?>
                            </a> 
                        </p>
                    </div>
                </div>

            <?php endforeach; ?>
             <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
        </div>
    <?php else: ?>
        <?php echo $this->productcat ?>
    <?php endif; ?>
</div>

<?php
if (DEBUG_MODE)    var_dump($this->productcat);?>