<h1 class="title-box"><span><?php echo $this->lang[$this->module] ?></span></h1>
<div class="frame-tent-right">
    <?php if (is_array($this->menu_product_cat)): ?>
        <div class="all-product">
            <?php foreach ($this->menu_product_cat as $value): ?>
                <?php
                $picthumb = ($value['pic_thumb'] != '') ? '/public/userfiles/images/' . $this->module . '/' . $value['pic_thumb'] : TEMPLATE . '/images/no-images.jpg';
                ?>
                <div class="product">
                    <div class="tent-product">
                        <div class="product-img">
                            <a href="<?php echo $this->baseUrl() ?>/san-pham/<?php echo $value['tag'] ?>" title="<?php echo $value['cat_title' . LANG] ?>">
                                <img src="<?php echo $this->baseUrl() . $picthumb ?>" alt="<?php echo $value['cat_title' . LANG] ?>" />
                            </a>
                        </div><div class="clear"></div>

                        <h2 class="title-pro">
                            <a href="<?php echo $this->baseUrl() ?>/san-pham/<?php echo $value['tag'] ?>" title="<?php echo $value['cat_title' . LANG] ?>">
                                <strong><?php echo $value['cat_title' . LANG] ?></strong>
                            </a>
                        </h2>
       
                    </div>
                </div>

            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <?php echo $this->menu_product_hot ?>
    <?php endif; ?>
</div>

<?php
    if (DEBUG_MODE)
        var_dump($this->menu_product_hot);
?>