<h1 class="title-pr">Mua hàng</h1>
<table class="form_order" cellspacing="0" cellpadding="5">
	<thead>
	  <tr align="center">
		<td>Hình ảnh</td>
		<td>Tên sản phẩm</td>
		<td>Đơn giá</td>
		<td width="80">Số lượng</td>
		<td>Thành tiền</td>
		<td width="100">Hủy</td>
	  </tr>
	</thead>
	<tbody>
	<?php 
	if(!empty($this->Items)){
		$total = 0;
		foreach ($this->Items as $k => $v):
			$url = '<a href="'.$this->baseUrl('/product/index/view/id/'.$v['record_id']).'" title="'.$v['title'.LANG] .' - '. $v['cat_title'.LANG].'">';
			$pic = ($v['pic_thumb']!='') ? '<img src="'.$this->baseUrl().'/public/userfiles/images/product/'.$v['pic_thumb'].'" alt="'.$v['cat_title'].'" />' : '<img src="'.$this->baseUrl().TEMPLATE.'/images/no-images.jpg" alt="'.$v['cat_title'].'" />';
			$name = $v['title'.LANG] .' - '. $v['cat_title'.LANG];
			$price = $v['unit'];
			$num_of_dates = $this->cart[$v['record_id']];
			$total_item = $price * $num_of_dates;
			$total = $total + $total_item;

			$link_del = '<a href="'.$this->baseUrl('/product/index/cart-delete/id/'.$v['record_id']).'" title="Del '.$name.'"><img src="'.$this->baseUrl().TEMPLATE.'/images/del.png" alt="del" /></a>';
	?>
	<tr align="center">
		<td class="pic-order"><?php echo $url.$pic?></a></td>
		<td><?php echo $url?><strong><?php echo $name?></strong></a></td>
		<td><?php echo number_format($price, 3)?></td>
		<td><?php echo $num_of_dates?></td>
		<td><?php echo number_format($total_item, 3)?> VND</td>
		<td><?php echo $link_del?></td>
	</tr>
	<?php 
		endforeach;
	}else {
		echo '<tr align="center"><td colspan="6" style="text-align:center">Danh sách trống</tr>';
	}
	?>
	<tr>
		<td colspan="4" style="color:#006600; padding:3px; font-weight: bold">Tổng cộng</td>
		<td align="center"><strong><?php echo number_format($total, 3); ?></strong> VND</td>
		<td>&nbsp;</td>
	</tr>
	</tbody>
</table>

<div id="notificaion"><?php echo html_entity_decode($this->info_payment['content'.LANG]);?></div>
 
 <div id="payment_form">
	<?php 
		$fullname 	= $this->formText('fullname',$this->FormInfo['fullname']);
		$address 	= $this->formText('address',$this->FormInfo['address']);
		$phone 		= $this->formText('phone',$this->FormInfo['phone']);
		$email 		= $this->formText('email',$this->FormInfo['email']);
	?>
							 
	 <form name="payment" action="" method="post">
		<h1 class="title-pr">Thông tin đặt hàng</h1>
			<?php
				if(isset($this->messageError)){
					foreach ($this->messageError as $value){
						echo '<p class="red">'.$value.'</p>';
					}
				}
			?>
		<ul>
			<li><label>Họ và tên <span class="red">*</span>:</label><?php echo $fullname?></li>
			<li><label>Địa chỉ <span class="red">*</span>:</label><?php echo $address?></li>
		</ul>
		<ul>
			<li><label>Điện thoại <span class="red">*</span>:</label><?php echo $phone?></li>
			<li><label>Email <span class="red">*</span>:</label><?php echo $email?></li>
		</ul>
		<ul>
			<li>
				<label>Nội dung <span class="red">*</span>:</label>
				<textarea name="content" rows="10" cols="30" class="input-textarea"><?php echo $this->FormInfo['content']?></textarea>
			</li>
		</ul>
			<input name="submit" class="submit_order" type="submit" value="  HOÀN THÀNH  ">
	  </form>
</div>