<h1 class="title-box"><span><? echo $this->lang['product'] ?></span>  &raquo; <?php echo $this->productdetail['title' . LANG] ?></h1>
<div class="frame-tent-right">
     <?php $pic = ($this->productdetail['pic_full']!= '') ? '/public/userfiles/images/product/' . $this->productdetail['pic_full'] : ''?>
    <?php if($pic):?>
        <div class="frame-img-info">
            <img src="<?php echo $this->baseUrl() . $pic ?>"" />
        </div>
    <?php endif ?>
    <?php echo html_entity_decode($this->productdetail['detail' . LANG]) ?>
    <p class="black"><a href="javascript: history.go(-1)" title="Trở lại" >Trở lại</a></p>
</div> <div class="clear"></div>

<?php
if (DEBUG_MODE)
    var_dump($this->productdetail);
?>


<h1 class="title-box"><?php echo $this->lang['product_other'] ?></h1>
<div id="all-product">
    <?php if (is_array($this->productcat)): ?>
        <?php foreach ($this->productcat as $value): ?>
        <?php $picthumb = ($value['pic_thumb'] != '') ? '/public/userfiles/images/product/' . $value['pic_thumb'] : TEMPLATE . '/images/no-images.jpg'; ?>
            <div class="product-new">
                <div class="product-img-new"><a href="<?php echo $this->baseUrl() . '/' . LANGURL ?>product/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title' . LANG] ?>">
                        <img src="<?php echo $this->baseUrl() . $picthumb ?>" alt="<?php echo $value['title' . LANG] ?>" />
                    </a>
                </div><div class="clear"></div>
                <h2 class="title-pro-new"><a href="<?php echo $this->baseUrl() . '/' . LANGURL ?>product/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title' . LANG] ?>"><?php echo $value['title' . LANG] ?></a></h2>       

            </div>
        <?php endforeach; ?>
<?php endif; ?>
</div>
