<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl().TEMPLATE ?>/css/dosvn.css" />
<link rel="SHORTCUT ICON" href="<?php echo $this->baseUrl().TEMPLATE ?>/images/favicon.ico" type="image/x-icon" />
<link rel="icon" href="<?php echo $this->baseUrl().TEMPLATE ?>/images/favicon.ico" type="image/gif" />

<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>

<?php echo $this->google_analytic; ?>
</head>

<body>
<div id="wapper">
	<div id="header">
		<img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/logo.jpg" alt="logo sieu thi"/>
    </div>
    <div id="all">
        <div id="menu">
        	<ul>
        		<?php 
					$folders = $this->menubar();
					$rowsize = count($folders);
					for($i=0; $i < $rowsize; $i++){
						$target = ($folders[$i]['target']=='') ? '' : ' target="'.$folders[$i]['target'].'"';
						echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.$folders[$i]['url'].'" title="'.$folders[$i]['module'.LANG].'"'.$target.'>'.html_entity_decode($folders[$i]['module'.LANG]).'</a></li>';
					}
				?>
            </ul>
        </div>
        
        <div id="content">
			<div class="topborder"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top.gif"  alt="border top"/></div>
			<div id="lcon">
				<?php if(isset($this->menu_about)): ?>
					<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
					<h1><span><?php echo $this->lang['about'] ?></span></h1>
						<ul class="list">
						<?php 
							foreach($this->menu_about as $value){
								echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'about'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
							}
						?>
					</ul>
					<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list" /></div>
				<?php endif;?>
				
				<?php if(isset($this->menu_philosophy)): ?>
					<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
					<h1><span><?php echo $this->lang['philosophy'] ?></span></h1>
						<ul class="list">
						<?php 
							foreach($this->menu_philosophy as $value){
								echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'philosophy'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
							}
						?>
					</ul>
					<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list" /></div>
				<?php endif;?>
				
				<?php if(isset($this->menu_termsofuse)): ?>
					<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
					<h1><span><?php echo $this->lang['termsofuse'] ?></span></h1>
						<ul class="list">
						<?php 
							foreach($this->menu_termsofuse as $value){
								echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'termsofuse'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
							}
						?>
					</ul>
					<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list" /></div>
				<?php endif;?>
			
				<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
				<h1><span>supplier - list</span></h1>
					<ul class="list">
						<li><a href="supplier-list.html" title="marketing research">marketing research</a></li>
						<li><a href="#" title="marketing ATL">marketing ATL</a></li>
						<li><a href="#" title="marketing BTL">marketing BTL</a></li>
						<li><a href="#" title="event - PR - TVC">event - PR - TVC</a></li>
						<li><a href="#" title="Digital marketing">Digital marketing</a></li>
						<li><a href="#" title="giấy phép, địa điểm">giấy phép, địa điểm</a></li>
						<li><a href="#" title="MC - PG - model - expert">MC - PG - model - expert</a></li>
						<li><a href="#" title="đồng phục quảng cáo">đồng phục quảng cáo</a></li>
						<li><a href="#" title="in ấn, quà tặng">in ấn, quà tặng</a></li>
						<li><a href="#" title="booth, sân khấu">booth, sân khấu</a></li>
						<li><a href="#" title="vận chuyển, thuê xe">vận chuyển, thuê xe</a></li>
						<li><a href="#" title="cơ sở gia công">cơ sở gia công</a></li>
						<li><a href="#" title="vật tư quảng cáo">vật tư quảng cáo</a></li>
						<li><a href="#" title="âm thanh, ánh sáng, IT">âm thanh, ánh sáng, IT</a></li>
						<li><a href="#" title="dù, pallet, mascot">dù, pallet, mascot</a></li>
						<li><a href="#" title="tổng hợp">tổng hợp</a></li>
					</ul>
				<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list" /></div>
						
				<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
				<h1><span>đăng nhập</span></h1>
					<form id="login" name="login" action="">
						<ul>
							<li>username</li>
							<li class="user"><input type="text" name="username" size="15"/></li>
							<li>password</li>
							<li class="pass"><input type="text" name="pass" size="15"/></li>
							<li><input type="checkbox" name="remember" /> Remember me</li>
							<li><input type="image" src="<?php echo $this->baseUrl().TEMPLATE ?>/images/login.gif" /></li>
							
							<li class="ngang" style="margin:10px 10px"></li>                   	
							<li><a href="#" title="">forget password</a></li>
							<li><a href="dangky.html" title="Đăng ký">register</a></li>
							<li><a href="#">quyền lợi khi là thành viên ?</a></li>
						</ul>
					</form>
				<div class="btmenu"> <img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list"  /></div>
					
			    <div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
			    <h1><span>thống kê truy cập</span></h1>
			    <?php $sc = new GLT_System_SmartCounter();?>
				<ul class="statistics">
					<li>Truy cập trong ngày: <?php echo $sc->visit_today();?></li>
                    <li>Đang truy cập: <?php echo $sc->visit_online();?></li>
                    <li>Tổng số lượt truy cập: <?php echo $sc->visit_total();?></li>
				</ul>
			    <div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list"  /></div>
			</div><!--END LEFT-->            
            
			<div id="allrightcon">
            	<div id="centercon"> 
					<div id="banner">
						<?php if($this->banner):?>
							<?php foreach($this->banner as $value):?>
								<a href="<?php echo $value['banner_link']?>"><img src="<?php echo $this->baseUrl()?>/public/userfiles/images/banner/<?php echo $value['banner_url']?>" alt="" /></a>
							<?php endforeach;?>
							<script type="text/javascript" src="<?php echo $this->BaseUrl().TEMPLATE?>/js/jqFancyTransitions.1.8.min.js"></script>
							<script type="text/javascript">
								jQuery('#banner').jqFancyTransitions({ effect: 'wave', // wave, zipper, curtain
								width: <?php echo $this->config['banner_width']?>, // width of panel
								height: <?php echo $this->config['banner_height']?>, // height of panel
								strips: 20, // number of strips
								delay: 5000, // delay between images in ms
								stripDelay: 50, // delay beetwen strips in ms
								titleOpacity: 0.7, // opacity of title
								titleSpeed: 1000, // speed of title appereance in ms
								position: 'alternate', // top, bottom, alternate, curtain
								direction: 'random', // left, right, alternate, random, fountain, fountainAlternate
								navigation: false, // prev and next navigation buttons
								links: false // show images as links
								 });
							</script>
						<?php else:?>
							<img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/banner.jpg" alt="Banner" />
						<?php endif;?>
					</div>
					<?php echo $this->layout()->content ?>
				</div><!--End centercon-->
                    
                <div id="rightcon">
                	<?php if($this->list_adv_right_top):?>
					<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
					<h1><span>sản phẩm mới</span></h1>
					<ul>
						<?php foreach ($this->list_adv_right_top as $value):?>
						<li><a href="<?php echo $value['url']?>" target="<?php echo $value['type']?>" title="<?php echo $value['title'.LANG].' - '.$value['description']?>"><img src="<?php echo $this->baseUrl() ?>/public/userfiles/images/adv/<?php echo $value['pic_thumb']?>" alt="<?php echo $value['title'.LANG].' - '.$value['description']?>"/></a></li>
						<?php endforeach;?>
					</ul>
					<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list"  /></div>
					<?php endif;?>   
						
					<?php if($this->list_adv_right_bottom):?>		   
					 <div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
						<h1><span>quảng cáo</span></h1>
						<ul>
							<?php foreach ($this->list_adv_right_bottom as $value):?>
							<li><a href="<?php echo $value['url']?>" target="<?php echo $value['type']?>" title="<?php echo $value['title'.LANG].' - '.$value['description']?>"><img src="<?php echo $this->baseUrl() ?>/public/userfiles/images/adv/<?php echo $value['pic_thumb']?>" alt="<?php echo $value['title'.LANG].' - '.$value['description']?>"/></a></li>
							<?php endforeach;?>
						</ul>
					<div class="btmenu"> <img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list"  /></div>
					<?php endif;?>
				</div><!--End rightcon-->
            </div>
        <div class="clear"></div>
        <div class="btborder"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bottom.gif" alt="bottom" /></div>
   	</div>
    	<div id="footer"><?php echo $this->lang['copyright']?><p><?php echo $this->lang['developed']?></p></div>
    </div>
</div><!--end warpper-->
</body>
</html>