<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl().TEMPLATE ?>/css/dosvn.css" />
<link rel="SHORTCUT ICON" href="<?php echo $this->baseUrl().TEMPLATE ?>/images/favicon.ico" type="image/x-icon" />
<link rel="icon" href="<?php echo $this->baseUrl().TEMPLATE ?>/images/favicon.ico" type="image/gif" />

<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>

<?php echo $this->google_analytic; ?>
</head>
<body>
<div id="wrapper">
	<div id="header">
    	<div id="header-left"><a href="<?php echo $this->baseUrl()?>/" title="Logo <?php echo $this->web['titleweb']?>"><img src="<?php echo $this->baseUrl().TEMPLATE?>/images/logo-title.png" alt="Logo <?php echo $this->web['titleweb']?>" /></a></div>
        <div id="header-right"><img src="<?php echo $this->baseUrl().TEMPLATE?>/images/logo.png" alt="Logo <?php echo $this->web['titleweb']?>" /></div>
    </div><!--End header-->
    <div class="clear"></div>
    <div id="page">
    	<div id="bg-menu">
            <ul class="menu">
            	<?php
					$folders = $this->menubar();
					foreach($folders as $models){		
						$target = ($models['target']=='') ? '' : ' target="'.$models['target'].'"';
						$select =($this->module==$models['url']) ? ' class="select"': '';
						echo '<li'.$select.'><a href="'.$this->baseUrl().'/'.LANGURL.$models['url'].'" title="'.$models['module'.LANG].'"'.$target.'>'.html_entity_decode($models['module'.LANG]).'</a></li>';
					}
				?>
            </ul><!--End menu-->
        </div><!--End Bg menu-->
        <div class="clear"></div>
        <div id="allcontent">
        	<div id="leftcontent">
                <?php if(isset($this->menu_product) && is_array($this->menu_product)): ?>
                	<h1 class="title-left"><span><?php echo $this->lang['product'] ?></span></h1>
					<ul class="list">
						<?php 
							$rowsize = count($this->menu_product);
							$params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
							$cat_id = isset($params['cid']) ? intval($params['cid']) : 0;
							
							//Find parent_id
							$parent_id	= $cat_id;
			            	if ( $cat_id ){
			            		for ($i=0; $i < $rowsize; $i++){
			            			if ($cat_id == $this->menu_product[$i]['cat_id']){
			            				if ( $this->menu_product[$i]['cat_parent_id'] ){
			            					$parent_id = $this->menu_product[$i]['cat_parent_id'];
			            				}
			            				break;
			            			}
			            		}
			            	}
			            	
			            	//Display cat menu
			            	for ($i=0; $i < $rowsize; $i++){
			            		if ( $this->menu_product[$i]['cat_parent_id'] == 0 ){
			            			//Parent categories
			            			echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'product/index/cat/cid/'.$this->menu_product[$i]['cat_id'].'" title="'.$this->menu_product[$i]['cat_title'.LANG].'">'.$this->menu_product[$i]['cat_title'.LANG].'</a>';
				            		//Sub categories
			            			if ( $parent_id && ($parent_id == $this->menu_product[$i]['cat_id']) ){
			            				for ($j=0; $j < $rowsize; $j++){
			            					if ( $this->menu_product[$j]['cat_parent_id'] == $this->menu_product[$i]['cat_id'] ){
			            						echo '<ul class="sub">';
					            					for ($j=0; $j < $rowsize; $j++){
					            						if ( $this->menu_product[$j]['cat_parent_id'] == $this->menu_product[$i]['cat_id'] ){
				                                            echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'product/index/cat/cid/'.$this->menu_product[$j]['cat_id'].'" title="'.$this->menu_product[$j]['cat_title'.LANG].'">'.$this->menu_product[$j]['cat_title'.LANG].'</a></li>';
				                                        }
				                                    }
			                                    echo '</ul>';
			            					}
			            				}
			            			}
			            			echo '</li>';
			            		}
			            	}
						?>
					</ul>
				<?php endif;?>

                <?php if(isset($this->menu_about)): ?>
                <h1 class="title-left"><span><?php echo $this->lang['about'] ?></span></h1>
				<ul class="about-list">
					<?php 
						foreach($this->menu_about as $value){
							echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'about'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
						}
					?>
				</ul>
				<div class="bt-bder-left"></div>
				<?php endif;?>
				
				<?php if(isset($this->menu_services)): ?>
                <h1 class="title-left"><span><?php echo $this->lang['services'] ?></span></h1>
				<ul class="about-list">
					<?php 
						foreach($this->menu_services as $value){
							echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'services'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
						}
					?>
				</ul>
				<div class="bt-bder-left"></div>
				<?php endif;?>
                
                <?php if(is_array($this->product_hot)):?>
	                <h1 class="title-left"><span><?php echo $this->lang['product_hot']?></span></h1>
	                <ul class="img-list">
	                	<?php foreach ($this->product_hot as $value):?>
	                		<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/product/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg';?>
	                		<li><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/view/id/<?php echo $value['record_id'] ?>/<?php echo $this->noneUnicode($value['title'.LANG])?>" title="<?php echo $value['title'.LANG]?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" alt="<?php echo $value['title'.LANG]?>" /></a></li>
	                	<?php endforeach;?>
	                </ul>
	                <div class="bt-bder-left"></div>
                <?php endif;?>

                <?php if(isset($this->menu_support)): ?>
	                <h1 class="title-left"><span><?php echo $this->lang['support']?></span></h1>
	                <ul class="support">
	                	<?php foreach ($this->menu_support as $value): ?>
	                		<li><?php echo $value['support_name'] ?></li>
	                    	<li><a href="ymsgr:sendim?<?php echo $value['support_value'] ?>&amp;m=<?php echo $this->lang['welcome_chat']?>" title="Chat <?php echo $value['support_value'] ?>"><img src="http://opi.yahoo.com/online?u=<?php echo $value['support_value'] ?>&amp;m=g&amp;t=2&amp;l=us" alt="<?php echo $value['support_value'] ?>" /></a></li>
	                   	<?php endforeach;?>
	                </ul>
	                <div class="bt-bder-left"></div>
	            <?php endif;?>
                
                <h1 class="title-left"><span><?php echo $this->lang['counter']?></span></h1>
                <?php $sc = new GLT_System_SmartCounter();?>
				<ul class="statistics">
					<li>Truy cập trong ngày: <?php echo $sc->visit_today();?></li>
                    <li>Đang truy cập: <?php echo $sc->visit_online();?></li>
                    <li>Tổng số lượt truy cập: <?php echo $sc->visit_total();?></li>
				</ul>
                <div class="bt-bder-left"></div>
            </div><!--End left content-->
            
            <div id="rightcontent">
            	<div id="banner">
                	<div class="container">
						<?php if($this->banner):?>
							<div class="wt-rotator">
								<a href="#"></a>   
								<div class="thumbnails"> 
									  <ul>
											<?php foreach($this->banner as $value):?>
												<li><a href="<?php echo $this->baseUrl()?>/public/userfiles/images/banner/<?php echo $value['banner_url']?>" title="<?php echo $value['banner_name']?>"></a></li>
											<?php endforeach;?>
									  </ul>
									  <script type="text/javascript">
										$(document).ready(function(){
											runbanner(<?php echo $this->config['banner_width']?>, <?php echo $this->config['banner_height']?>);
										});
									</script>
								</div>  
							</div>
						<?php else:?>
							<img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/banner.jpg" alt="Banner" />
						<?php endif;?>
                    </div>
                </div><!--End banner-->
                
                <?php echo $this->layout()->content ?>
                
            </div><!--End right content-->
        </div><!--End All content-->
        <div class="clear"></div>
		<!--Footer-->
		<div id="footer">
        	<p><?php echo $this->lang['copyright']?></p>
            <p><?php echo $this->lang['developed']?> <a href="http://azweb.vn" title="azweb.vn">azweb.vn</a></p>
		</div><!--End footer-->
    </div><!--End Page-->
</div><!--End wrapper-->

</body>
</html>