<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name='robots' content='all, follow' />
    <link href="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/css/login.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/css/login-blue.css" rel="stylesheet" type="text/css" />
    <link rel="SHORTCUT ICON" href="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/favicon.ico" type="image/gif" />
    <script type="text/javascript"> 
        function setFocus(){
            document.getElementById("username").focus();
        }
    </script>
    <?php echo $this->headTitle() ?>
   	<?php echo $this->headMeta() ?>
   	<?php echo $this->headLink() ?>
   	<?php echo $this->headScript() ?>
   	
   	<?php if (count($this->messages)) : ?>
   	<script type="text/javascript">
   		<?php $str = ''; foreach ($this->messages as $message) : ?>
   			<?php $str .= $this->escape($message).'\n'; ?>
   		<?php endforeach; ?>
   		<?php echo 'alert("'.$str.'")'; ?>
    </script>
	<?php endif; ?>
</head>
<body onload="setFocus();">
<?php echo $this->layout()->content ?>
</body>
</html>