<h1 class="title-pr">Thông tin giỏ hàng</h1>
<form name="order" action="" method="post">
	<table class="form_order" cellspacing="0" cellpadding="5" width="100%">
	<thead>
	  <tr align="center">
		<td width="150">Hình ảnh</td>
		<td>Tên sản phẩm</td>
		<td>Đơn giá</td>
		<td width="80">Số lượng</td>
		<td>Thành tiền</td>
		<td width="100">Hủy</td>
	  </tr>
	</thead>
	<tbody>
		<?php 
		if(!empty($this->Items)){
			foreach ($this->Items as $k => $v):
				$url = '<a href="'.$this->baseUrl('/product/index/view/id/'.$v['record_id']).'" title="'.$v['title'.LANG] .' - '. $v['cat_title'.LANG].'">';
				$pic = ($v['pic_thumb']!='') ? '<img src="'.$this->baseUrl().'/public/userfiles/images/product/'.$v['pic_thumb'].'" alt="'.$v['cat_title'].'" />' : '<img src="'.$this->baseUrl().TEMPLATE.'/images/no-images.jpg" alt="'.$v['cat_title'].'" />';
				$name = $v['title'.LANG] .' - '. $v['cat_title'.LANG];
				$price = $v['unit'];
				$num_of_dates = $this->formText('num_of_dates['.$v['record_id'].']', $this->cart[$v['record_id']], array('style'=>'width:30px;text-align: center;', 'maxlength'=>3));
				$total_item = $price * $this->cart[$v['record_id']];
				
				$link_del = '<a href="'.$this->baseUrl('/product/index/cart-delete/id/'.$v['record_id']).'" title="Del '.$name.'"><img src="'.$this->baseUrl().TEMPLATE.'/images/del.png" alt="del" /></a>';
		?>
		<tr align="center">
			<td class="pic-order"><?php echo $url.$pic?></a></td>
			<td><?php echo $url?><strong><?php echo $name?></strong></a></td>
			<td><?php echo number_format($price, 3)?></td>
			<td><?php echo $num_of_dates?></td>
			<td><?php echo number_format($total_item, 3) ?> VND</td>
			<td><?php echo $link_del?></td>
		</tr>
		<?php 
			endforeach;
		}else {
			echo '<tr align="center"><td colspan="6" style="text-align:center; padding:5px 0">Danh sách trống</td></tr>';
		}
		?>
	</tbody>
</table>
<div class="panel-order"><input type="submit" value=" THANH TOÁN " /> <a href="javascript:history.back()" class="btn_order" title="tiếp tục mua hàng"><strong>TIẾP TỤC MUA HÀNG</strong></a></div>
</form>