<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl().TEMPLATE ?>/css/dosvn.css" />
<link rel="SHORTCUT ICON" href="<?php echo $this->baseUrl().TEMPLATE ?>/images/favicon.ico" type="image/x-icon" />
<link rel="icon" href="<?php echo $this->baseUrl().TEMPLATE ?>/images/favicon.ico" type="image/gif" />

<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>

<?php echo $this->google_analytic; ?>
</head>

<body>
<div id="wapper">
	<div id="header">
		<a href="<?php echo $this->baseUrl()?>/" title="Logo <?php echo $this->web['titleweb']?>"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/logo.png" alt="logo <?php echo $this->web['titleweb']?>"/></a>
		<div class="clock">
			<script src="http://www.clocklink.com/embed.js" type="text/javascript"></script><script type="text/javascript" language="JavaScript">obj=new Object;obj.clockfile="0008-red.swf";obj.TimeZone="VietNam_HoChiMinhCity";obj.width=110;obj.height=110;obj.wmode="transparent";showClock(obj);</script>
			<p><a href="<?php echo $this->baseUrl()?>/" target="_blank" title="Logo <?php echo $this->web['titleweb']?>">Visit my homepage</a></p>
		</div>
    </div>
    <div id="all">
        <div id="menu">
        	<ul>
        		<?php 
        			$folders = $this->menubar();
					foreach($folders as $models){		
						$target = ($models['target']=='') ? '' : ' target="'.$models['target'].'"';
						$select =($this->module==$models['url']) ? ' class="select"': '';
						echo '<li'.$select.'><a href="'.$this->baseUrl().'/'.LANGURL.$models['url'].'" title="'.$models['module'.LANG].'"'.$target.'>'.html_entity_decode($models['module'.LANG]).'</a></li>';
					}
				?>
            </ul>
        </div>
        
        <div id="content">
			<div class="topborder"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top.gif"  alt="border top"/></div>
			<div id="lcon">
				<?php if(isset($this->menu_about)): ?>
					<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
					<h1><span><?php echo $this->lang['about'] ?></span></h1>
						<ul class="list">
						<?php 
							foreach($this->menu_about as $value){
								echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'about'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
							}
						?>
					</ul>
					<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list" /></div>
				<?php endif;?>
				
				<?php if(isset($this->menu_philosophy)): ?>
					<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
					<h1><span><?php echo $this->lang['philosophy'] ?></span></h1>
						<ul class="list">
						<?php 
							foreach($this->menu_philosophy as $value){
								echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'philosophy'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
							}
						?>
					</ul>
					<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list" /></div>
				<?php endif;?>
				
				<?php if(isset($this->menu_termsofuse)): ?>
					<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
					<h1><span><?php echo $this->lang['termsofuse'] ?></span></h1>
						<ul class="list">
						<?php 
							foreach($this->menu_termsofuse as $value){
								echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'termsofuse'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
							}
						?>
					</ul>
					<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list" /></div>
				<?php endif;?>
			
				<?php if(isset($this->menu_studies) && is_array($this->menu_studies)): ?>
					<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
					<h1><span><?php echo $this->lang['studies'] ?></span></h1>
						<ul class="list">
							<?php 
								$rowsize = count($this->menu_studies);
								$params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
								$cat_id = isset($params['cid']) ? intval($params['cid']) : 0;
								
								//Find parent_id
								$parent_id	= $cat_id;
				            	if ( $cat_id ){
				            		for ($i=0; $i < $rowsize; $i++){
				            			if ($cat_id == $this->menu_studies[$i]['cat_id']){
				            				if ( $this->menu_studies[$i]['cat_parent_id'] ){
				            					$parent_id = $this->menu_studies[$i]['cat_parent_id'];
				            				}
				            				break;
				            			}
				            		}
				            	}
				            	
				            	//Display cat menu
				            	for ($i=0; $i < $rowsize; $i++){
				            		if ( $this->menu_studies[$i]['cat_parent_id'] == 0 ){
				            			//Parent categories
				            			echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'studies/index/cat/cid/'.$this->menu_studies[$i]['cat_id'].'/'.$this->noneUnicode($this->menu_studies[$i]['cat_title'.LANG]).'" title="'.$this->menu_studies[$i]['cat_title'.LANG].'">'.$this->menu_studies[$i]['cat_title'.LANG].'</a>';
					            		//Sub categories
				            			if ( $parent_id && ($parent_id == $this->menu_studies[$i]['cat_id']) ){
				            				for ($j=0; $j < $rowsize; $j++){
				            					if ( $this->menu_studies[$j]['cat_parent_id'] == $this->menu_studies[$i]['cat_id'] ){
				            						echo '<ul class="sub">';
						            					for ($j=0; $j < $rowsize; $j++){
						            						if ( $this->menu_studies[$j]['cat_parent_id'] == $this->menu_studies[$i]['cat_id'] ){
					                                            echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'studies/index/cat/cid/'.$this->menu_studies[$j]['cat_id'].'/'.$this->noneUnicode($this->menu_studies[$j]['cat_title'.LANG]).'" title="'.$this->menu_studies[$j]['cat_title'.LANG].'">'.$this->menu_studies[$j]['cat_title'.LANG].'</a></li>';
					                                        }
					                                    }
				                                    echo '</ul>';
				            					}
				            				}
				            			}
				            			echo '</li>';
				            		}
				            	}
							?>
						</ul>
					<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list" /></div>
				<?php endif;?>
				
				<?php if(isset($this->menu_marketing) && is_array($this->menu_marketing)): ?>
					<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
					<h1><span><?php echo $this->lang['marketing'] ?></span></h1>
						<ul class="list">
							<?php 
								$rowsize = count($this->menu_marketing);
								$params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
								$cat_id = isset($params['cid']) ? intval($params['cid']) : 0;
								
								//Find parent_id
								$parent_id	= $cat_id;
				            	if ( $cat_id ){
				            		for ($i=0; $i < $rowsize; $i++){
				            			if ($cat_id == $this->menu_marketing[$i]['cat_id']){
				            				if ( $this->menu_marketing[$i]['cat_parent_id'] ){
				            					$parent_id = $this->menu_marketing[$i]['cat_parent_id'];
				            				}
				            				break;
				            			}
				            		}
				            	}
				            	
				            	//Display cat menu
				            	for ($i=0; $i < $rowsize; $i++){
				            		if ( $this->menu_marketing[$i]['cat_parent_id'] == 0 ){
				            			//Parent categories
				            			echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'marketing/index/cat/cid/'.$this->menu_marketing[$i]['cat_id'].'/'.$this->noneUnicode($this->menu_marketing[$i]['cat_title'.LANG]).'" title="'.$this->menu_marketing[$i]['cat_title'.LANG].'">'.$this->menu_marketing[$i]['cat_title'.LANG].'</a>';
					            		//Sub categories
				            			if ( $parent_id && ($parent_id == $this->menu_marketing[$i]['cat_id']) ){
				            				for ($j=0; $j < $rowsize; $j++){
				            					if ( $this->menu_marketing[$j]['cat_parent_id'] == $this->menu_marketing[$i]['cat_id'] ){
				            						echo '<ul class="sub">';
						            					for ($j=0; $j < $rowsize; $j++){
						            						if ( $this->menu_marketing[$j]['cat_parent_id'] == $this->menu_marketing[$i]['cat_id'] ){
					                                            echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'marketing/index/cat/cid/'.$this->menu_marketing[$j]['cat_id'].'/'.$this->noneUnicode($this->menu_marketing[$j]['cat_title'.LANG]).'" title="'.$this->menu_marketing[$j]['cat_title'.LANG].'">'.$this->menu_marketing[$j]['cat_title'.LANG].'</a></li>';
					                                        }
					                                    }
				                                    echo '</ul>';
				            					}
				            				}
				            			}
				            			echo '</li>';
				            		}
				            	}
							?>
						</ul>
					<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list" /></div>
				<?php endif;?>
				
				<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
				<h1><span><?php echo $this->lang['supplier'] ?></span></h1>
					<ul class="list">
						<?php 
							if(is_array($this->listSupplierCat))
								foreach($this->listSupplierCat as $value){
									echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'supplier'.'/index/view/cid/'.$value['cat_id'].'/title/'.$this->noneUnicode($value['cat_title'.LANG]).'" title="'.$this->escape($value['cat_title'.LANG]).'">'.$this->escape($value['cat_title'.LANG]).'</a></li>';
								}
						?>
					</ul>
				<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list" /></div>
						
				<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
				<?php if(!$this->checklogin()): ?>
					<h1><span>đăng nhập</span></h1>
					<form method="post" id="login" name="login" action="<?php echo $this->baseUrl()?>/login">
						<ul>
							<li>username</li>
							<li class="user"><input type="text" name="username" size="15"/></li>
							<li>password</li>
							<li class="pass"><input type="password" name="password" size="15"/></li>
							<!-- <li><input type="checkbox" name="remember" />Remember me</li> -->
							<li class="login"><input type="image" src="<?php echo $this->baseUrl().TEMPLATE ?>/images/login.gif" /></li>
							<li><a href="#" title="">forget password</a></li>
							<li><a href="<?php echo $this->baseUrl()?>/register" title="Đăng ký">register</a></li>
							<li><a href="<?php echo $this->baseUrl()?>/interests">quyền lợi khi là thành viên ?</a></li>
						</ul>
					</form>
				<?php else: ?>
					<h1><span>Bảng điều khiển</span></h1>
					<ul class="statistics">
						<li>Chào <strong><?php echo $this->infouser('username')?></strong></li>
						<li class="center"><a href="<?php echo $this->baseUrl()?>/login/index/logout" title="Thoát"><img src="<?php echo $this->baseUrl().TEMPLATE?>/images/logout.png" alt="Thoát" /></a></li>
					</ul>
				<?php endif;?>		
				<div class="btmenu"> <img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list"  /></div>
				
				<?php if(isset($this->menu_support)): ?>
				    <div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
				    <h1><span>Hỗ trợ trực tuyến</span></h1>
					<ul class="statistics center">
						<?php foreach ($this->menu_support as $value): ?>
							<li><?php echo $value['support_name'] ?></li>
							<li><a href="ymsgr:sendim?<?php echo $value['support_value'] ?>&amp;m=<?php echo $this->lang['welcome_chat']?>" title="Chat <?php echo $value['support_value'] ?>"><img src="http://opi.yahoo.com/online?u=<?php echo $value['support_value'] ?>&amp;m=g&amp;t=2&amp;l=us" alt="<?php echo $value['support_value'] ?>" /></a></li>
						<?php endforeach;?>
					</ul>
				    <div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list"  /></div>
			    <?php endif;?>
			    
			    <div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
			    <h1><span>Thống kê truy cập</span></h1>
			    <?php $sc = new GLT_System_SmartCounter();?>
				<ul class="statistics">
					<li>Truy cập trong ngày: <?php echo $sc->visit_today();?></li>
                    <li>Đang truy cập: <?php echo $sc->visit_online();?></li>
                    <li>Tổng lượt truy cập: <?php echo $sc->visit_total();?></li>
				</ul>
			    <div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list"  /></div>
			</div><!--END LEFT-->            
            
			<div id="allrightcon">
            	<div id="centercon"> 
					<div id="banner">
						<?php if($this->banner):?>
							<?php foreach($this->banner as $value):?>
								<a href="<?php echo $value['banner_link']?>"><img src="<?php echo $this->baseUrl()?>/public/userfiles/images/banner/<?php echo $value['banner_url']?>" alt="" /></a>
							<?php endforeach;?>
							<script type="text/javascript" src="<?php echo $this->BaseUrl().TEMPLATE?>/js/jqFancyTransitions.1.8.min.js"></script>
							<script type="text/javascript">
								jQuery('#banner').jqFancyTransitions({ effect: 'wave', // wave, zipper, curtain
								width: <?php echo $this->config['banner_width']?>, // width of panel
								height: <?php echo $this->config['banner_height']?>, // height of panel
								strips: 20, // number of strips
								delay: 4000, // delay between images in ms
								stripDelay: 50, // delay beetwen strips in ms
								titleOpacity: 0.7, // opacity of title
								titleSpeed: 1000, // speed of title appereance in ms
								position: 'alternate', // top, bottom, alternate, curtain
								direction: 'random', // left, right, alternate, random, fountain, fountainAlternate
								navigation: false, // prev and next navigation buttons
								links: false // show images as links
								 });
							</script>
						<?php else:?>
							<img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/banner.jpg" alt="Banner" />
						<?php endif;?>
					</div>
					<?php echo $this->layout()->content ?>
				</div><!--End centercon-->
                    
                <div id="rightcon">
                	<?php if($this->list_adv_right_top):?>
					<div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
					<h1><span>sản phẩm mới</span></h1>
					<ul>
						<?php foreach ($this->list_adv_right_top as $value):?>
						<li><a href="<?php echo $value['url']?>" target="<?php echo $value['type']?>" title="<?php echo $value['title'.LANG].' - '.$value['description']?>"><img src="<?php echo $this->baseUrl() ?>/public/userfiles/images/adv/<?php echo $value['pic_thumb']?>" alt="<?php echo $value['title'.LANG].' - '.$value['description']?>"/></a></li>
						<?php endforeach;?>
					</ul>
					<div class="btmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list"  /></div>
					<?php endif;?>   
						
					<?php if($this->list_adv_right_bottom):?>		   
					 <div class="topmenu"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/top-mn-list.gif" alt="border top menu" /></div>
						<h1><span>quảng cáo</span></h1>
						<ul>
							<?php foreach ($this->list_adv_right_bottom as $value):?>
							<li><a href="<?php echo $value['url']?>" target="<?php echo $value['type']?>" title="<?php echo $value['title'.LANG].' - '.$value['description']?>"><img src="<?php echo $this->baseUrl() ?>/public/userfiles/images/adv/<?php echo $value['pic_thumb']?>" alt="<?php echo $value['title'.LANG].' - '.$value['description']?>"/></a></li>
							<?php endforeach;?>
						</ul>
					<div class="btmenu"> <img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bd-mn-list.gif" alt="border menu list"  /></div>
					<?php endif;?>
				</div><!--End rightcon-->
            </div>
        <div class="clear"></div>
        <div class="btborder"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/bottom.gif" alt="bottom" /></div>
   	</div>
    	<div id="footer"><?php echo $this->lang['copyright']?><p><?php echo $this->lang['developed']?></p></div>
    </div>
</div><!--end warpper-->
</body>
</html>