<h1 class="title-right"><span>VỀ CÔNG TY</span></h1>
				<div class="frame-tent-right">
					<img src="images/gioithieu.jpg" alt="img loi chao" style="float:left"/>
					<p>Công ty chuyên sản xuất và kinh doanh các loại thiết bị hàn, cắt, dây hàn lõi thuốc và vật tư cho ngành hàn. Đồng thời, chúng tôi cũng sản xuất các loại tủ bảng điện tàu thủy và công nghiệp. Ngoài ra, chúng tôi còn hoạt động trong lĩnh vực thương mại cung cấp thiết bị, vật tư cho ngành đóng tàu và các ngành công nghiệp khác.</p>
					<p>Việc sản xuất rộng rãi các sản phẩm trong lĩnh vực công nghiệp của chúng tôi được dựa trên một chặng đường tích lũy kinh nghiệm qua nhiều năm. Chúng tôi được biết đến là một đối tác tin cậy cho các ngành đóng tàu, kết cấu thép, cơ khí, xây dựng, dầu khí, v.v…
</p>
					<p>Bên cạnh đó, chúng tôi luôn duy trì mối quan hệ tốt đẹp với các đối tác trong và ngoài nước trong lĩnh vực hàn và thiết kế tàu biển để luôn không ngừng cải tiến, nâng cao chất lượng sản phẩm và đưa ra các giải pháp tốt nhất phục vụ mọi yêu cầu của khách hàng.</p>
					
				</div> <!--End frame tent right-->