<?php if(isset($this->menu_about_home)): ?>
    <h1 class="title-box"><span><?php echo $this->lang['about_coperation']?></span></h1>
    <div class="frame-tent-right">
        <b><?php echo $this->menu_about_home['title'] ?></b>
        <?php echo $this->menu_about_home['content'] ?>
    </div> <!--End frame tent right-->
<?php endif;?>
<?php
if (DEBUG_MODE)
    var_dump($this->menu_about_home);?>
    
<div class="all-product">
    <h1 class="title-all-pro"><span>SẢN PHẨM NỔI BẬT</span></h1>
    <div class="product">
        <div class="tent-product">
            <div class="product-img"><a href="product-info.html" title=""><img src="images/pro-img.jpg" alt="Product" /></a></div><div class="clear"></div>
            <h2 class="title-pro"><a href="product-info.html" title="">Thông tin tóm tắt sản phẩm 1</a></h2>
            <p class="bton-pro"><a href="product-info.html" title="CHI TIẾT" class="bton-detail">CHI TIẾT</a> <a href="order.html" title="ĐẶT HÀNG" class="bton-order">ĐẶT HÀNG</a> </p>
        </div>
    </div>
</div> <!--End all product-->