<h1 class="title-right"><span><?php echo $this->lang[$this->module]?> &raquo; <?php echo $this->item['title'.LANG]?></span></h1>
<div class="frame-tent-right">	
	<?php if(is_array($this->item)): ?>
        <?php echo $this->item['content'.LANG] ?>        
    <?php endif;?>
    
    
<!--    <div class="clear"></div>
    <?php if(is_array($this->otherItem)){ ?>
    	 <h2 class="title-masuring">Các Tin khác</h2>
		<ul class="sub-others">
        	<?php foreach ($this->otherItem as $value): ?>
            	<li>
            		<a href="<?php echo $this->baseUrl().'/'.LANGURL.$this->module ?>/index/view/id/<?php echo $value['record_id'] ?>/<?php echo $this->noneUnicode($value['title'.LANG])?>" title="<?php echo $value['title'.LANG]?>">
            			<?php echo $value['title'.LANG]?>
            		</a>
            	</li>       
            <?php endforeach?>
        </ul>
     <?php }?>
-->
</div><!--End frame tent-->
