<div class="content">
    <?php if (count($this->error) > 0): ?>
        <ul class="error-li">
            <?php
            foreach ($this->error as $value) {
                echo '<li>' . $value . '</li>';
            }
            ?>
        </ul>
    <?php endif; ?>

    <form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
        <fieldset>
            <legend><?php echo $this->lang['sys_edit'] ?></legend>
            <div class="col1"><?php echo $this->lang['catparent'] ?></div>
            <div class="col2">
                <select name="parentcat" id="parentcat">
                    <?php
                    foreach ($this->cat as $value) {
                        echo '<option value="' . $value['cat_id'] . '">' . $value['title_prefix'] . $value['cat_title' . LANG] . '</option>';
                    }
                    ?>
                </select>
            </div>
            <div class="clear space"></div>

            <?php
            $lang = $this->langlist();
            foreach ($lang as $value) {
                echo '<div class="col1">' . $this->lang['sys_title'] . ' ' . $value . '</div>
	                <div class="col2">
	                    <input id="title' . $value . '" name="title' . $value . '" value="' . $this->item['title' . $value] . '" maxlength="100" class="txt-very-large" />
	                </div>
	                <div class="clear space"></div>';
            }
            foreach ($lang as $value) {
                echo '<div class="col1">' . $this->lang['sys_preview'] . ' ' . $value . '</div>
	                <div class="col2">
	                    <textarea name="preview' . $value . '" cols="70" rows="10">' . $this->item['preview' . $value] . '</textarea>
	                    <script type="text/javascript">
	                    //<![CDATA[
	                    	CKEDITOR.replace( \'preview' . $value . '\' );
	                    //]]>
	                    </script>
	                </div><div class="clear space"></div>';
            }
            foreach ($lang as $value) {
                echo '<div class="col1">' . $this->lang['sys_detail'] . ' ' . $value . '</div>
	                <div class="col2">
	                    <textarea name="detail' . $value . '" cols="70" rows="10">' . $this->item['content' . $value] . '</textarea>
	                    <script type="text/javascript">
	                    //<![CDATA[
	                    	CKEDITOR.replace( \'detail' . $value . '\' );
	                    //]]>
	                    </script>
	                </div><div class="clear space"></div>';
            }
            ?>

            <div class="col1">Liên kết</div>
            <div class="col2">
                <input name="tag" id="tag" value="<?php echo $this->item['tag'] ?>" maxlength="100" class="txt-very-large" />
            </div>
            <div class="clear space"></div>

            <div class="col1">Mô tả</div>
            <div class="col2">
                <textarea cols="89" rows="5" name="description" id="description"><?php echo $this->item['description'] ?></textarea> <span class="info-keyup">0</span>
            </div>
            <div class="clear space"></div>

            <div class="col1"><?php echo $this->lang['picture_thumb'] ?></div>
            <div class="col2">
                <?php if ($this->item['pic_thumb'] != null): ?>
                    <input type="hidden" name="fileold_thumb" value="<?php echo $this->item['pic_thumb'] ?>" />
                    <div class="border-img"><img src="<?php echo $this->baseUrl() . '/public/userfiles/images/' . $this->controller . '/' . $this->item['pic_thumb'] ?>" alt="" /></div>
                <?php endif; ?>
                <input type="file" name="file_thumb" size="48%" />
            </div>
            <div class="clear space"></div>

            <div class="col1"><?php echo $this->lang['sys_hot'] ?></div>
            <div class="col2 radio">
                <input type="radio" checked="checked" name="hot" id="nohot" value="0" /> <label for="nohot"><?php echo $this->lang['sys_nohot'] ?></label> &nbsp;&nbsp; <input type="radio" name="hot" id="hot" value="1" /> <label for="hot"><?php echo $this->lang['sys_hot'] ?></label>
            </div>
            <div class="clear space"></div>

            <div class="col1"><?php echo $this->lang['sys_active'] ?></div>
            <div class="col2 radio">
                <input type="radio" checked="checked" name="active" id="active" value="1" /> <label for="active"><?php echo $this->lang['sys_active'] ?></label> &nbsp;&nbsp; <input type="radio"  name="active" id="deactive" value="0" /> <label for="deactive"><?php echo $this->lang['sys_hidden'] ?></label>
            </div>
            <div class="clear space"></div>

            <div class="col1">&nbsp;</div>
            <div class="col2">
                <input type="submit" name="submit" value="  <?php echo $this->lang['sys_edit'] ?>  " class="login" /> <a href="/" class="login-a"><?php echo $this->lang['sys_cancel'] ?></a>
            </div>
            <div class="clear space"></div>
        </fieldset>
    </form>
    <script type="text/javascript">
        var the_form = window.document.frm;
        radio_list("<?php echo $this->item['record_type'] ?>", the_form.hot);
        radio_list("<?php echo $this->item['enable'] ?>", the_form.active);
        select_list("<?php echo $this->item['dos_module_item_cat_cat_id'] ?>", the_form.parentcat);
    </script>
    <script type="text/javascript">
        jQuery(function($) {
            $('#description').keyup(function(){var max=250;var valLen=$(this).val().length;$('.info-keyup').text( valLen+'/'+max); var val = $(this).val(); if (val.length > 250){ $(this).val(val.slice(0, 250));}});
            $('#title').seoAlias({target:'#tag'});
        });
    </script>
</div>