<?php if($this->list_cats):?>
	<?php foreach($this->list_cats as $value):?>
	<h1 class="title-box-right"><span><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>materials/index/cat/cid/<?php echo $value['cat_id']?>/<?php echo $this->noneUnicode($value['cat_title'.LANG])?>" title=""><?php echo $value['cat_title'.LANG]?></a></span></h1>
	<div class="mid-boxright">
		<?php if($first = $this->cat->getItemFirstByCat($value['cat_id'])):?>
		<div class="tent-new">
			<h2 class="title-h2"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>materials/index/view/id/<?php echo $first['record_id'] ?>/<?php echo $this->noneUnicode($first['title'.LANG]) ?>" title="<?php echo $first['title'.LANG] ?>"><?php echo $first['title'.LANG] ?></a></h2>
			<?php if($first['pic_thumb']): ?><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>materials/index/view/id/<?php echo $first['record_id'] ?>/<?php echo $this->noneUnicode($first['title'.LANG]) ?>" title="<?php echo $first['title'.LANG] ?>"><img src="<?php echo $this->baseUrl() ?>/public/userfiles/images/materials/<?php echo $first['pic_thumb'] ?>" alt="<?php echo $first['title'.LANG] ?>" style="float:left" /></a><?php endif; ?>
			<?php echo html_entity_decode($first['preview'.LANG]) ?>
		</div><!--End tent new-->
        <?php else: ?>
            <?php echo $this->lang['no_record'] ?>
		<?php endif;?>

		<?php if($items = $this->cat->listItemByCat($value['cat_id'])):?>
		<ul class="sub-new">
			<?php foreach($items as $item): ?>
				<li<?php echo ($item['pic_thumb']) ? ' style="list-style:none"' : '' ?>>
					<?php if($item['pic_thumb']):?>
						<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>materials/index/view/id/<?php echo $item['record_id'] ?>/<?php echo $this->noneUnicode($item['title'.LANG]) ?>" title="<?php echo $item['title'.LANG] ?>"><img src="<?php echo $this->baseUrl() ?>/public/userfiles/images/materials/<?php echo $item['pic_thumb'] ?>" alt="<?php echo $item['title'.LANG] ?>" title="<?php echo $item['title'.LANG] ?>" style="float:left;"/></a>
					<?php endif; ?>
					<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>materials/index/view/id/<?php echo $item['record_id'] ?>/<?php echo $this->noneUnicode($item['title'.LANG]) ?>" title="<?php echo $item['title'.LANG] ?>"><?php echo $item['title'.LANG] ?></a><div class="clear"></div>
				</li>
			<?php endforeach;?>
		</ul> <!--End sub new-->
		<?php endif;?>
		<div class="clear"></div>
	</div>
	<div class="bd-bt-boxright"></div>
	<?php endforeach;?>
<?php endif;?>