<h1 class="title-right"><?php echo '<a href="'.$this->baseUrl().'/materials" title="'.$this->lang['materials'].'">'.$this->lang['materials'].'</a>';?></h1>
<?php if(is_array($this->items)):?>
	<?php foreach ($this->items as $value):?>
		<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/materials/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg'; ?>
		<div class="masuring">
			<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>materials/index/view/id/<?php echo $value['record_id'] ?>/<?php echo $this->noneUnicode($value['title'.LANG])?>" title="<?php echo $value['title'.LANG] ?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" class="imgcon" style="float:left;" alt="<?php echo $value['title'.LANG] ?>" /></a>
		    <h2 class="title-masuring"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>materials/index/view/id/<?php echo $value['record_id'] ?>/<?php echo $this->noneUnicode($value['title'.LANG])?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h2>
		 	<?php echo html_entity_decode($value['preview'.LANG]) ?>
		</div><div class="clear"></div>
	<?php endforeach;?>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
<?php else: ?>
	<?php echo $this->items?>
<?php endif;?>