<div class="content">
	<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
	<fieldset>
		<legend>Cấu hình công cụ tìm kiếm</legend>
		<p>
			<label>Google analytics</label>
			<textarea rows="10" cols="30" class="txt-textarea" name="google_analytic"><?php echo $this->item['seo_content']?></textarea>
		</p>
		<p>
			<label>&nbsp;</label>
			<input type="submit" name="submit" value="  <?php echo $this->lang['sys_edit'] ?>  " class="login" /> <a href="javascript:history.back()" class="login-a" title="<?php echo $this->lang['sys_cancel'] ?>"><?php echo $this->lang['sys_cancel'] ?></a>
		</p>
	</fieldset>
	</form>
</div>