
<div id="allproduct">
	<?php if (is_array($this->item)): ?>
		<?php foreach ($this->item as $value): ?>
			<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/product/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg';?>
			<div class="bg-product">
				<div class="bd-top-pr"></div>
				<div class="product">
					<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" alt="<?php echo $value['title'.LANG] ?>" /></a>
					<h3 class="title-h3-pr"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h3>
					<?php echo html_entity_decode($value['preview'.LANG]) ?>
					<!-- <p><s>$35.99</s></p> -->
					<div class="all-buy">
						<div class="all-pr"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/order/id/<?php echo $value['record_id'] ?>" title="Mua hàng <?php echo $value['title'.LANG] ?>">Mua hàng</a></div>
						<div class="spe-price">
							<div class="spe-left-price"></div>
							<div class="spe-right-price"><span><?php echo $value['unit'] ?></span></div>
						</div>
					</div>
				</div>
				<div class="bd-btom-pr"></div>
			</div>
		<?php endforeach;?>
		<?php //echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');?>
	<?php else: ?>
		<?php echo $this->item ?>
	<?php endif;?>
	</div><!--End All product-->
