<h3 class="marginb3"><strong>Công việc đã tạo</strong></h3>
<table>
	<thead>
		<tr>
			<th class="txt60">Mã CV</th>
			<th>Tên công việc</th>
			<th>Người thực hiện</th>
			<th>Ngày bắt đầu</th>
			<th>Ngày kết thúc</th>
			<th>Trạng thái</th>
			<th>Tiến độ thời gian</th>
		</tr>
	</thead>

	<tbody>
		<?php if($this->listjobs):?>
	  	<?php
	  		$i=0;
			foreach ($this->listjobs as $job) {
			    $i++;
				?>
			  	<tr	<?php if($i%2==0) echo 'class="alt"';?>  >
					<td><?php echo $job['job_id']?></td>
					<td><a href="<?php echo $this->baseUrl()?>/job/list/view/id/<?php echo $job['job_id']?>"><?php echo $job['job_title']?></a></td>
					<td><?php echo $job['reciever']?></td>
					<td><?php echo $job['start_date']?></td>		
					<td><?php echo $job['last_date']?></td>
					<td><?php echo $job['status']?></td>		
					<td><?php echo $job['time']?></td>	
				</tr>  
		<?php }?>
		<?php else:?>
			<tr><td colspan="6">Bạn không có việc nào yêu cầu cả</td></tr>
		<?php endif;?>
	</tbody>
</table>

<h2 class="margint10 marginb3"><strong>Công việc được giao</strong></h2>
<table>
	<thead>
		<tr>
			<th class="txt60">Mã CV</th>
			<th>Tên công việc</th>
			<th>Người giao việc</th>
			<th>Ngày bắt đầu</th>
			<th>Ngày kết thúc</th>
			<th>Trạng thái</th>
			<th>Tiến độ thời gina</th>
		</tr>

	</thead>
	<tbody>
		<?php if($this->listRecievJobs):?>
	  	<?php
	  		$i=0;
			foreach ($this->listRecievJobs as $job) {
			    $i++;
				?>
			  	<tr	<?php if($i%2==0) echo 'class="alt"';?>  >
					<td><?php echo $job['job_id']?></td>
					<td><a href="<?php echo $this->baseUrl()?>/job/list/view/id/<?php echo $job['job_id']?>"><?php echo $job['job_title']?></a></td>
					<td><?php echo $job['glt_usernames_username']?></td>
					<td><?php echo $job['start_date']?></td>		
					<td><?php echo $job['last_date']?></td>
					<td><?php echo $job['status']?></td>		
					<td><?php echo $job['time']?></td>	
				</tr>  
		<?php }?>
		<?php else:?>
			<tr><td colspan="6">Bạn không có việc nào để làm cả</td></tr>
		<?php endif;?>
	</tbody>
</table>