<div class="content">
	<?php if(count($this->error) > 0): ?>
		<ul class="error-li">
			<?php 
			foreach ($this->error as $value){
				echo '<li>'.$value.'</li>';
			}
			?>
		</ul>
	<?php endif; ?>
	
	<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
	<fieldset>
		<legend>Thêm bài viết</legend>
	    <?php
	        $lang = $this->langlist();
	        foreach($lang as $value){
	            echo '<div class="col1">'.$this->lang['sys_title'].' '.$value.'</div>
	                <div class="col2">
	                    <input name="title'.$value.'" value="'.$this->item['title'.$value].'" maxlength="45" class="txt-very-large" />
	                </div>
	                <div class="clear space"></div>';
	        }
	        foreach($lang as $value){
	            echo '<div class="col1">'.$this->lang['sys_detail'].' '.$value.'</div>
	                <div class="col2">
	                    <textarea name="detail'.$value.'" cols="70" rows="10">'.$this->item['detail'.$value].'</textarea>
	                    <script type="text/javascript">
	                    //<![CDATA[
	                    	CKEDITOR.replace( \'detail'.$value.'\' );
	                    //]]>
	                    </script>
	                </div><div class="clear space"></div>';
	        }
	    ?>
	    
	    <div class="col1"><?php echo $this->lang['sys_picture'] ?></div>
	    <div class="col2">
	        <input type="file" name="file" size="48%" />
	    </div>
	    <div class="clear space"></div>
	
	    <div class="col1"><?php echo $this->lang['job_extra1'] ?></div>
	    <div class="col2">
	        <input name="extra1" value="<?php echo $this->item['extra1'] ?>" maxlength="45" class="txt-very-large" />
	    </div>
	    <div class="clear space"></div>
	    
	    <div class="col1"><?php echo $this->lang['job_extra2'] ?></div>
	    <div class="col2">
	        <input name="extra2" value="<?php echo $this->item['extra2'] ?>" maxlength="45" class="txt-very-large" />
	    </div>
	    <div class="clear space"></div>
	    
	    <div class="col1"><?php echo $this->lang['sys_hot'] ?></div>
	    <div class="col2 radio">
	        <input type="radio" checked="checked" name="hot" id="nohot" value="0" /> <label for="nohot"><?php echo $this->lang['sys_nohot'] ?></label> &nbsp;&nbsp; <input type="radio" name="hot" id="hot" value="1" /> <label for="hot"><?php echo $this->lang['sys_hot'] ?></label>
	    </div>
	    <div class="clear space"></div>
	    
	    <div class="col1"><?php echo $this->lang['sys_active'] ?></div>
	    <div class="col2 radio">
	        <input type="radio" checked="checked" name="active" id="active" value="1" /> <label for="active"><?php echo $this->lang['sys_active'] ?></label> &nbsp;&nbsp; <input type="radio"  name="active" id="deactive" value="0" /> <label for="deactive"><?php echo $this->lang['sys_hidden'] ?></label>
	    </div>
	    <div class="clear space"></div>
	    
	    <div class="col1">&nbsp;</div>
	    <div class="col2">
	        <input type="submit" name="submit" value="  <?php echo $this->lang['sys_add'] ?>  " class="login" /> <a href="javascript:history.back()" class="login-a"><?php echo $this->lang['sys_cancel'] ?></a>
	    </div>
	    <div class="clear space"></div>
	</fieldset>
	</form>
	<script type="text/javascript">
		var the_form = window.document.frm;
		radio_list("<?php echo $this->item['hot'] ?>", the_form.hot);
		radio_list("<?php echo $this->item['active'] ?>", the_form.active);
	</script>
</div>