<div class="content">
<h3><strong>Danh sách thành viên</strong></h3>
<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
    <input type="hidden" name="factive" value="" />
	<table>
	<thead>
		<tr>
			<th class="txt15"><input onclick="javascript: select_switch(this.checked);" type="checkbox" name="checkall" /></th>
			<th class="txt60">Username</th>
			<th>Họ tên</th>
	        <th>Ngày ĐK</th>
	        <th>Người giới thiệu</th>
	        <th>Người bảo trợ</th>
	        <th>Số ĐT</th>
	        <th>Email</th>
	        <th>Số dư TK</th>
		</tr>
	</thead>
	<tbody>
	<?php
		if(is_array($this->list)){
			$k=0;
		    foreach($this->list as $value){
		        if($value['enable'] == 0){
		    		$rowclass = ' class="disable"';
		    	}else{
		        	$rowclass = ($k%2==0) ? '' : ' class="alt"';
		    	}
		 
		    	$k++;
		    		
		        echo '<tr '.$rowclass.'>
		               <td><input type="checkbox" name="ids[]" value="'.$value['username'].'" /></td>
		               <td><strong>'.$value['username'].'</strong></td>
		               <td>'.$value['full_name'].'</td>
		             
		               <td>'.substr($value['create_date'],0,10).'</td>
		               <td>'.$value['user_gioithieu'].'</td>
		               <td>'.$value['user_baotro'].'</td>
		               <td>'.$value['phone'].'</td>
		               <td>'.$value['email'].'</td>
		               <td>'.$value['balance'].'</td>
		               
		            </tr>';
		        
		    }
		}else{
			echo '<tr><td colspan="6">'.'Hiện tại bạn không có thành viên nào nào'.'</td></tr>';
		}
	    
	?>
	</tbody>
	</table>
	
	<div class="control-button"><img src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/visible.png" alt="<?php echo $this->lang['sys_active'] ?>" align="left" /> <a href="javascript:submit_list('enable', '');" title="<?php echo $this->lang['sys_active'] ?>"><?php echo $this->lang['sys_active'] ?></a></div>
	<div class="control-button"><img src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/hidden.png" alt="<?php echo $this->lang['sys_hidden'] ?>" align="left" /> <a href="javascript:submit_list('disable', '');" title="<?php echo $this->lang['sys_hidden'] ?>"><?php echo $this->lang['sys_hidden'] ?></a></div>
	<div class="control-button"><img src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/delete.png" alt="<?php echo $this->lang['sys_delete'] ?>" align="left" /> <a href="javascript:delete_list('');" title="<?php echo $this->lang['sys_delete'] ?>"><?php echo $this->lang['sys_delete'] ?></a></div>

	<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
</form>
<script type="text/javascript" src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/js/common.js"></script></div>