<?php
$strPage = '';
foreach ( $this->pagesInRange as $key ) {
	if ($this->current == $key) {
		$strPage .= '<b class="pagecureent">' . $key . '</b> ';
	} else {
		$strPage .= '<a class="pagenav" href="'.$this->url(array('page' => $key)).'">' . $key . '</a> ';
	}
}

//$page = 'Page ' . $this->current . ' Of ' . $this->last;
?>
<div class="paging">
	<?php 
		$lang = Zend_Registry::get("lang");
        if (isset($this->previous)){
            echo '<a class="pagenav" href="'.$this->url(array('page' => $this->first)).'">'.$lang['start'].'</a> ';
        }  
        
        if (isset($this->previous)){
            echo '<a class="pagenav" href="'.$this->url(array('page' => $this->previous)).'">'.$lang['previous'].'</a> ';
        }
    ?>
	<?php echo $strPage;?>
	<?php 
		if (isset($this->next)){
            echo '<a class="pageactive" href="'.$this->url(array('page' => $this->next)).'">'.$lang['next'].'</a> ';
        }
        
        if (isset($this->next)){
            echo '<a class="pagenav" href="'.$this->url(array('page' => $this->last)).'">'.$lang['end'].'</a>';
        } 
	?>
</div><div class="clear"></div>