<!--ALL Content-->
<div id="allcontent">
	<div id="leftcontent">
		<h1 class="title"><?php echo $this->item['title'.LANG]?></h1>
		<div class="infoabout">
			<?php echo html_entity_decode($this->item['content'.LANG]); ?>
		</div>
	</div>
	<!--Right content-->
		<div id="rightcontent">
			 <div id="allinfo">
				<?php if(isset($this->menu_about)): ?>
				<h3 class="tlsubmenu"><?php echo $this->lang['about'] ?></h3>
				<ul class="submenu">
					<?php 
						foreach($this->menu_about as $value){
							echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'about'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
						}
					?>
				</ul>
				<?php endif;?>
				
				<?php if(isset($this->menu_support)): ?>					  
				  <h3 class="titleh3"><?php echo $this->lang['support'] ?></h3>
					<ul id="subsupport">
						<?php foreach ($this->menu_support as $value): ?>
							<li><?php echo $value['support_name'] ?></li>
							<li><a href="ymsgr:sendim?<?php echo $value['support_value'] ?>&amp;m=<?php echo $this->lang['welcome_chat']?>" title="Chat <?php echo $value['support_value'] ?>"><img src="http://opi.yahoo.com/online?u=<?php echo $value['support_value'] ?>&amp;m=g&amp;t=2&amp;l=us" alt="<?php echo $value['support_value'] ?>" /></a></li>
						<?php endforeach;?>
					</ul>
				<?php endif;?>
				
				<?php $sc = new GLT_System_SmartCounter();?>
				<h3 class="titleh3"><?php echo $this->lang['counter']?></h3>
				<ul id="substatistics">
					<li><?php echo $this->lang['counter_today']?>: <?php echo $sc->visit_today();?></li>
					<li><?php echo $this->lang['counter_online']?>: <?php echo $sc->visit_online();?></li>
					<li><?php echo $this->lang['counter_total']?>: <?php echo $sc->visit_total();?></li>
				</ul>
				
				<?php if(isset($this->list_adv_right)):?>
				<h3 class="titleh3"><?php echo $this->lang['adv']?></h3>
				<ul id="subcustomer">
					<?php foreach ($this->list_adv_right as $value):?>
						<li><a href="<?php echo $value['url']?>" target="<?php echo $value['type']?>" title="<?php echo $value['title'.LANG].' - '.$value['description']?>"><img src="<?php echo $this->baseUrl() ?>/public/userfiles/images/adv/<?php echo $value['pic_thumb']?>" alt="<?php echo $value['title'.LANG].' - '.$value['description']?>"/></a></li>
					<?php endforeach;?>
				</ul>
				<?php endif;?>
			 </div>
		</div><!--End Right content-->
</div><!--End ALL Content-->