<h1 class="title-right"><span><?php echo $this->lang['register'.LANG]?></span></h1>
<div class="bg-pr">
	<div class="bd-top-pr"></div>
		<div class="tent-right">
				<p>Chúc mừng bạn đã đăng kí thành công.</p>
				<p>Tài khoản của bạn sẽ được kích hoạt ngay sau khi bạn hoàn tất các thủ tục thanh toán.</p>
				Nhấp <a href="<?php echo $this->baseUrl()?>"><strong>đây</strong></a> nếu trình duyệt không tự chuyển.
		</div><!--End tent right-->
	<div class="bd-bt-pr"></div>
</div><!--End bg pr-->

<script type="text/javascript">document.onload = setInterval(function (){window.location ="http://<?php echo $_SERVER["SERVER_NAME"].$this->baseUrl()?>";}, 8000);</script>