<h1 class="title-right"><span><?php echo $this->lang['handbook']?></span></h1>
<div class="bg-pr">
    <div class="bd-top-pr"></div>
		<div class="tent-right">
		
			<?php if(is_array($this->list_handbook_new)):?>
			
				<?php foreach ($this->list_handbook_new as $value):?>
					<div class="masuring">
						<?php if($value['pic_thumb']):?>
							<img src="<?php echo $this->baseUrl() ?>/public/userfiles/images/handbook/<?php echo $value['pic_thumb']?>" class="imgcon" style="float:left;" alt="<?php echo $value['title'.LANG] ?>" />
						<?php endif;?>
						<h3><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>handbook/index/view/id/<?php echo $value['record_id'].'/'.$this->noneUnicode($value['title'.LANG])?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h3>
						<?php echo strip_tags(html_entity_decode($value['preview'.LANG]), '<b><strong><p>') ?>
					</div>
				<?php endforeach;?>
				
			<?php else: ?>
				<?php echo $this->list_news_new?>
			<?php endif;?>
			
		</div><!--End tent right-->
    <div class="bd-bt-pr"></div>
</div><!--End bg pr-->
	
