<h1 class="title-box"><span><?php echo $this->item['title'.LANG] ?></span></h1>
    <div class="frame-tent-right">
	   <div class="frame-title">
            <?php echo html_entity_decode($this->item['content'.LANG]); ?>
        </div>
<p>Quý khách có thể liên hệ với chúng tôi bằng cách điền đầy đủ thông tin vào mẫu sau:</p>


 <form id="frm" name="frm" method="post"  onsubmit="return validatecheck();">
<ul class="frame-contact">
	<li><label><span>*</span> Họ và tên: </label><input name="fullname" id="fullname" type="text" /></li>
	<li><label><span>*</span> Công ty: </label><input type="text" name="company" value="" /></li>
	<li><label><span>*</span> Địa chỉ: </label><input name="address" id="address" type="text" /></li>
	<li><label><span>*</span> Điện thoại: </label><input name="phone" id="phone" type="text" /></li>
	<li><label><span>*</span> Email: </label><input name="email" id="email" type="text" /></li>
	<li><label><span>*</span> Nội dung:</label><textarea rows="10" cols="55" name="content"></textarea></li>
	<li><label>&nbsp;</label><input type="submit" value=" Gửi " class="bton-dk"/>
        <input type="reset" value="Xoá" class="bton-dk"/></li>
</ul>
</form>
<script type="text/javascript" src="<?php echo $this->baseUrl().TEMPLATE ?>/js/contact.js"></script>
</div>