<script type="text/javascript" src="<?php echo $this->baseUrl().TEMPLATE?>/js/validate-login.js"></script>
<?php if (count($this->messages)) : ?>
	<script type="text/javascript">
   		<?php $str = ''; foreach ($this->messages as $message) : ?>
   			<?php $str .= $this->escape($message).'\n'; ?>
   		<?php endforeach; ?>
   		<?php echo 'alert("'.$str.'")'; ?>
    </script>
<?php endif; ?>
	
<h2>Đăng nhập</h2>
<form method="post" id="frm-login" action="" onsubmit="return validateFormOnSubmit(this)">
	<ul>
		<li><label>Tên thành viên <span>*</span></label><input name="username" value="<?php echo $this->username?>" /></li>
		<li><label>Mật khẩu <span>*</span></label><input type="password" name="password" value="<?php echo $this->password?>" /></li>
		<li><label>&nbsp;</label><input type="image" class=submit src="<?php echo $this->baseUrl().TEMPLATE ?>/images/login.gif" onclick="return validateFormOnSubmit(this);" /></li>
	</ul>
</form>