<h1 class="title-right"><?php echo $this->lang['video']?></h1> 

<div class="frame-video">
	<?php if(is_array($this->list_items_new)): ?>
		<?php foreach ($this->list_items_new as $value):
			$pic = ($value['pic_full']) ? $this->baseUrl().'/public/userfiles/images/video/'.$value['pic_full'] : $this->baseUrl().TEMPLATE.'/images/no-images.jpg';
		?>
		
		<div class="video-photo">
	    	<div class="video-photo-img">
	    		<a href="<?php echo $value['url']?>" rel="prettyPhoto" title="<?php echo $value['title'.LANG]?>">
	    			<img src="<?php echo $pic?>" alt="<?php echo $value['title'.LANG]?>"  />
	    		</a>
	    	</div>
			<h2 class="title-video">
				<a href="<?php echo $value['url']?>" rel="prettyPhoto" title="<?php echo $value['title'.LANG]?>">
					<?php echo $value['title'.LANG]?>
				</a>
			</h2>
		</div>
		<?php endforeach;?>
		 <div class="clear"></div>
	<?php	
		echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
	?>
	<?php else: ?>
		<p><?php echo $this->list_items_new; ?></p>
	<?php endif;?>

                      
</div><!--End frame video-->
<script type="text/javascript" charset="utf-8"> 
  $(document).ready(function(){
	$(".video-photo a[rel^='prettyPhoto']").prettyPhoto();
  });
</script>                  