(function (){
  function e(a){throw a;}var f=void 0,i=!0,j=null,l=!1;function n(a){return function(b){this[a]=b}}function o(a){return function(){return this[a]}}var p,r=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function s(a){return"array"==ba(a)}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function t(a){return"string"==typeof a}function da(a){return"function"==ba(a)}function ea(a){var b=typeof a;return"object"==b&&a!=j||"function"==b}function fa(a){return a[ga]||(a[ga]=++ha)}var ga="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ha=0;
function ia(a,b,c){return a.call.apply(a.bind,arguments)}function ja(a,b,c){a||e(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ka(a,b,c){ka=Function.prototype.bind&&-1!=(""+Function.prototype.bind).indexOf("native code")?ia:ja;return ka.apply(j,arguments)}
function w(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function ma(a){var b={},c;for(c in b)var d=(""+b[c]).replace(/\$/g,"$$$$"),a=a.replace(RegExp("\\{\\$"+c+"\\}","gi"),d);return a}function x(a,b){y.prototype[a]=b}function z(a,b){function c(){}c.prototype=b.prototype;a.c=b.prototype;a.prototype=new c}
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return ka.apply(j,c)}return ka(this,a)};function na(a){if(!oa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(pa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(qa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ra,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(sa,"&quot;"));return a}var pa=/&/g,qa=/</g,ra=/>/g,sa=/\"/g,oa=/[&<>\"]/;function ta(a){return(""+a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})}function ua(a){return(""+a).replace(/([A-Z])/g,"-$1").toLowerCase()};function va(a,b){this.x=a!==f?a:0;this.y=b!==f?b:0}va.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function wa(){}wa.prototype.Na=l;wa.prototype.t=function(){this.Na||(this.Na=i,this.g())};wa.prototype.g=function(){this.nd&&xa.apply(j,this.nd)};function ya(a){a&&"function"==typeof a.t&&a.t()}function xa(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ca(d)?xa.apply(j,d):ya(d)}};var A=Array.prototype,za=A.indexOf?function(a,b,c){return A.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:0>c?Math.max(0,a.length+c):c;if(t(a))return!t(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Aa=A.forEach?function(a,b,c){A.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,h=t(a)?a.split(""):a,g=0;g<d;g++)g in h&&b.call(c,h[g],g,a)},Ba=A.filter?function(a,b,c){return A.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,h=[],g=0,k=t(a)?
a.split(""):a,m=0;m<d;m++)if(m in k){var q=k[m];b.call(c,q,m,a)&&(h[g++]=q)}return h};function Ca(a,b){var c=za(a,b);0<=c&&A.splice.call(a,c,1)}function Da(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ea(a,b,c,d){A.splice.apply(a,Fa(arguments,1))}function Fa(a,b,c){return 2>=arguments.length?A.slice.call(a,b):A.slice.call(a,b,c)};var Ga,Ha,Ia,Ja,Ka;function La(){return r.navigator?r.navigator.userAgent:j}function Ma(){return r.navigator}Ja=Ia=Ha=Ga=l;var Na;if(Na=La()){var Oa=Ma();Ga=0==Na.indexOf("Opera");Ha=!Ga&&-1!=Na.indexOf("MSIE");Ia=!Ga&&-1!=Na.indexOf("WebKit");Ja=!Ga&&!Ia&&"Gecko"==Oa.product}var Pa=Ga,B=Ha,C=Ja,D=Ia,Qa=Ma();Ka=-1!=(Qa&&Qa.platform||"").indexOf("Mac");var Ra=!!Ma()&&-1!=(Ma().appVersion||"").indexOf("X11"),Sa;
a:{var Ta="",Ua;if(Pa&&r.opera)var Va=r.opera.version,Ta="function"==typeof Va?Va():Va;else if(C?Ua=/rv\:([^\);]+)(\)|;)/:B?Ua=/MSIE\s+([^\);]+)(\)|;)/:D&&(Ua=/WebKit\/(\S+)/),Ua)var Wa=Ua.exec(La()),Ta=Wa?Wa[1]:"";if(B){var Ya,Za=r.document;Ya=Za?Za.documentMode:f;if(Ya>parseFloat(Ta)){Sa=""+Ya;break a}}Sa=Ta}var $a={};
function E(a){var b;if(!(b=$a[a])){b=0;for(var c=(""+Sa).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=(""+a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),h=Math.max(c.length,d.length),g=0;0==b&&g<h;g++){var k=c[g]||"",m=d[g]||"",q=RegExp("(\\d*)(\\D*)","g"),u=RegExp("(\\d*)(\\D*)","g");do{var Q=q.exec(k)||["","",""],v=u.exec(m)||["","",""];if(0==Q[0].length&&0==v[0].length)break;b=((0==Q[1].length?0:parseInt(Q[1],10))<(0==v[1].length?0:parseInt(v[1],10))?-1:(0==Q[1].length?0:parseInt(Q[1],
10))>(0==v[1].length?0:parseInt(v[1],10))?1:0)||((0==Q[2].length)<(0==v[2].length)?-1:(0==Q[2].length)>(0==v[2].length)?1:0)||(Q[2]<v[2]?-1:Q[2]>v[2]?1:0)}while(0==b)}b=$a[a]=0<=b}return b}var ab={};function F(a){return ab[a]||(ab[a]=B&&!!document.documentMode&&document.documentMode>=a)};var bb=!B||F(9),cb=!B||F(9),db=B&&!E("8");!D||E("528");C&&E("1.9b")||B&&E("8")||Pa&&E("9.5")||D&&E("528");C&&!E("8")||B&&E("9");function G(a,b){this.type=a;this.currentTarget=this.target=b}z(G,wa);p=G.prototype;p.g=function(){delete this.type;delete this.target;delete this.currentTarget};p.fa=l;p.defaultPrevented=l;p.jb=i;p.stopPropagation=function(){this.fa=i};p.preventDefault=function(){this.defaultPrevented=i;this.jb=l};function eb(a){a.preventDefault()};function fb(a){fb[" "](a);return a}fb[" "]=aa;function H(a,b){a&&this.S(a,b)}z(H,G);var gb=[1,4,2];p=H.prototype;p.target=j;p.relatedTarget=j;p.offsetX=0;p.offsetY=0;p.clientX=0;p.clientY=0;p.screenX=0;p.screenY=0;p.button=0;p.keyCode=0;p.charCode=0;p.ctrlKey=l;p.altKey=l;p.shiftKey=l;p.metaKey=l;p.u=j;
p.S=function(a,b){var c=this.type=a.type;G.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(C){var h;a:{try{fb(d.nodeName);h=i;break a}catch(g){}h=l}h||(d=j)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=D||a.offsetX!==f?a.offsetX:a.layerX;this.offsetY=D||a.offsetY!==f?a.offsetY:a.layerY;this.clientX=a.clientX!==f?a.clientX:a.pageX;this.clientY=a.clientY!==f?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.u=a;a.defaultPrevented&&this.preventDefault();delete this.fa};p.stopPropagation=function(){H.c.stopPropagation.call(this);this.u.stopPropagation?this.u.stopPropagation():this.u.cancelBubble=i};
p.preventDefault=function(){H.c.preventDefault.call(this);var a=this.u;if(a.preventDefault)a.preventDefault();else if(a.returnValue=l,db)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};p.g=function(){H.c.g.call(this);this.relatedTarget=this.currentTarget=this.target=this.u=j};function hb(){}var ib=0;p=hb.prototype;p.key=0;p.ga=l;p.ob=l;p.S=function(a,b,c,d,h,g){da(a)?this.Ic=i:a&&a.handleEvent&&da(a.handleEvent)?this.Ic=l:e(Error("Invalid listener argument"));this.oa=a;this.Sc=b;this.src=c;this.type=d;this.capture=!!h;this.Xa=g;this.ob=l;this.key=++ib;this.ga=l};p.handleEvent=function(a){return this.Ic?this.oa.call(this.Xa||this.src,a):this.oa.handleEvent.call(this.oa,a)};function jb(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function kb(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function lb(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function mb(a){for(var b in a)return l;return i}var nb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function ob(a,b){for(var c,d,h=1;h<arguments.length;h++){d=arguments[h];for(c in d)a[c]=d[c];for(var g=0;g<nb.length;g++)c=nb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var pb={},I={},J={},qb={};
function K(a,b,c,d,h){if(b){if(s(b)){for(var g=0;g<b.length;g++)K(a,b[g],c,d,h);return j}var d=!!d,k=I;b in k||(k[b]={k:0,z:0});k=k[b];d in k||(k[d]={k:0,z:0},k.k++);var k=k[d],m=fa(a),q;k.z++;if(k[m]){q=k[m];for(g=0;g<q.length;g++)if(k=q[g],k.oa==c&&k.Xa==h){if(k.ga)break;return q[g].key}}else q=k[m]=[],k.k++;g=rb();g.src=a;k=new hb;k.S(c,g,a,b,d,h);c=k.key;g.key=c;q.push(k);pb[c]=k;J[m]||(J[m]=[]);J[m].push(k);a.addEventListener?(a==r||!a.ec)&&a.addEventListener(b,g,d):a.attachEvent(b in qb?qb[b]:
qb[b]="on"+b,g);return c}e(Error("Invalid event type"))}function rb(){var a=sb,b=cb?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}function tb(a,b,c,d,h){if(s(b))for(var g=0;g<b.length;g++)tb(a,b[g],c,d,h);else a=K(a,b,c,d,h),pb[a].ob=i}function ub(a,b,c,d,h){if(s(b))for(var g=0;g<b.length;g++)ub(a,b[g],c,d,h);else if(d=!!d,a=vb(a,b,d))for(g=0;g<a.length;g++)if(a[g].oa==c&&a[g].capture==d&&a[g].Xa==h){L(a[g].key);break}}
function L(a){if(!pb[a])return l;var b=pb[a];if(b.ga)return l;var c=b.src,d=b.type,h=b.Sc,g=b.capture;c.removeEventListener?(c==r||!c.ec)&&c.removeEventListener(d,h,g):c.detachEvent&&c.detachEvent(d in qb?qb[d]:qb[d]="on"+d,h);c=fa(c);h=I[d][g][c];if(J[c]){var k=J[c];Ca(k,b);0==k.length&&delete J[c]}b.ga=i;h.Oc=i;wb(d,g,c,h);delete pb[a];return i}
function wb(a,b,c,d){if(!d.eb&&d.Oc){for(var h=0,g=0;h<d.length;h++)d[h].ga?d[h].Sc.src=j:(h!=g&&(d[g]=d[h]),g++);d.length=g;d.Oc=l;0==g&&(delete I[a][b][c],I[a][b].k--,0==I[a][b].k&&(delete I[a][b],I[a].k--),0==I[a].k&&delete I[a])}}function xb(a){var b,c=0,d=b==j;b=!!b;if(a==j)jb(J,function(a){for(var h=a.length-1;0<=h;h--){var g=a[h];if(d||b==g.capture)L(g.key),c++}});else if(a=fa(a),J[a])for(var a=J[a],h=a.length-1;0<=h;h--){var g=a[h];if(d||b==g.capture)L(g.key),c++}}
function vb(a,b,c){var d=I;return b in d&&(d=d[b],c in d&&(d=d[c],a=fa(a),d[a]))?d[a]:j}function yb(a,b,c,d,h){var g=1,b=fa(b);if(a[b]){a.z--;a=a[b];a.eb?a.eb++:a.eb=1;try{for(var k=a.length,m=0;m<k;m++){var q=a[m];q&&!q.ga&&(g&=zb(q,h)!==l)}}finally{a.eb--,wb(c,d,b,a)}}return Boolean(g)}function zb(a,b){var c=a.handleEvent(b);a.ob&&L(a.key);return c}
function sb(a,b){if(!pb[a])return i;var c=pb[a],d=c.type,h=I;if(!(d in h))return i;var h=h[d],g,k;if(!cb){var m;if(!(m=b))a:{m=["window","event"];for(var q=r;g=m.shift();)if(q[g]!=j)q=q[g];else{m=j;break a}m=q}g=m;m=i in h;q=l in h;if(m){if(0>g.keyCode||g.returnValue!=f)return i;a:{var u=l;if(0==g.keyCode)try{g.keyCode=-1;break a}catch(Q){u=i}if(u||g.returnValue==f)g.returnValue=i}}u=new H;u.S(g,this);g=i;try{if(m){for(var v=[],Xa=u.currentTarget;Xa;Xa=Xa.parentNode)v.push(Xa);k=h[i];k.z=k.k;for(var T=
v.length-1;!u.fa&&0<=T&&k.z;T--)u.currentTarget=v[T],g&=yb(k,v[T],d,i,u);if(q){k=h[l];k.z=k.k;for(T=0;!u.fa&&T<v.length&&k.z;T++)u.currentTarget=v[T],g&=yb(k,v[T],d,l,u)}}else g=zb(c,u)}finally{v&&(v.length=0),u.t()}return g}d=new H(b,this);try{g=zb(c,d)}finally{d.t()}return g};function M(){}z(M,wa);p=M.prototype;p.ec=i;p.ib=j;p.Nb=n("ib");p.addEventListener=function(a,b,c,d){K(this,a,b,c,d)};p.removeEventListener=function(a,b,c,d){ub(this,a,b,c,d)};
p.dispatchEvent=function(a){var b=a.type||a,c=I;if(b in c){if(t(a))a=new G(a,this);else if(a instanceof G)a.target=a.target||this;else{var d=a,a=new G(b,this);ob(a,d)}var d=1,h,c=c[b],b=i in c,g;if(b){h=[];for(g=this;g;g=g.ib)h.push(g);g=c[i];g.z=g.k;for(var k=h.length-1;!a.fa&&0<=k&&g.z;k--)a.currentTarget=h[k],d&=yb(g,h[k],a.type,i,a)&&a.jb!=l}if(l in c)if(g=c[l],g.z=g.k,b)for(k=0;!a.fa&&k<h.length&&g.z;k++)a.currentTarget=h[k],d&=yb(g,h[k],a.type,l,a)&&a.jb!=l;else for(h=this;!a.fa&&h&&g.z;h=h.ib)a.currentTarget=
h,d&=yb(g,h,a.type,l,a)&&a.jb!=l;a=Boolean(d)}else a=i;return a};p.g=function(){M.c.g.call(this);xb(this);this.ib=j};var Ab=r.window;function Bb(a,b,c){da(a)?c&&(a=ka(a,c)):a&&"function"==typeof a.handleEvent?a=ka(a.handleEvent,a):e(Error("Invalid listener argument"));return 2147483647<b?-1:Ab.setTimeout(a,b||0)};var N={},Cb=!B||F(9),Db=!C&&!B||B&&F(9)||C&&E("1.9.1"),Eb=B&&!E("9"),Fb=B||Pa||D;N.b={};N.b.set=function(a,b){a.className=b};N.b.get=function(a){a=a.className;return t(a)&&a.match(/\S+/g)||[]};N.b.add=function(a,b){var c=N.b.get(a),d=Fa(arguments,1),h=c.length+d.length;N.b.Wb(c,d);a.className=c.join(" ");return c.length==h};N.b.remove=function(a,b){var c=N.b.get(a),d=Fa(arguments,1),h=N.b.oc(c,d);a.className=h.join(" ");return h.length==c.length-d.length};N.b.Wb=function(a,b){for(var c=0;c<b.length;c++)0<=za(a,b[c])||a.push(b[c])};
N.b.oc=function(a,b){return Ba(a,function(a){return!(0<=za(b,a))})};N.b.ze=function(a,b,c){for(var d=N.b.get(a),h=l,g=0;g<d.length;g++)d[g]==b&&(Ea(d,g--,1),h=i);h&&(d.push(c),a.className=d.join(" "));return h};N.b.ge=function(a,b,c){var d=N.b.get(a);t(b)?Ca(d,b):s(b)&&(d=N.b.oc(d,b));t(c)&&!(0<=za(d,c))?d.push(c):s(c)&&N.b.Wb(d,c);a.className=d.join(" ")};N.b.Cb=function(a,b){var c=N.b.get(a);return 0<=za(c,b)};N.b.enable=function(a,b,c){c?N.b.add(a,b):N.b.remove(a,b)};
N.b.toggle=function(a,b){var c=!N.b.Cb(a,b);N.b.enable(a,b,c);return c};function O(a,b){this.width=a;this.height=b}O.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};O.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};O.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};O.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};N.gd=l;N.Sb=l;N.jd=N.gd||N.Sb;N.e=function(a){return a?new Gb(N.m(a)):N.md||(N.md=new Gb)};N.O=function(){return document};N.d=function(a){return t(a)?document.getElementById(a):a};N.dd=N.d;N.Ra=function(a,b,c){return N.yb(document,a,b,c)};N.la=function(a,b){var c=b||document;return N.pb(c)?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):N.yb(document,"*",a,b)};N.ka=function(a,b){var c=b||document,d=j;return(d=N.pb(c)?c.querySelector("."+a):N.la(a,b)[0])||j};
N.pb=function(a){return!(!a.querySelectorAll||!a.querySelector)};N.yb=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(N.pb(a)&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){for(var d={},h=0,g=0,k;k=a[g];g++)b==k.nodeName&&(d[h++]=k);d.length=h;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(g=h=0;k=a[g];g++)b=k.className,"function"==typeof b.split&&0<=za(b.split(/\s+/),c)&&(d[h++]=k);d.length=h;return d}return a};
N.ed=N.Ra;N.Ob=function(a,b){jb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in N.Tb?a.setAttribute(N.Tb[d],b):0==d.lastIndexOf("aria-",0)?a.setAttribute(d,b):a[d]=b})};N.Tb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};N.ea=function(a){return N.Bc(a||window)};
N.Bc=function(a){a=a.document;a=N.xa(a)?a.documentElement:a.body;return new O(a.clientWidth,a.clientHeight)};N.ud=function(){return N.pc(window)};N.pc=function(a){var b=a.document,c=0;if(b){var a=N.Bc(a).height,c=b.body,d=b.documentElement;if(N.xa(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{var b=d.scrollHeight,h=d.offsetHeight;d.clientHeight!=h&&(b=c.scrollHeight,h=c.offsetHeight);c=b>a?b>h?b:h:b<h?b:h}}return c};N.pe=function(a){return N.e((a||r||window).document).ca()};
N.ca=function(){return N.qc(document)};N.qc=function(a){var b=N.xb(a),a=N.Wa(a);return new va(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};N.vd=function(){return N.xb(document)};N.xb=function(a){return!D&&N.xa(a)?a.documentElement:a.body};N.P=function(a){return a?N.Wa(a):window};N.Wa=function(a){return a.parentWindow||a.defaultView};N.f=function(a,b,c){return N.cc(document,arguments)};
N.cc=function(a,b){var c=b[0],d=b[1];if(!Cb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',na(d.name),'"');if(d.type){c.push(' type="',na(d.type),'"');var h={};ob(h,d);d=h;delete d.type}c.push(">");c=c.join("")}c=a.createElement(c);d&&(t(d)?c.className=d:s(d)?N.b.add.apply(j,[c].concat(d)):N.Ob(c,d));2<b.length&&N.Xb(a,c,b,2);return c};N.Xb=function(a,b,c,d){function h(c){c&&b.appendChild(t(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];ca(g)&&!N.Eb(g)?Aa(N.Hd(g)?Da(g):g,h):h(g)}};
N.fd=N.f;N.createElement=function(a){return document.createElement(a)};N.createTextNode=function(a){return document.createTextNode(a)};N.ld=function(a,b,c){return N.dc(document,a,b,!!c)};N.dc=function(a,b,c,d){for(var h=["<tr>"],g=0;g<c;g++)h.push(d?"<td>&nbsp;</td>":"<td></td>");h.push("</tr>");h=h.join("");c=["<table>"];for(g=0;g<b;g++)c.push(h);c.push("</table>");a=a.createElement("DIV");a.innerHTML=c.join("");return a.removeChild(a.firstChild)};N.Ed=function(a){return N.Ec(document,a)};
N.Ec=function(a,b){var c=a.createElement("div");B?(c.innerHTML="<br>"+b,c.removeChild(c.firstChild)):c.innerHTML=b;if(1==c.childNodes.length)return c.removeChild(c.firstChild);for(var d=a.createDocumentFragment();c.firstChild;)d.appendChild(c.firstChild);return d};N.td=function(){return N.$a()?"CSS1Compat":"BackCompat"};N.$a=function(){return N.xa(document)};N.xa=function(a){return N.jd?N.Sb:"CSS1Compat"==a.compatMode};N.canHaveChildren=function(a){if(1!=a.nodeType)return l;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "STYLE":return l}return i};
N.appendChild=function(a,b){a.appendChild(b)};N.append=function(a,b){N.Xb(N.m(a),a,arguments,1)};N.Ca=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};N.Za=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};N.Db=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};N.te=function(a,b,c){a.insertBefore(b,a.childNodes[c]||j)};N.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):j};N.Tc=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};
N.lc=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(l);for(;b=a.firstChild;)c.insertBefore(b,a);return N.removeNode(a)}};N.me=function(a){return Db&&a.children!=f?a.children:Ba(a.childNodes,function(a){return 1==a.nodeType})};N.zb=function(a){return a.firstElementChild!=f?a.firstElementChild:N.Ta(a.firstChild,i)};N.tc=function(a){return a.lastElementChild!=f?a.lastElementChild:N.Ta(a.lastChild,l)};
N.uc=function(a){return a.nextElementSibling!=f?a.nextElementSibling:N.Ta(a.nextSibling,i)};N.yc=function(a){return a.previousElementSibling!=f?a.previousElementSibling:N.Ta(a.previousSibling,l)};N.Ta=function(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a};N.vc=function(a){if(!a)return j;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:j};
N.zc=function(a){if(!a)return j;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};N.Eb=function(a){return ea(a)&&0<a.nodeType};N.Gd=function(a){return ea(a)&&1==a.nodeType};N.ve=function(a){return ea(a)&&a.window==a};N.qe=function(a){if(Fb)return a.parentElement;a=a.parentNode;return N.Gd(a)?a:j};
N.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
N.he=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var h=a.parentNode,g=b.parentNode;return h==g?N.ac(a,b):!c&&N.contains(h,b)?-1*N.$b(a,b):!d&&N.contains(g,a)?N.$b(b,a):(c?a.sourceIndex:h.sourceIndex)-(d?b.sourceIndex:g.sourceIndex)}d=N.m(a);c=d.createRange();c.selectNode(a);c.collapse(i);d=d.createRange();
d.selectNode(b);d.collapse(i);return c.compareBoundaryPoints(r.Range.START_TO_END,d)};N.$b=function(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return N.ac(d,a)};N.ac=function(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1};
N.je=function(a){var b,c=arguments.length;if(c){if(1==c)return arguments[0]}else return j;var d=[],h=Infinity;for(b=0;b<c;b++){for(var g=[],k=arguments[b];k;)g.unshift(k),k=k.parentNode;d.push(g);h=Math.min(h,g.length)}g=j;for(b=0;b<h;b++){for(var k=d[0][b],m=1;m<c;m++)if(k!=d[m][b])return g;g=k}return g};N.m=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};N.Sa=function(a){return a.contentDocument||a.contentWindow.document};N.rc=function(a){return a.contentWindow||N.Wa(N.Sa(a))};
N.Xc=function(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{N.Ca(a);var c=N.m(a);a.appendChild(c.createTextNode(b))}};N.oe=function(a){if("outerHTML"in a)return a.outerHTML;var b=N.m(a).createElement("div");b.appendChild(a.cloneNode(i));return b.innerHTML};N.ic=function(a,b){var c=[];return N.tb(a,b,c,i)?c[0]:f};N.jc=function(a,b){var c=[];N.tb(a,b,c,l);return c};
N.tb=function(a,b,c,d){if(a!=j)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||N.tb(a,b,c,d))return i;a=a.nextSibling}return l};N.Ub={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1};N.Ja={IMG:" ",BR:"\n"};N.ue=function(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?(a=a.tabIndex,"number"==typeof a&&0<=a&&32768>a):l};N.Vc=function(a){a.tabIndex=0};
N.Ua=function(a){if(Eb&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];N.Bb(a,b,i);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Eb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a};N.re=function(a){var b=[];N.Bb(a,b,l);return b.join("")};
N.Bb=function(a,b,c){if(!(a.nodeName in N.Ub))if(3==a.nodeType)c?b.push((""+a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in N.Ja)b.push(N.Ja[a.nodeName]);else for(a=a.firstChild;a;)N.Bb(a,b,c),a=a.nextSibling};N.wc=function(a){return N.Ua(a).length};N.xc=function(a,b){for(var c=b||N.m(a).body,d=[];a&&a!=c;){for(var h=a;h=h.previousSibling;)d.unshift(N.Ua(h));a=a.parentNode}return d.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
N.ne=function(a,b,c){for(var a=[a],d=0,h;0<a.length&&d<b;)if(h=a.pop(),!(h.nodeName in N.Ub))if(3==h.nodeType)var g=h.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," "),d=d+g.length;else if(h.nodeName in N.Ja)d+=N.Ja[h.nodeName].length;else for(g=h.childNodes.length-1;0<=g;g--)a.push(h.childNodes[g]);ea(c)&&(c.xe=h?h.nodeValue.length+b-d-1:0,c.we=h);return h};
N.Hd=function(a){if(a&&"number"==typeof a.length){if(ea(a))return"function"==typeof a.item||"string"==typeof a.item;if(da(a))return"function"==typeof a.item}return l};N.wb=function(a,b,c){if(!b&&!c)return j;var d=b?b.toUpperCase():j;return N.vb(a,function(a){return(!d||a.nodeName==d)&&(!c||N.b.Cb(a,c))},i)};N.nc=function(a,b){return N.wb(a,j,b)};N.vb=function(a,b,c,d){c||(a=a.parentNode);for(var c=d==j,h=0;a&&(c||h<=d);){if(b(a))return a;a=a.parentNode;h++}return j};
N.le=function(a){try{return a&&a.activeElement}catch(b){}return j};function Gb(a){this.j=a||r.document||document}p=Gb.prototype;p.e=N.e;p.O=o("j");p.d=function(a){return t(a)?this.j.getElementById(a):a};p.dd=Gb.prototype.d;p.Ra=function(a,b,c){return N.yb(this.j,a,b,c)};p.la=function(a,b){return N.la(a,b||this.j)};p.ka=function(a,b){return N.ka(a,b||this.j)};p.ed=Gb.prototype.Ra;p.Ob=N.Ob;p.ea=function(a){return N.ea(a||this.P())};p.ud=function(){return N.pc(this.P())};
p.f=function(a,b,c){return N.cc(this.j,arguments)};p.fd=Gb.prototype.f;p.createElement=function(a){return this.j.createElement(a)};p.createTextNode=function(a){return this.j.createTextNode(a)};p.ld=function(a,b,c){return N.dc(this.j,a,b,!!c)};p.Ed=function(a){return N.Ec(this.j,a)};p.td=function(){return this.$a()?"CSS1Compat":"BackCompat"};p.$a=function(){return N.xa(this.j)};p.P=function(){return N.Wa(this.j)};p.vd=function(){return N.xb(this.j)};p.ca=function(){return N.qc(this.j)};
p.appendChild=N.appendChild;p.append=N.append;p.Ca=N.Ca;p.Za=N.Za;p.Db=N.Db;p.removeNode=N.removeNode;p.Tc=N.Tc;p.lc=N.lc;p.zb=N.zb;p.tc=N.tc;p.uc=N.uc;p.yc=N.yc;p.vc=N.vc;p.zc=N.zc;p.Eb=N.Eb;p.contains=N.contains;p.m=N.m;p.Sa=N.Sa;p.rc=N.rc;p.Xc=N.Xc;p.ic=N.ic;p.jc=N.jc;p.Ua=N.Ua;p.wc=N.wc;p.xc=N.xc;p.wb=N.wb;p.nc=N.nc;p.vb=N.vb;N.dataset={};N.dataset.set=function(a,b,c){a.dataset?a.dataset[b]=c:a.setAttribute("data-"+ua(b),c)};N.dataset.get=function(a,b){return a.dataset?a.dataset[b]:a.getAttribute("data-"+ua(b))};N.dataset.remove=function(a,b){a.dataset?delete a.dataset[b]:a.removeAttribute("data-"+ua(b))};N.dataset.Cb=function(a,b){return a.dataset?b in a.dataset:a.hasAttribute?a.hasAttribute("data-"+ua(b)):!!a.getAttribute("data-"+ua(b))};N.B={};N.B.hd='javascript:""';N.B.kd="border:0;vertical-align:bottom;";N.B.sb=function(a,b){return a.f("iframe",{frameborder:0,style:N.B.kd+(b||""),src:N.B.hd})};N.B.fe=function(a,b){var c=N.Sa(a);c.open();c.write(b);c.close()};N.B.ie=function(a,b,c,d,h){var g=N.e(a),k=[];h||k.push("<!DOCTYPE html>");k.push("<html><head>",b,"</head><body>",c,"</body></html>");b=N.B.sb(g,d);a.appendChild(b);N.B.fe(b,k.join(""));return b};function Hb(a,b,c,d,h){if(!B&&(!D||!E("525")))return i;if(Ka&&h)return Ib(a);if(h&&!d||!c&&(17==b||18==b)||B&&d&&b==a)return l;switch(a){case 13:return!(B&&F(9));case 27:return!D}return Ib(a)}function Ib(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||D&&0==a)return i;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return i;default:return l}}
function Jb(a){switch(a){case 61:return 187;case 59:return 186;case 224:return 91;case 0:return 224;default:return a}};function Kb(a,b){a&&(this.bb&&this.detach(),this.a=a,this.ab=K(this.a,"keypress",this,b),this.Gb=K(this.a,"keydown",this.yd,b,this),this.bb=K(this.a,"keyup",this.Ad,b,this))}z(Kb,M);p=Kb.prototype;p.a=j;p.ab=j;p.Gb=j;p.bb=j;p.X=-1;p.W=-1;
var Lb={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Mb={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Nb=B||D&&E("525");p=Kb.prototype;
p.yd=function(a){if(D&&(17==this.X&&!a.ctrlKey||18==this.X&&!a.altKey))this.W=this.X=-1;Nb&&!Hb(a.keyCode,this.X,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):this.W=C?Jb(a.keyCode):a.keyCode};p.Ad=function(){this.W=this.X=-1};
p.handleEvent=function(a){var b=a.u,c,d;B&&"keypress"==a.type?(c=this.W,d=13!=c&&27!=c?b.keyCode:0):D&&"keypress"==a.type?(c=this.W,d=0<=b.charCode&&63232>b.charCode&&Ib(c)?b.charCode:0):Pa?(c=this.W,d=Ib(c)?b.keyCode:0):(c=b.keyCode||this.W,d=b.charCode||0,Ka&&(63==d&&224==c)&&(c=191));var h=c,g=b.keyIdentifier;c?63232<=c&&c in Lb?h=Lb[c]:25==c&&a.shiftKey&&(h=9):g&&g in Mb&&(h=Mb[g]);a=h==this.X;this.X=h;b=new Ob(h,d,a,b);try{this.dispatchEvent(b)}finally{b.t()}};p.d=o("a");
p.detach=function(){this.ab&&(L(this.ab),L(this.Gb),L(this.bb),this.bb=this.Gb=this.ab=j);this.a=j;this.W=this.X=-1};p.g=function(){Kb.c.g.call(this);this.detach()};function Ob(a,b,c,d){d&&this.S(d,f);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}z(Ob,H);function Pb(){this.K=Qb;this.gc=this.startTime=j}z(Pb,M);var Qb=0;Pb.prototype.Jb=function(){this.N("begin")};Pb.prototype.fb=function(){this.N("end")};Pb.prototype.N=function(a){this.dispatchEvent(a)};var Rb={},Sb=j;function Tb(a){a=fa(a);delete Rb[a];mb(Rb)&&Sb&&(Ab.clearTimeout(Sb),Sb=j)}function Ub(){Sb||(Sb=Bb(function(){Sb=j;Vb()},20))}function Vb(){var a=la();jb(Rb,function(b){Wb(b,a)});mb(Rb)||Ub()};function Xb(a,b,c,d){Pb.call(this);(!s(a)||!s(b))&&e(Error("Start and end parameters must be arrays"));a.length!=b.length&&e(Error("Start and end points must be the same length"));this.Fa=a;this.rd=b;this.duration=c;this.Vb=d;this.coords=[];this.lb=l}z(Xb,Pb);p=Xb.prototype;p.w=0;
p.play=function(a){if(a||this.K==Qb)this.w=0,this.coords=this.Fa;else if(1==this.K)return l;Tb(this);this.startTime=a=la();-1==this.K&&(this.startTime-=this.duration*this.w);this.gc=this.startTime+this.duration;this.w||this.Jb();this.N("play");-1==this.K&&this.N("resume");this.K=1;var b=fa(this);b in Rb||(Rb[b]=this);Ub();Wb(this,a);return i};p.stop=function(a){Tb(this);this.K=Qb;a&&(this.w=1);Yb(this,this.w);this.N("stop");this.fb()};p.g=function(){this.K==Qb||this.stop(l);this.N("destroy");Xb.c.g.call(this)};
function Wb(a,b){a.w=(b-a.startTime)/(a.gc-a.startTime);1<=a.w&&(a.w=1);Yb(a,a.w);1==a.w?(a.K=Qb,Tb(a),a.N("finish"),a.fb()):1==a.K&&a.Ib()}function Yb(a,b){da(a.Vb)&&(b=a.Vb(b));a.coords=Array(a.Fa.length);for(var c=0;c<a.Fa.length;c++)a.coords[c]=(a.rd[c]-a.Fa[c])*b+a.Fa[c]}p.Ib=function(){this.N("animate")};p.N=function(a){this.dispatchEvent(new Zb(a,this))};
function Zb(a,b){G.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.duration=b.duration;this.w=b.w;this.state=b.K}z(Zb,G);function $b(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}$b.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};$b.prototype.contains=function(a){return!this||!a?l:a instanceof $b?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};function P(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}P.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};P.prototype.contains=function(a){return a instanceof P?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};function ac(a,b,c){t(b)?bc(a,c,b):jb(b,w(bc,a))}function bc(a,b,c){a.style[ta(c)]=b}function cc(a,b){var c=N.m(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,j))?c[b]||c.getPropertyValue(b):""}function dc(a,b){return cc(a,b)||(a.currentStyle?a.currentStyle[b]:j)||a.style&&a.style[b]}function ec(a){return dc(a,"position")}function fc(a,b,c){var d,h=C&&(Ka||Ra)&&E("1.9");b instanceof va?(d=b.x,b=b.y):(d=b,b=c);a.style.left=gc(d,h);a.style.top=gc(b,h)}
function hc(a){var b=a.getBoundingClientRect();B&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function ic(a){if(B&&!F(8))return a.offsetParent;for(var b=N.m(a),c=dc(a,"position"),d="fixed"==c||"absolute"==c,a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=dc(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return j}
function jc(a){var b,c=N.m(a),d=dc(a,"position"),h=C&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),g=new va(0,0),k;b=c?9==c.nodeType?c:N.m(c):N.O();k=B&&!F(9)&&!N.e(b).$a()?b.body:b.documentElement;if(a==k)return g;if(a.getBoundingClientRect)b=hc(a),a=N.e(c).ca(),g.x=b.left+a.x,g.y=b.top+a.y;else if(c.getBoxObjectFor&&!h)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(k),g.x=b.screenX-a.screenX,g.y=b.screenY-a.screenY;else{b=a;do{g.x+=
b.offsetLeft;g.y+=b.offsetTop;b!=a&&(g.x+=b.clientLeft||0,g.y+=b.clientTop||0);if(D&&"fixed"==ec(b)){g.x+=c.body.scrollLeft;g.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Pa||D&&"absolute"==d)g.y-=c.body.offsetTop;for(b=a;(b=ic(b))&&b!=c.body&&b!=k;)if(g.x-=b.scrollLeft,!Pa||"TR"!=b.tagName)g.y-=b.scrollTop}return g}function R(a,b,c){b instanceof O?(c=b.height,b=b.width):c==f&&e(Error("missing height argument"));a.style.width=gc(b,i);a.style.height=gc(c,i)}
function gc(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}function S(a){if("none"!=dc(a,"display"))return kc(a);var b=a.style,c=b.display,d=b.visibility,h=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=kc(a);b.display=c;b.position=h;b.visibility=d;return a}function kc(a){var b=a.offsetWidth,c=a.offsetHeight,d=D&&!b&&!c;return(b===f||d)&&a.getBoundingClientRect?(a=hc(a),new O(a.right-a.left,a.bottom-a.top)):new O(b,c)}
function lc(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*b+")")}function U(a,b){a.style.display=b?"":"none"}var mc={thin:2,medium:4,thick:6};
function nc(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:j))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:j,d;if(c in mc)d=mc[c];else if(/^\d+px?$/.test(c))d=parseInt(c,10);else{d=a.style.left;var h=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=h;d=c}return d}
function oc(a){if(B){var b=nc(a,"borderLeft"),c=nc(a,"borderRight"),d=nc(a,"borderTop"),a=nc(a,"borderBottom");return new $b(d,c,a,b)}b=cc(a,"borderLeftWidth");c=cc(a,"borderRightWidth");d=cc(a,"borderTopWidth");a=cc(a,"borderBottomWidth");return new $b(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))};function V(a,b,c,d,h){Xb.call(this,b,c,d,h);this.element=a}z(V,Xb);V.prototype.Ia=aa;V.prototype.Ib=function(){this.Ia();V.c.Ib.call(this)};V.prototype.fb=function(){this.Ia();V.c.fb.call(this)};V.prototype.Jb=function(){this.Ia();V.c.Jb.call(this)};function pc(a,b,c,d,h){"number"==typeof b&&(b=[b]);"number"==typeof c&&(c=[c]);V.call(this,a,b,c,d,h);(1!=b.length||1!=c.length)&&e(Error("Start and end points must be 1D"))}z(pc,V);pc.prototype.Ia=function(){lc(this.element,this.coords[0])};
function qc(a,b,c){pc.call(this,a,1,0,b,c)}z(qc,pc);function rc(a,b,c){pc.call(this,a,0,1,b,c)}z(rc,pc);function sc(a){return 1-Math.pow(1-a,3)};function tc(a){this.Q=a;this.h=[]}z(tc,wa);var uc=[];function W(a,b,c,d,h){s(c)||(uc[0]=c,c=uc);for(var g=0;g<c.length;g++)a.h.push(K(b,c[g],d||a,h||l,a.Q||a));return a}function vc(a,b,c,d,h,g){if(s(c))for(var k=0;k<c.length;k++)vc(a,b,c[k],d,h,g);else{a:{d=d||a;g=g||a.Q||a;h=!!h;if(b=vb(b,c,h))for(c=0;c<b.length;c++)if(!b[c].ga&&b[c].oa==d&&b[c].capture==h&&b[c].Xa==g){b=b[c];break a}b=j}b&&(b=b.key,L(b),Ca(a.h,b))}}function wc(a){Aa(a.h,L);a.h.length=0}
tc.prototype.g=function(){tc.c.g.call(this);wc(this)};tc.prototype.handleEvent=function(){e(Error("EventHandler.handleEvent not implemented"))};function xc(a){this.na={};this.Q=new tc(this);this.T=a}z(xc,M);function yc(a,b,c){(c=t(c)?c:c.src)&&(a.na[b]=c)}xc.prototype.start=function(){jb(this.na,this.Kd,this)};xc.prototype.Kd=function(a,b){if(!this.Na){var c;c=this.T?N.e(this.T).f("img"):new Image;W(this.Q,c,[B?"readystatechange":"load","abort","error"],this.Nd);c.id=b;c.src=a}};
xc.prototype.Nd=function(a){var b=a.currentTarget;if(b){if("readystatechange"==a.type)if("complete"==b.readyState)a.type="load";else return;"undefined"==typeof b.naturalWidth&&("load"==a.type?(b.naturalWidth=b.width,b.naturalHeight=b.height):(b.naturalWidth=0,b.naturalHeight=0));this.dispatchEvent({type:a.type,target:b});this.Na||(a=this.na,b=b.id,b in a&&delete a[b],mb(this.na)&&(this.dispatchEvent("complete"),this.Q&&wc(this.Q)))}};
xc.prototype.g=function(){this.na&&delete this.na;this.Q&&(this.Q.t(),this.Q=j);xc.c.g.call(this)};N.r={};N.r.Wc=function(a){a.setAttribute("role","dialog");a.Qd="dialog"};N.r.se=function(a){return a.Qd||""};N.r.Pb=function(a,b,c){a.setAttribute("aria-"+b,c)};N.r.wd=function(a){a=a.getAttribute("aria-activedescendant");return a===i||a===l?a?"true":"false":a?""+a:""};N.r.ke=function(a){var b=N.r.wd(a);return N.m(a).getElementById(b)};N.r.ye=function(a,b){N.r.Pb(a,"activedescendant",b?b.id:"")};function zc(a,b,c){this.target=a;this.handle=b||a;this.Hb=c||new P(NaN,NaN,NaN,NaN);this.j=N.m(a);this.G=new tc(this);K(this.handle,["touchstart","mousedown"],this.$c,l,this)}z(zc,M);var Ac=B||C&&E("1.9.3");p=zc.prototype;p.clientX=0;p.clientY=0;p.screenX=0;p.screenY=0;p.ad=0;p.bd=0;p.ha=0;p.ia=0;p.fc=i;p.V=l;p.Fc=0;p.Fd=l;p.lb=l;p.da=o("G");p.g=function(){zc.c.g.call(this);ub(this.handle,["touchstart","mousedown"],this.$c,l,this);this.G.t();delete this.target;delete this.handle;delete this.G};
function Bc(a){a.kb===f&&(a.kb="rtl"==dc(a.target,"direction"));return a.kb}
p.$c=function(a){var b="mousedown"==a.type;if(this.fc&&!this.V&&(!b||(bb?0==a.u.button:"click"==a.type||a.u.button&gb[0])&&(!D||!Ka||!a.ctrlKey))){Cc(a);if(0==this.Fc)if(Dc(this,a),this.V)a.preventDefault();else return;else a.preventDefault();var b=this.j,c=b.documentElement,d=!Ac;W(this.G,b,["touchmove","mousemove"],this.Bd,d);W(this.G,b,["touchend","mouseup"],this.Oa,d);Ac?(c.setCapture(l),W(this.G,c,"losecapture",this.Oa)):W(this.G,N.P(b),"blur",this.Oa);B&&this.Fd&&W(this.G,b,"dragstart",eb);
this.Rd&&W(this.G,this.Rd,"scroll",this.Od,d);this.clientX=this.ad=a.clientX;this.clientY=this.bd=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;this.lb?(a=this.target,b=a.offsetLeft,c=a.offsetParent,!c&&"fixed"==ec(a)&&(c=N.m(a).documentElement),c)?(C?(d=oc(c),b+=d.left):F(8)&&(d=oc(c),b-=d.left),a="rtl"==dc(c,"direction")?c.clientWidth-(b+a.offsetWidth):b):a=b:a=this.target.offsetLeft;this.ha=a;this.ia=this.target.offsetTop;this.Kb=N.e(this.j).ca();la()}else this.dispatchEvent("earlycancel")};
function Dc(a,b){a.dispatchEvent(new Ec("start",a,b.clientX,b.clientY))!==l&&(a.V=i)}p.Oa=function(a){wc(this.G);Ac&&this.j.releaseCapture();var b=Fc(this,this.ha),c=Gc(this,this.ia);this.V?(Cc(a),this.V=l,this.dispatchEvent(new Ec("end",this,a.clientX,a.clientY,0,b,c))):this.dispatchEvent("earlycancel");("touchend"==a.type||"touchcancel"==a.type)&&a.preventDefault()};
function Cc(a){var b=a.type;"touchstart"==b||"touchmove"==b?a.S(a.u.targetTouches[0],a.currentTarget):("touchend"==b||"touchcancel"==b)&&a.S(a.u.changedTouches[0],a.currentTarget)}
p.Bd=function(a){if(this.fc){Cc(a);var b=(this.lb&&Bc(this)?-1:1)*(a.clientX-this.clientX),c=a.clientY-this.clientY;this.clientX=a.clientX;this.clientY=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.V){var d=this.ad-this.clientX,h=this.bd-this.clientY;if(d*d+h*h>this.Fc&&(Dc(this,a),!this.V)){this.Oa(a);return}}c=Hc(this,b,c);b=c.x;c=c.y;this.V&&this.dispatchEvent(new Ec("beforedrag",this,a.clientX,a.clientY,0,b,c))!==l&&(Ic(this,a,b,c),a.preventDefault())}};
function Hc(a,b,c){var d=N.e(a.j).ca(),b=b+(d.x-a.Kb.x),c=c+(d.y-a.Kb.y);a.Kb=d;a.ha+=b;a.ia+=c;b=Fc(a,a.ha);a=Gc(a,a.ia);return new va(b,a)}p.Od=function(a){var b=Hc(this,0,0);a.clientX=this.clientX;a.clientY=this.clientY;Ic(this,a,b.x,b.y)};function Ic(a,b,c,d){a.lb&&Bc(a)?a.target.style.right=c+"px":a.target.style.left=c+"px";a.target.style.top=d+"px";a.dispatchEvent(new Ec("drag",a,b.clientX,b.clientY,0,c,d))}
function Fc(a,b){var c=a.Hb,d=!isNaN(c.left)?c.left:j,c=!isNaN(c.width)?c.width:0;return Math.min(d!=j?d+c:Infinity,Math.max(d!=j?d:-Infinity,b))}function Gc(a,b){var c=a.Hb,d=!isNaN(c.top)?c.top:j,c=!isNaN(c.height)?c.height:0;return Math.min(d!=j?d+c:Infinity,Math.max(d!=j?d:-Infinity,b))}function Ec(a,b,c,d,h,g,k){G.call(this,a);this.clientX=c;this.clientY=d;this.left=g!==f?g:b.ha;this.top=k!==f?k:b.ia}z(Ec,G);function Jc(a){if("function"==typeof a.Va)return a.Va();if(t(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return kb(a)}function Kc(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ca(a)||t(a))Aa(a,b,c);else{var d;if("function"==typeof a.Ab)d=a.Ab();else if("function"!=typeof a.Va)if(ca(a)||t(a)){d=[];for(var h=a.length,g=0;g<h;g++)d.push(g)}else d=lb(a);else d=f;for(var h=Jc(a),g=h.length,k=0;k<g;k++)b.call(c,h[k],d&&d[k],a)}};function Lc(a,b){this.Y={};this.h=[];var c=arguments.length;if(1<c){c%2&&e(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Lc?(c=a.Ab(),d=a.Va()):(c=lb(a),d=kb(a));for(var h=0;h<c.length;h++)this.set(c[h],d[h])}}p=Lc.prototype;p.k=0;p.Va=function(){Mc(this);for(var a=[],b=0;b<this.h.length;b++)a.push(this.Y[this.h[b]]);return a};p.Ab=function(){Mc(this);return this.h.concat()};
p.remove=function(a){return Object.prototype.hasOwnProperty.call(this.Y,a)?(delete this.Y[a],this.k--,this.h.length>2*this.k&&Mc(this),i):l};function Mc(a){if(a.k!=a.h.length){for(var b=0,c=0;b<a.h.length;){var d=a.h[b];Object.prototype.hasOwnProperty.call(a.Y,d)&&(a.h[c++]=d);b++}a.h.length=c}if(a.k!=a.h.length){for(var h={},c=b=0;b<a.h.length;)d=a.h[b],Object.prototype.hasOwnProperty.call(h,d)||(a.h[c++]=d,h[d]=1),b++;a.h.length=c}}
p.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.Y,a)?this.Y[a]:b};p.set=function(a,b){Object.prototype.hasOwnProperty.call(this.Y,a)||(this.k++,this.h.push(a));this.Y[a]=b};function Nc(a){this.a=a;a=B?"focusout":"blur";this.Id=K(this.a,B?"focusin":"focus",this,!B);this.Jd=K(this.a,a,this,!B)}z(Nc,M);Nc.prototype.handleEvent=function(a){var b=new H(a.u);b.type="focusin"==a.type||"focus"==a.type?"focusin":"focusout";try{this.dispatchEvent(b)}finally{b.t()}};Nc.prototype.g=function(){Nc.c.g.call(this);L(this.Id);L(this.Jd);delete this.a};function X(){}X.sc=function(){return X.Hc?X.Hc:X.Hc=new X};X.prototype.Pc=0;X.sc();function Y(a){this.$=a||N.e();this.kb=Oc}z(Y,M);Y.prototype.Gc=X.sc();var Oc=j;p=Y.prototype;p.Ya=j;p.R=l;p.a=j;p.kb=j;p.T=j;p.U=j;p.Ka=j;p.ee=l;p.d=o("a");p.la=function(a){return this.a?this.$.la(a,this.a):[]};p.ka=function(a){return this.a?this.$.ka(a,this.a):j};p.da=function(){return this.ma||(this.ma=new tc(this))};p.Nb=function(a){this.T&&this.T!=a&&e(Error("Method not supported"));Y.c.Nb.call(this,a)};p.e=o("$");p.f=function(){this.a=this.$.createElement("div")};
p.ra=function(a){this.R&&e(Error("Component already rendered"));this.a||this.f();a?a.insertBefore(this.a,j):this.$.O().body.appendChild(this.a);(!this.T||this.T.R)&&this.ja()};p.ja=function(){this.R=i;Pc(this,function(a){!a.R&&a.d()&&a.ja()})};p.ba=function(){Pc(this,function(a){a.R&&a.ba()});this.ma&&wc(this.ma);this.R=l};
p.g=function(){Y.c.g.call(this);this.R&&this.ba();this.ma&&(this.ma.t(),delete this.ma);Pc(this,function(a){a.t()});!this.ee&&this.a&&N.removeNode(this.a);this.T=this.a=this.Ka=this.U=j};function Pc(a,b){a.U&&Aa(a.U,b,f)}
p.removeChild=function(a,b){if(a){var c=t(a)?a:a.Ya||(a.Ya=":"+(a.Gc.Pc++).toString(36)),d;this.Ka&&c?(d=this.Ka,d=(c in d?d[c]:f)||j):d=j;a=d;c&&a&&(d=this.Ka,c in d&&delete d[c],Ca(this.U,a),b&&(a.ba(),a.a&&N.removeNode(a.a)),c=a,c==j&&e(Error("Unable to set parent component")),c.T=j,Y.c.Nb.call(c,j))}a||e(Error("Child is not in parent component"));return a};p.Ca=function(a){for(var b=[];this.U&&0!=this.U.length;)b.push(this.removeChild(this.U?this.U[0]||j:j,a));return b};function Qc(a,b){Y.call(this,b);this.de=!!a}z(Qc,Y);p=Qc.prototype;p.ub=j;p.Z=l;p.n=j;p.l=j;p.L=j;p.Qa=function(){return"goog-modalpopup"};p.Pa=o("n");p.f=function(){Qc.c.f.call(this);var a=this.d();N.b.add(a,this.Qa());N.Vc(a);U(a,l);this.de&&!this.l&&(this.l=N.B.sb(this.e()),this.l.className=this.Qa()+"-bg",U(this.l,l),lc(this.l,0));this.n||(this.n=this.e().f("div",this.Qa()+"-bg"),U(this.n,l));this.L||(this.L=this.e().createElement("span"),U(this.L,l),N.Vc(this.L),this.L.style.position="absolute")};
p.ja=function(){this.l&&N.Za(this.l,this.d());N.Za(this.n,this.d());Qc.c.ja.call(this);N.Db(this.L,this.d());this.ub=new Nc(this.e().O());W(this.da(),this.ub,"focusin",this.Md)};p.ba=function(){this.Z&&this.J(l);ya(this.ub);Qc.c.ba.call(this);N.removeNode(this.l);N.removeNode(this.n);N.removeNode(this.L)};p.J=function(a){a!=this.Z&&(this.qa&&this.qa.stop(),this.ua&&this.ua.stop(),this.pa&&this.pa.stop(),this.ta&&this.ta.stop(),a?this.ce():this.Dd())};
p.ce=function(){this.dispatchEvent("beforeshow")&&(this.Lb(),this.sa(),W(this.da(),this.e().P(),"resize",this.Lb),Rc(this,i),this.focus(),this.Z=i,this.qa&&this.ua?(tb(this.qa,"end",this.hb,l,this),this.ua.play(),this.qa.play()):this.hb())};p.Dd=function(){this.dispatchEvent("beforehide")&&(vc(this.da(),this.e().P(),"resize",this.Lb),this.Z=l,this.pa&&this.ta?(tb(this.pa,"end",this.gb,l,this),this.ta.play(),this.pa.play()):this.gb())};
function Rc(a,b){a.l&&U(a.l,b);a.n&&U(a.n,b);U(a.d(),b);U(a.L,b)}p.hb=function(){this.dispatchEvent("show")};p.gb=function(){Rc(this,l);this.dispatchEvent("hide")};p.focus=function(){this.mc()};
p.Lb=function(){this.l&&U(this.l,l);this.n&&U(this.n,l);var a=this.e().O(),b=N.ea(N.P(a)||window),c=Math.max(b.width,Math.max(a.body.scrollWidth,a.documentElement.scrollWidth)),a=Math.max(b.height,Math.max(a.body.scrollHeight,a.documentElement.scrollHeight));this.l&&(U(this.l,i),R(this.l,c,a));this.n&&(U(this.n,i),R(this.n,c,a))};
p.sa=function(){var a=this.e().O(),b=N.P(a)||window;if("fixed"==ec(this.d()))var c=a=0;else c=this.e().ca(),a=c.x,c=c.y;var d=S(this.d()),b=N.ea(b),a=Math.max(a+b.width/2-d.width/2,0),c=Math.max(c+b.height/2-d.height/2,0);fc(this.d(),a,c);fc(this.L,a,c)};p.Md=function(a){a.target==this.L&&Bb(this.mc,0,this)};p.mc=function(){try{B&&this.e().O().body.focus(),this.d().focus()}catch(a){}};p.g=function(){ya(this.qa);this.qa=j;ya(this.pa);this.pa=j;ya(this.ua);this.ua=j;ya(this.ta);this.ta=j;Qc.c.g.call(this)};function Z(a,b,c){Qc.call(this,b,c);this.D=a||"modal-dialog";this.s=Sc()}z(Z,Qc);p=Z.prototype;p.hc=i;p.Cc=i;p.Jc=i;p.qd=i;p.nb=0.5;p.Rb="";p.bc="";p.aa=j;p.pd=l;p.M=j;p.Ha=j;p.cd=j;p.Ga=j;p.va=j;p.i=j;p.Qa=o("D");p.Ac=o("Rb");p.Pa=function(){this.d()||this.ra();return Z.c.Pa.call(this)};function Tc(a,b){a.nb=b;if(a.d()){var c=a.Pa();c&&lc(c,a.nb)}}
function Uc(a,b){a.d()&&N.b.enable(a.M,a.D+"-title-draggable",b);b&&!a.aa?(a.aa=new zc(a.d(),a.M),N.b.add(a.M,a.D+"-title-draggable"),K(a.aa,"start",a.Ud,l,a)):!b&&a.aa&&(a.aa.t(),a.aa=j)}
p.f=function(){Z.c.f.call(this);var a=this.d(),b=this.e();this.M=b.f("div",{className:this.D+"-title",id:this.Ya||(this.Ya=":"+(this.Gc.Pc++).toString(36))},this.Ha=b.f("span",this.D+"-title-text",this.Rb),this.Ga=b.f("span",this.D+"-title-close"));N.append(a,this.M,this.va=b.f("div",this.D+"-content"),this.i=b.f("div",this.D+"-buttons"));this.cd=this.M.id;N.r.Wc(a);N.r.Pb(a,"labelledby",this.cd||"");this.bc&&(this.va.innerHTML=this.bc);U(this.Ga,this.Cc);this.s&&(a=this.s,a.a=this.i,a.ra());U(this.i,
!!this.s);Tc(this,this.nb)};p.ja=function(){Z.c.ja.call(this);W(W(this.da(),this.d(),"keydown",this.Qc),this.d(),"keypress",this.Qc);W(this.da(),this.i,"click",this.Ld);Uc(this,this.qd);W(this.da(),this.Ga,"click",this.Pd);N.r.Wc(this.d());""!==this.Ha.id&&N.r.Pb(this.d(),"labelledby",this.Ha.id);if(!this.Jc&&(this.Jc=l,this.R)){var a=this.e(),b=this.Pa();a.removeNode(this.l);a.removeNode(b)}};p.ba=function(){this.Z&&this.J(l);Uc(this,l);Z.c.ba.call(this)};
p.J=function(a){a!=this.Z&&(this.R||this.ra(),Z.c.J.call(this,a))};p.hb=function(){Z.c.hb.call(this);this.dispatchEvent(Vc)};p.gb=function(){Z.c.gb.call(this);this.dispatchEvent(Wc);this.pd&&this.t()};
p.focus=function(){Z.c.focus.call(this);if(this.s){var a=this.s.Ma;if(a)for(var b=this.e().O(),c=this.i.getElementsByTagName("button"),d=0,h;h=c[d];d++)if(h.name==a){try{if(D||Pa){var g=b.createElement("input");g.style.cssText="position:fixed;width:0;height:0;left:0;top:0;";this.d().appendChild(g);g.focus();this.d().removeChild(g)}h.focus()}catch(k){}break}}};
p.Ud=function(){var a=this.e().O(),b=N.ea(N.P(a)||window),c=Math.max(a.body.scrollWidth,b.width),a=Math.max(a.body.scrollHeight,b.height),d=S(this.d());this.aa.Hb="fixed"==ec(this.d())?new P(0,0,Math.max(0,b.width-d.width),Math.max(0,b.height-d.height))||new P(NaN,NaN,NaN,NaN):new P(0,0,c-d.width,a-d.height)||new P(NaN,NaN,NaN,NaN)};p.Pd=function(){if(this.Cc){var a=this.s,b=a&&a.qb;b?(a=a.get(b),this.dispatchEvent(new Xc(b,a))&&this.J(l)):this.J(l)}};p.g=function(){this.i=this.Ga=j;Z.c.g.call(this)};
function Yc(a){a.s=j;if(a.i){if(a.s){var b=a.s;b.a=a.i;b.ra()}else a.i.innerHTML="";U(a.i,!!a.s)}}p.Ld=function(a){a:{for(a=a.target;a!=j&&a!=this.i;){if("BUTTON"==a.tagName)break a;a=a.parentNode}a=j}if(a&&!a.disabled){var a=a.name,b=this.s.get(a);this.dispatchEvent(new Xc(a,b))&&this.J(l)}};
p.Qc=function(a){var b=l,c=l,d=this.s,h=a.target;if("keydown"==a.type)if(this.hc&&27==a.keyCode){var g=d&&d.qb,h="SELECT"==h.tagName&&!h.disabled;g&&!h?(c=i,b=d.get(g),b=this.dispatchEvent(new Xc(g,b))):h||(b=i)}else 9==a.keyCode&&(a.shiftKey&&h==this.d())&&(c=i);else if(13==a.keyCode){if("BUTTON"==h.tagName)g=h.name;else if(d){var k=d.Ma,m;if(m=k)a:{m=d.a.getElementsByTagName("BUTTON");for(var q=0,u;u=m[q];q++)if(u.name==k||u.id==k){m=u;break a}m=j}h=("TEXTAREA"==h.tagName||"SELECT"==h.tagName)&&
!h.disabled;m&&(!m.disabled&&!h)&&(g=k)}g&&d&&(c=i,b=this.dispatchEvent(new Xc(g,""+d.get(g))))}if(b||c)a.stopPropagation(),a.preventDefault();b&&this.J(l)};function Xc(a,b){this.type=Zc;this.key=a;this.caption=b}z(Xc,G);var Zc="dialogselect",Wc="afterhide",Vc="aftershow";function $c(a){this.$=a||N.e();Lc.call(this)}z($c,Lc);p=$c.prototype;p.D="goog-buttonset";p.Ma=j;p.a=j;p.qb=j;p.set=function(a,b,c,d){Lc.prototype.set.call(this,a,b);c&&(this.Ma=a);d&&(this.qb=a);return this};
function $(a,b,c,d){return a.set(b.key,b.caption,c,d)}p.ra=function(){if(this.a){this.a.innerHTML="";var a=N.e(this.a);Kc(this,function(b,c){var d=a.f("button",{name:c},b);c==this.Ma&&(d.className=this.D+"-default");this.a.appendChild(d)},this)}};p.d=o("a");p.e=o("$");
var ad=ma("OK"),bd=ma("Cancel"),cd=ma("Yes"),dd=ma("No"),ed=ma("Save"),fd=ma("Continue"),gd={key:"ok",caption:ad},hd={key:"cancel",caption:bd},id={key:"yes",caption:cd},jd={key:"no",caption:dd},kd={key:"save",caption:ed},ld={key:"continue",caption:fd};function Sc(){return $($(new $c,gd,i),hd,l,i)}"undefined"!=typeof document&&($(new $c,gd,i,i),Sc(),$($(new $c,id,i),jd,l,i),$($($(new $c,id),jd,i),hd,l,i),$($($(new $c,ld),kd),hd,i,i));var md=/Mac OS X.+Silk\//,nd=/iPhone|iPod|iPad/.test(navigator.userAgent)||-1!=navigator.userAgent.indexOf("Android")||md.test(navigator.userAgent),od=window.navigator.msPointerEnabled;
function y(a,b){Z.call(this,pd,i);this.Zb=a||qd;this.ya=pd+"-"+this.Zb;this.Rb=b||"";this.A=[];this.F=j;this.kc=i;this.C=this.a;this.Fb=this.q=this.Kc=this.Lc=this.o=this.H=this.p=this.v=j;this.I=0;this.Ba=l;this.Ea=i;this.mb=this.Uc=l;this.Nc=rd;this.Mc=sd;this.Yb=td;this.Dc=l;this.Aa=-1;this.za=l;this.cb=new xc;this.wa=this.Da=l}z(y,Z);var ud=y,vd=["gweb","ui","LightBox"],wd=r;!(vd[0]in wd)&&wd.execScript&&wd.execScript("var "+vd[0]);
for(var xd;vd.length&&(xd=vd.shift());)!vd.length&&ud!==f?wd[xd]=ud:wd=wd[xd]?wd[xd]:wd[xd]={};var pd="gweb-lightbox",yd=nd?"touchstart":od?"MSPointerDown":"click",td="\u00d7",rd="\u2039",sd="\u203a",zd=/\.(gif|jpg|jpeg|png|webp)$/i,Ad=/^#/,Bd=/\/\/(www\.)?youtube\.com/,qd="lb";p=y.prototype;p.ae=n("Ba");p.Wd=n("Ea");p.be=n("Uc");p.Sd=n("mb");p.Zd=n("Nc");p.Yd=n("Mc");p.Td=n("Yb");p.Vd=n("Dc");p.$d=function(a){this.Aa=a?1:0};p.Xd=n("za");p.od=function(){this.Ea=l;this.wa=i};
p.S=function(){var a=N.la(this.Zb);Aa(a,function(a){var c=new Cd(a),d=this.A;0<=za(d,c)||d.push(c);N.dataset.set(a,"lightboxIndex",this.A.length-1);Dd(this,a);-1==this.Aa&&c.href.match(Bd)&&(this.Aa=1)},this);Tc(this,0.8);this.hc=i;Yc(this);this.ra();1==this.Aa&&N.b.add(this.C,"gweb-lightbox-outside-nav");this.I=Math.ceil(2*oc(this.C).top);this.wa||Ed(this);K(this,"imageloaded",w(this.rb,this.p),l,this);K(this,"iframeloaded",w(this.rb,this.v),l,this);K(this,"fragmentloaded",w(this.rb,this.H),l,this);
K(this.n,yd,w(this.J,l),l,this);K(this,Wc,this.La,l,this);K(this,"navigateprev",w(this.Qb,this.Lc),l,this);K(this,"navigatenext",w(this.Qb,this.Kc),l,this);K(window,"resize",w(this.sa,this.Rc),l,this);"opacity"in window.document.body.style&&(this.Da=i)};function Dd(a,b){K(b,yd,function(a){a.preventDefault();this.Qb(b)},l,a)}
p.f=function(){y.c.f.call(this);N.appendChild(this.Ga,N.createTextNode(this.Yb));this.a.setAttribute("id",this.ya);this.i&&(this.o=N.f("div","gweb-lightbox-caption gweb-lightbox-hide"),N.appendChild(this.i,this.o));this.Ea&&1<this.A.length&&this.Ha?(this.Fb=N.f("span"),N.appendChild(this.Ha,this.Fb)):this.Ea=l;this.C=this.a;this.wa?U(this.i,i):(this.Lc=Fd(this,"gweb-lightbox-prev"),this.Kc=Fd(this,"gweb-lightbox-next"));Gd(this)};
function Gd(a){Aa(a.A,function(a){!this.p&&"IMG"==a.type?(this.p=N.f("img",{id:this.ya+"-image",src:"//www.google.com/images/cleardot.gif"}),R(this.p,200,200),N.appendChild(this.va,this.p)):!this.v&&"IFRAME"==a.type?(this.v=N.B.sb(N),this.v.id=this.ya+"-iframe",N.append(this.va,this.v)):!this.H&&"A"==a.type&&(this.H=N.f("div",{id:this.ya+"-fragment","class":pd+"-fragment"}),N.append(this.va,this.H))},a)}function Ed(a){var b=new Kb(document);K(b,"key",a.zd,l,a)}
p.zd=function(a){if(this.Z&&!this.wa)switch(a.keyCode){case 37:(this.za||0!=this.F)&&this.dispatchEvent("navigateprev");break;case 39:(this.za||this.F!=this.A.length-1)&&this.dispatchEvent("navigatenext")}};p.Mb=function(a){a?(N.b.remove(this.o,"gweb-lightbox-hide"),this.o.innerHTML=a,this.Ba&&N.b.add(this.o,"gweb-lightbox-overlay")):(this.o.innerHTML="",N.b.add(this.o,"gweb-lightbox-hide"));U(this.o,l)};p.Yc=function(){U(this.o,i);this.mb&&(new rc(this.o,200)).play()};
function Hd(a){a=N.dataset.get(a,"lightboxIndex");return parseInt(a,10)}function Fd(a,b){var c=N.f("span","","gweb-lightbox-next"==b?a.Mc:a.Nc),d=N.f("img",{src:"//www.google.com/images/cleardot.gif",alt:""}),c=N.f("a",{"class":"gweb-lightbox-nav "+b,href:"#"},[c,d]);U(c,l);N.appendChild(a.i,c);U(a.i,i);K(c,yd,function(a){a.preventDefault();"gweb-lightbox-next"==b?this.dispatchEvent("navigatenext"):this.dispatchEvent("navigateprev")},l,a);return c}
function Id(a){var b=a.A.length,c=N.ka("gweb-lightbox-prev",a.i),d=N.ka("gweb-lightbox-next",a.i),h=N.Ra("img",j,a.i);0==a.F?a.za?(U(c,i),N.dataset.set(c,"lightboxIndex",b-1)):U(c,l):(U(c,i),N.dataset.set(c,"lightboxIndex",a.F-1));a.F+1==b?a.za?(U(d,i),N.dataset.set(d,"lightboxIndex",0)):U(d,l):(U(d,i),N.dataset.set(d,"lightboxIndex",a.F+1));a.Dc&&(a.kc&&a.Da)&&(Jd(a,d,"gweb-lightbox-next"),Jd(a,c,"gweb-lightbox-prev"));var b=S(a.o).height,g=S(a.M).height+"px";ac(c,"top",g);ac(d,"top",g);var k=a.Ba?
a.q.height-b:a.q.height,m=0.35*a.q.width;Aa(h,function(a){R(a,m,k)},a);a.kc=l}function Jd(a,b,c){b=N.zb(b);b.style.visibility="visible";"gweb-lightbox-prev"==c?b.style.left="0":"gweb-lightbox-next"==c&&(b.style.right="0");Bb(w(a.sd,b),2E3,a)}p.sd=function(a){a=new qc(a,500);K(a,"end",this.Cd,l,this);a.play()};p.Cd=function(a){a=a.target.element;a.style.visibility="hidden";a.style.opacity=1;a.style.filter=""};p.Qb=function(a){this.Zc(Hd(a))};
p.Zc=function(a){if(this.A&&a<=this.A.length-1){this.F=a;a=this.A[this.F];this.Mb("");if(!this.Z){this.J(i);var b=new rc(this.C,200);this.Da||K(b,"end",w(ac,this.C,"filter",""),l,this);b.play()}this.Ea&&(this.Fb.innerHTML=this.F+1+"/"+this.A.length);this.Rc=S(this.C);switch(a.type){case "A":this.La("A");Kd(this,i,this.H);R(this.H,a.width,a.height);this.q=new O(a.width,a.height);b=a.href.split("#");1<b.length?(a=N.d(b[1]).cloneNode(i),N.append(this.H,a.childNodes),this.dispatchEvent("fragmentloaded")):
e(Error("Invalid url:"+a.href));break;case "IFRAME":Ld(this,a);break;case "IMG":Md(this,a)}}};p.La=function(a){this.v&&("IFRAME"!=a&&(this.v.src=""),U(this.v,!a||"IFRAME"==a));this.p&&("IMG"!=a&&(this.p.src="//www.google.com/images/cleardot.gif"),U(this.p,!a||"IMG"==a));this.H&&(N.Ca(this.H),U(this.H,!a||"A"==a))};function Kd(a,b,c){N.b.enable(a.C,"gweb-lightbox-loading",b);b&&a.Da&&c?lc(c,0.5):!b&&a.Da&&(new rc(c,500)).play()}
function Ld(a,b){a.La("IFRAME");Kd(a,i,a.p);tb(a.v,"load",function(){this.v.width=b.width;this.v.height=b.height;this.q=new O(b.width,b.height);this.dispatchEvent("iframeloaded")},l,a);a.v.src=b.href}
function Md(a,b){var c=N.ea(window),d=a.ya+"-image";a.La("IMG");a.cb&&(yc(a.cb,d,b.href),a.cb.start());Kd(a,i,a.p);tb(a.cb,"load",function(a){a=a.target;this.p.src=a.src;if(this.Uc){var b=(new O(this.M.offsetWidth,this.M.offsetHeight)).height,d=S(this.o).height+this.I,b=this.Ba?c.height-this.I-b:c.height-this.I-b-d,d=this.Aa==1?c.width-this.I*3:c.width-this.I;if(a.height>b||a.width>d){d=Math.min(d/a.width-0.1,b/a.height-0.05);b=Math.floor(a.width*d);a=Math.floor(a.height*d);R(this.p,b,a);this.q=new O(b,
a)}else{R(this.p,a.width,a.height);this.q=new O(a.width,a.height)}}else{R(this.p,a.width,a.height);this.q=new O(a.width,a.height)}this.dispatchEvent("imageloaded")},l,a)}p.rb=function(a){var b=this.A[this.F],c=200<this.q.width?this.q.width:200;this.C.style.width=gc(c,i);this.o.style.width=gc(c,i);this.Mb(b.title);this.sa(this.Rc);this.wa||Id(this);Kd(this,l,a)};
p.sa=function(a){if(a){var b=N.ea(window),c=N.ca(),d=S(this.M),h=S(this.o),g=[],k=200<=this.q.width?this.q.width:200,d=this.q.height+d.height;this.Ba||(d+=h.height);h=Math.floor(c.x+b.width/2-k/2)-this.I/2;b=Math.floor(c.y+b.height/2-d/2)-this.I/2;this.mb?(g=[a.width-this.I,a.height-this.I,jc(this.C).x,jc(this.C).y],a=new Nd(this.C,g,[k,d,h,b],800,sc),K(a,"end",this.Yc,l,this),a.play()):(y.c.sa.call(this),this.Yc())}else y.c.sa.call(this)};function Nd(a,b,c,d,h){V.apply(this,arguments)}z(Nd,V);
Nd.prototype.Ia=function(){R(this.element,this.coords[0],this.coords[1]);fc(this.element,this.coords[2],this.coords[3])};function Cd(a){this.type=this.xd(a);this.href=a.href||"";this.title=this.Ac(a);this.width="IMG"==this.type?0:parseInt(N.dataset.get(a,Od),10)||200;this.height="IMG"==this.type?0:parseInt(N.dataset.get(a,Pd),10)||200}var Pd="lightboxHeight",Od="lightboxWidth";Cd.prototype.xd=function(a){return a.href.match(zd)?"IMG":a.getAttribute("href",2).match(Ad)?"A":"IFRAME"};
Cd.prototype.Ac=function(a){return N.dataset.get(a,"lightboxCaption")||a.getAttribute("title")||""};x("setOverlayCaption",y.prototype.ae);x("setItemCount",y.prototype.Wd);x("setScaleImages",y.prototype.be);x("setAnimate",y.prototype.Sd);x("setNavTextPrev",y.prototype.Zd);x("setNavTextNext",y.prototype.Yd);x("setCloseText",y.prototype.Td);x("setHideNav",y.prototype.Vd);x("setOutsideNav",y.prototype.$d);x("setLoop",y.prototype.Xd);x("setCaption",y.prototype.Mb);x("disableNav",y.prototype.od);
x("showContentByIndex",y.prototype.Zc);x("init",y.prototype.S);
})()