<!--ALL Content-->
<div id="allcontent">
	<!--Left content-->
			<div id="leftcontent">
				<h1 class="title"><?php echo $this->lang['handbook']?> &raquo; <?php echo $this->detailcat['cat_title'.LANG] ?></h1>
				<?php if(is_array($this->items)):?>
						<?php foreach ($this->items as $value): ?>
						<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/handbook/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg'; ?>
						<div class="masuring">
		                	<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>handbook/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" class="imgcon" style="float:left;" alt="<?php echo $value['title'.LANG] ?>" /></a>
		                    <h3><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>handbook/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h3>
		                    <?php echo html_entity_decode($value['preview'.LANG]) ?>
		                </div>
						<?php endforeach; ?>
					<?php else:?>
						<?php echo $this->items; ?>
				<?php endif;?>
				
				<?php if(is_array($this->list_handbook_new)):?>
					<?php foreach ($this->list_handbook_new as $value):?>
						<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/handbook/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg'; ?>
						<div class="masuring">
		                	<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>handbook/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" class="imgcon" style="float:left;" alt="<?php echo $value['title'.LANG] ?>" /></a>
		                    <h3><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>handbook/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h3>
		                    <?php echo html_entity_decode($value['preview'.LANG]) ?>
		                </div>
					<?php endforeach;?>
				<?php else: ?>
					<?php echo $this->list_news_new?>
				<?php endif;?>
                <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
			</div><!--End Left content-->
	<!--Right content-->
	<div id="rightcontent">
		<div id="allinfo">
			<?php if(isset($this->menu_handbook) && is_array($this->menu_handbook)): ?>
				<h3 class="tlsubmenu"><?php echo $this->lang['handbook'] ?></h3>
				<ul class="submenu">
					<?php
						$rowsize = count($this->menu_handbook);
						$params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
						$cat_id = isset($params['cid']) ? intval($params['cid']) : 0;
						
						//For item detail
						$id = isset($params['id']) ? intval($params['id']) : 0;
						if($id){
		                    $cat_id = $this->item['dos_module_handbook_cat_cat_id'];
		                }
						
		                //Find parent_id
						$parent_id	= $cat_id;
		            	if ( $cat_id ){
		            		for ($i=0; $i < $rowsize; $i++){
		            			if ($cat_id == $this->menu_handbook[$i]['cat_id']){
		            				if ( $this->menu_handbook[$i]['cat_parent_id'] ){
		            					$parent_id = $this->menu_handbook[$i]['cat_parent_id'];
		            				}
		            				break;
		            			}
		            		}
		            	}
		            	
		            	//Display cat menu
		            	for ($i=0; $i < $rowsize; $i++){
		            		if ( $this->menu_handbook[$i]['cat_parent_id'] == 0 ){
		            			//Parent categories
		            			echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'handbook/index/cat/cid/'.$this->menu_handbook[$i]['cat_id'].'" title="'.$this->menu_handbook[$i]['cat_title'.LANG].'">'.$this->menu_handbook[$i]['cat_title'.LANG].'</a>';
			            		//Sub categories
		            			if ( $parent_id && ($parent_id == $this->menu_handbook[$i]['cat_id']) ){
		            				for ($j=0; $j < $rowsize; $j++){
		            					if ( $this->menu_handbook[$j]['cat_parent_id'] == $this->menu_handbook[$i]['cat_id'] ){
		            						echo '<ul>';
				            					for ($j=0; $j < $rowsize; $j++){
				            						if ( $this->menu_handbook[$j]['cat_parent_id'] == $this->menu_handbook[$i]['cat_id'] ){
			                                            echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'handbook/index/cat/cid/'.$this->menu_handbook[$j]['cat_id'].'" title="'.$this->menu_news[$j]['cat_title'.LANG].'">'.$this->menu_handbook[$j]['cat_title'.LANG].'</a></li>';
			                                        }
			                                    }
		                                    echo '</ul>';
		            					}
		            				}
		            			}
		            			echo '</li>';
		            		}
		            	}
					?>
				</ul>
			<?php endif;?>
			
			<?php if(isset($this->menu_about)): ?>
				<h3 class="tlsubmenu"><?php echo $this->lang['about'] ?></h3>
				<ul class="submenu">
					<?php 
						foreach($this->menu_about as $value){
							echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'about'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
						}
					?>
				</ul>
				<?php endif;?>
				
				<?php if(isset($this->menu_support)): ?>					  
				  <h3 class="titleh3"><?php echo $this->lang['support'] ?></h3>
					<ul id="subsupport">
						<?php foreach ($this->menu_support as $value): ?>
							<li><?php echo $value['support_name'] ?></li>
							<li><a href="ymsgr:sendim?<?php echo $value['support_value'] ?>&amp;m=<?php echo $this->lang['welcome_chat']?>" title="Chat <?php echo $value['support_value'] ?>"><img src="http://opi.yahoo.com/online?u=<?php echo $value['support_value'] ?>&amp;m=g&amp;t=2&amp;l=us" alt="<?php echo $value['support_value'] ?>" /></a></li>
						<?php endforeach;?>
					</ul>
				<?php endif;?>
				
				<?php $sc = new GLT_System_SmartCounter();?>
				<h3 class="titleh3"><?php echo $this->lang['counter']?></h3>
				<ul id="substatistics">
					<li><?php echo $this->lang['counter_today']?>: <?php echo $sc->visit_today();?></li>
					<li><?php echo $this->lang['counter_online']?>: <?php echo $sc->visit_online();?></li>
					<li><?php echo $this->lang['counter_total']?>: <?php echo $sc->visit_total();?></li>
				</ul>
				
				<?php if(isset($this->list_adv_right)):?>
				<h3 class="titleh3"><?php echo $this->lang['adv']?></h3>
				<ul id="subcustomer">
					<?php foreach ($this->list_adv_right as $value):?>
						<li><a href="<?php echo $value['url']?>" target="<?php echo $value['type']?>" title="<?php echo $value['title'.LANG].' - '.$value['description']?>"><img src="<?php echo $this->baseUrl() ?>/public/userfiles/images/adv/<?php echo $value['pic_thumb']?>" alt="<?php echo $value['title'.LANG].' - '.$value['description']?>"/></a></li>
					<?php endforeach;?>
				</ul>
			<?php endif;?>
		</div>
	</div><!--End Right content-->
</div><!--End Content-->