<?php
$page_current = Zend_Controller_Front::getInstance()->getRequest()->getParams();
$page_id = isset($page_current['id']) ? '/'.$page_current['id'] : '';
$strPage = '';
foreach ( $this->pagesInRange as $key ) {
	if ($this->current == $key) {
		$strPage .= '<b class="pagecureent">' . $key . '</b> ';
	} else {
		$strPage .= '<a class="pagenav" href="'.$this->baseUrl().'/'.$page_current[1].$page_id.'/page/'.$key.'">' . $key . '</a> ';
	}
}
//$page = 'Page ' . $this->current . ' Of ' . $this->last;
?>
<div class="paging">
	<?php 
		$lang = Zend_Registry::get("lang");
        if (isset($this->previous)){
            echo '<a class="pagenav" href="'.$this->baseUrl().'/'.$page_current[1].$page_id.'/page/'.$this->first.'">'.$lang['start'].'</a> ';
        }  
        
        if (isset($this->previous)){
            echo '<a class="pagenav" href="'.$this->baseUrl().'/'.$page_current[1].$page_id.'/page/'.$this->previous.'">'.$lang['previous'].'</a> ';
        }
    ?>
	<?php echo $strPage;?>
	<?php 
		if (isset($this->next)){
            echo '<a class="pageactive" href="'.$this->baseUrl().'/'.$page_current[1].$page_id.'/page/'.$this->next.'">'.$lang['next'].'</a> ';
        }
        
        if (isset($this->next)){
            echo '<a class="pagenav" href="'.$this->baseUrl().'/'.$page_current[1].$page_id.'/page/'.$this->last.'">'.$lang['end'].'</a>';
        }
	?>
</div>