<?php if ($this->listLog): ?>
	<table>
		<thead>
			<tr>
				<th>STT</th>
				<th>Thời gian</th>
				<th>Chi tiết</th>
				<th>Đối tác</th>
				<th>Tiền (V)</th>
				<th>Thành tiền VNĐ</th>
			</tr>
		</thead>
			<tbody>
			
			<?php 
				$i=0;
				foreach ($this->listLog as $value){
					$class = ($i%2==0) ? '' : ' class="alt"';
			    	$i++;
			   
			    	if($this->user == $value['username']){
						$u= $value['user_receive'];
						$sign='-';
			    	}
			    	else {
			    		$u= $value['username'];
						$sign='+';
			    	}
			?>
				<tr<?php echo $class?>>
			   		<td><?php echo $i++?></td>
			 		<td><?php echo $value['time'] ?></td>
					<td><?php echo $value['detail']?>	</td>
					<td><?php echo $u?></td>
					
					<td><?php echo $sign.$value['value'] ?> </td>
					<td><?php echo $sign.number_format($value['value']*1000,0)?></td>
								
				</tr>	
		<?php } ?>
			
		</tbody>
	</table>
	<br />
	<p style="float: right;">Sô dư Tài khoản hiện tại: <span style="font-style: italic; font: bold;"><?php echo number_format($this->tk*1000, 0)?> VNĐ</span></p>
	<br />
		<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
<?php else: ?>
	Bạn chưa có giao dịch nào.
<?php endif;?> 