<div class="aboutBox-detail">
	<div class="title"><?php echo $this->lang['news']?> &raquo; <?php echo $this->detailcat['cat_title'.LANG] ?></div>
	<?php if(is_array($this->items)):?>
	<ul class="news-list">
		<?php foreach ($this->items as $value): ?>
		<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/news/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg'; ?>
		<li>
			<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>news/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" alt="<?php echo $value['title'.LANG] ?>" /></a>
			<h2><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>news/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h2>
			<?php echo html_entity_decode($value['preview'.LANG]) ?>
		</li>
		<?php endforeach; ?>
	</ul>
	
	<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
	<?php else:?>
		<?php echo $this->items; ?>
	<?php endif;?>
</div>