<h2><?php echo $this->lang['studies']?> &raquo; <?php echo $this->item['title'.LANG] ?></h2>
<div id="presented">
	<?php echo html_entity_decode($this->item['content'.LANG]) ?>
	
	<!--Binh luan-->
	<div class="binhluan">
		<h3>chứng khoán toàn cầu thiệt hại tới 4.000 tỷ USD<span> - vietha1089</span></h3>
		<p>chào mọi người, đây là lời bình của vietha1089</p>
	</div>
	<div class="binhluan">
		<h3>chứng khoán toàn cầu thiệt hại tới 4.000 tỷ USD<span> - vietha1089</span></h3>
		<p>chào mọi người, đây là lời bình của vietha1089</p>
	</div>
	<!--End binh luan-->
	<div class="paging"><a class="pagenav" href="#">Start</a><a class="pagenav" href="#">Previous</a><b class="pagecureent">1</b> <a class="pagenav" href="#">2</a> <a class="pagenav" href="#">3</a>  <a class="pageactive" href="#">Next</a> <a class="pagenav" href="#">End</a></div> 
</div>

<div class="clear"></div>
<ul class="menusmall">
	<li><img src="images/icon-1.gif" alt="home" /><a href="index.html" title="Trang chủ">trang chủ</a></li>
	<li><img src="images/icon-2.gif" alt="Email" />email</li>
	<li><img src="images/icon-3.gif" alt="Print" />print</li>
	<li><img src="images/icon-4.gif" alt="Save" />save</li>
</ul>
<!--Loi binh-->
<div id="loibinh">
	<div id="bgloibinh"><p>gửi lời bình</p></div>
	<form id="contact" method="post" name="dangky" action="">
		<ul>
			<li><label>tiêu đề: </label><input type="text" name="username" value="" /></li>
			<li><label>nội dung:</label><textarea name="noidung" rows="10" cols="70"></textarea></li>
			<li><label></label><input type="image" src="images/bt-loibinh.gif" class="btloibinh"/></li>
		</ul>
	</form>
</div>
<!--End loi binh-->

<h3>các bài viết liên quan:</h3>
<ul class="posts">
	<li><a href="#" title="">nhà đầu tư hào hứng mua "chứng" </a><span> - Diễn đàn Doanh nghiệp</span></li>
	<li><a href="#" title="">"mưa tiền" đang đổ về thị trường chứng khoán </a><span> - vietnam plus</span></li>
	<li><a href="#" title="">TT, VRC, SDN, VSI: lịch trả cổ tức</a><span> - cafeF</span></li>
	<li><a href="#" title="">thuế thu nhập doanh nghiệp: Hồi hộp chờ sữa Nghị định 124 </a><span> - VnEconomy</span></li>
	<li><a href="#" title="">nhà đầu tư tăng mua chứng khoán</a><span> - VnExpress</span></li>
</ul>