<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="author" content="thanhansoft" />

<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/css/dosvn.css" />
<link rel="SHORTCUT ICON" href="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/favicon.ico" type="image/x-icon" />
<link rel="icon" href="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/favicon.ico" type="image/gif" />

<!--[if IE]>
<style>
    fieldset {position: relative; margin-top:10px}
    legend {position: absolute;	top: -0.5em; left: 1.4em; font-weight:bold; font-size:10pt}
</style>
<![endif]-->

<script type="text/javascript" src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/js/jquery-1.5.2.min.js"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/js/ddaccordion.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/js/ddaccordion.effect.js"></script>

<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>

<?php if (count($this->messages)) : ?>
   	<script type="text/javascript">
   		<?php $str = ''; foreach ($this->messages as $message) : ?>
   			<?php $str .= $this->escape($message).'\n'; ?>
   		<?php endforeach; ?>
   		<?php echo 'alert("'.$str.'")'; ?>
    </script>
<?php endif; ?>
</head>
<body>
<div id="wapper">
	<div id="header">
		<div class="logo"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>webadmin"><img src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/logo.png" alt="Logo" /></a></div>
        <div class="frmlogged">
            Chào <strong><?php echo $this->infouser('full_name'); ?></strong>
            <a href="<?php $url = explode('/webadmin', Zend_Controller_Front::getInstance()->getRequest()->getRequestUri()); echo ($url[0]) ? $url[0] : '/' ?>" target="_blank">Website</a>
            <a href="#"><?php echo $this->lang['inbox'] ?> (0)</a>
            <a href="<?php echo $this->baseUrl().'/webadmin/index/logout' ?>"><?php echo $this->lang['logout'] ?></a>
        </div>
        <div class="nav-left"></div><div class="nav-right"></div>
    </div>
    <ul id="tabs">
        <li<?php echo $this->selecthome ?>><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>webadmin" title="<?php echo $this->lang['home'] ?>"><span><?php echo $this->lang['home'] ?></span></a></li>
        <li<?php echo $this->selectsetup ?>><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>webadmin/setup" title="<?php echo $this->lang['setup'] ?>"><span><?php echo $this->lang['setup'] ?></span></a></li>
        <li<?php echo $this->selecttool ?>><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>webadmin/tool" title="<?php echo $this->lang['sys_tool'] ?>"><span><?php echo $this->lang['sys_tool'] ?></span></a></li>
        <li><a href="#"><span>Thanh toán</span></a></li>
        <li><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>webadmin/account" title="Tài khoản của tôi"><span>Tài khoản của tôi</span></a></li>
        <li><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>webadmin/user" title="Quản lý thành viên"><span>Quản lý thành viên</span></a></li>
    </ul><div class="clear"></div>
	<div class="paddinglr10">
		<div class="menu-bar">
            <div class="urbangreymenu">
                <?php
                    //List menu for web config for system
                    $rowsize = count($this->menu_setup);
                    if($rowsize >0){
                        echo '<h3 class="headerbar"><a href="#">'.$this->lang['setup'].'</a></h3>';
                        echo '<ul class="submenu">';
                        for($i=0; $i<$rowsize; $i++){
                            echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'webadmin/setup/'.$this->menu_setup[$i]['url'].'">'.$this->menu_setup[$i]['name'].'</a></li>';
                        }
                        echo '</ul>';
                    }

                    $rowsize = count($this->menu_user);
                    if($rowsize >0){
                        echo '<h3 class="headerbar"><a href="#">'.$this->lang['user'].'</a></h3>';
                        echo '<ul class="submenu">';
                        for($i=0; $i<$rowsize; $i++){
                            echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'webadmin/user/'.$this->menu_user[$i]['url'].'">'.$this->menu_user[$i]['name'].'</a></li>';
                        }
                        echo '</ul>';
                    }
                    $rowsize = count($this->menu_tool);
                    if($rowsize >0){
                        echo '<h3 class="headerbar"><a href="#">'.$this->lang['sys_tool'].'</a></h3>';
                        echo '<ul class="submenu">';
                        for($i=0; $i<$rowsize; $i++){
                            echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'webadmin/tool/'.$this->menu_tool[$i]['url'].'">'.$this->menu_tool[$i]['name'].'</a></li>';
                        }
                        echo '</ul>';
                    }
                    
                    $rowsize = count($this->menu_account);
                    if($rowsize >0){
                        echo '<h3 class="headerbar"><a href="#">'.$this->lang['sys_account'].'</a></h3>';
                        echo '<ul class="submenu">';
                        for($i=0; $i<$rowsize; $i++){
                            echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'webadmin/account/'.$this->menu_account[$i]['url'].'">'.$this->menu_account[$i]['name'].'</a></li>';
                        }
                        echo '</ul>';
                    }
                  
                ?>
                <?php
                    //List menu for Module 
                    foreach($this->listmenu as $value){
                        if($value['name'] != 'webadmin' && $value['name'] != 'default'){
                            echo '<h3 class="headerbar"><a href="#">'. $this->lang[$value['name']].'</a></h3>';
                            
                            $module = ucfirst($value['name']).'_Model_'.ucfirst($value['name']);
                            $model = new $module();
                            $list = $model->menuAdmin();
                            $num_record = count($list);
                            
                            if($num_record > 0){
                                echo '<ul class="submenu">';
                                for($i=0; $i<$num_record; $i++){
                                    echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'webadmin/'.$list[$i]['url'].'">'.$list[$i]['name'.LANG].'</a></li>';
                                }
                                echo '</ul>';
                            }
                        }
                    }
                ?>
            </div>
		</div>
		<div class="contenter">
        	<?php echo $this->layout()->content ?>
			<div id="footer" class="clear">
				<p>Copyright &copy; 2011 by <a href="http://azweb.vn">Azweb.vn</a>. All rights reserved. Version: 2.1.1.082211</p>
			</div>
		</div>
	</div>
</div>
</body>
</html>