<div class="content-conner">
	<b class="b1"></b><b class="b2"></b><b class="b3"></b><b class="b4"></b>
	<div class="contentb">
		<div class="content-conner-panel">
			<?php 
				echo '<h1 class="title-about title-services-detail">'.$this->item[0]['title'.LANG].'</h1>';
				echo html_entity_decode($this->item[0]['content'.LANG]);
			?>
			<script type="text/javascript">
			Cufon.replace('.content-conner-panel h1');
			</script>
		</div>
	</div>
	<b class="b4"></b><b class="b3"></b><b class="b2"></b><b class="b1"></b>
</div>