<div class="content">
	<?php if(count($this->error) > 0): ?>
		<ul class="error-li">
			<?php 
			foreach ($this->error as $value){
				echo '<li>'.$value.'</li>';
			}
			?>
		</ul>
	<?php endif; ?>
	<script type="text/javascript">
	$(document).ready(function(){
	    $("#add-rows").click(function(){
	        $(".rows").before('<p><label>Language</label><input name="langnamenew[]" value="" maxlength="30" class="txt-small" /> <?php $lang = $this->langlist(); foreach($lang as $value){echo '<input name="langnew'.$value.'[]" value="" maxlength="200" class="txt-small-x" /> '; }?></p>');
	        return false;
	    });
	});
	</script>
	<form action="" method="post" enctype="multipart/form-data" id="frmsignup" name="frmsignup">
	<fieldset>
		<legend><?php echo $this->lang['sys_lang']?></legend>
		<p class="rows"><a href="#" id="add-rows"><?php echo $this->lang['sys_addrow']?></a></p>
	    <?php
	    	$lang = $this->langlist(); //num language
	        foreach($this->listlang as $item){
	            echo '<p><label>Language</label>
	                    <input name="langname[]" value="'.$item['lang_name'].'" maxlength="30" class="txt-small" /> ';
	            foreach($lang as $value){
				     echo '<input name="lang'.$value.'[]" value="'.$item['lang'.$value].'" maxlength="200" class="txt-small-x" /> ';
				}
	            echo '</p>';
	        }
		?>
		<p>
			<label>&nbsp;</label>
			<input type="submit" name="btnregister" value="  <?php echo $this->lang['sys_edit'] ?>  " class="login" /> <a href="javascript:history.back()" class="login-a"><?php echo $this->lang['sys_cancel'] ?></a>
		</p>
	</fieldset>
	</form>
</div>