<div class="content-index">
	<div class="welcome">Chào mừng <strong><?php echo $this->infouser('full_name'); ?></strong> đến với hệ thống quản lý website của công ty chúng tôi. Ngay bây giờ bạn có thể bấm vào các nút bên trái và chỉnh sửa nó bên phải, bạn có thể thay đổi nội dung danh mục Giới thiệu công ty, địa chỉ liên hệ, Sản phẩm, Tin tức, Dịch vụ của công ty. <a href="#">Tìm hiểu thêm</a></div>
	<div class="static">
		<div class="col-static1">Tổng lượt truy cập<p><?php $sc = new GLT_System_SmartCounter(); echo $sc->visit_total();?></p></div>
		<div class="col-static2">Thứ hạng Web<p id="alexa">0</p></div>
		<div class="col-static3">Số thành viên quản lý<p><?php echo $this->numuser; ?></p></div>
	</div>
	<div class="count-module-col1">
		<h1><?php echo $this->lang['sys_func_static']?></h1>
		<?php 
			//List menu for Module 
			foreach($this->listmenu as $value){
				if($value['name'] != 'webadmin' && $value['name'] != 'default'){
					echo '<p><label>'.$this->lang[$value['name']].':</label>&nbsp;</p>';
					$module = ucfirst($value['name']).'_Model_'.ucfirst($value['name']);
					$model = new $module();
					$list = $model->menuAdmin();
					
					foreach ($list as $item){
						echo '<p class="sub"><label><a href="'.$this->baseUrl().'/'.LANGURL.'webadmin/'.$item['url'].'">'.$item['name'.LANG].'</a>:</label>'.$item['num'].'</p>';
					}
            	}
			}
		?>
	</div>
	<div class="count-module-col2">
		<h1>Thông báo</h1>
		<div class="paddingtb105">Không có thông báo nào cả, bạn có thể yên tâm đi chơi rồi!</div>
	</div>
	<div class="count-module-col2">
		<h1>Trang tin từ chúng tôi</h1>
		<div style="height:300px; padding:5px">Đang cập nhật...</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
    $('#alexa').load('<?php echo $this->baseUrl() ?>/webadmin/index/alexa');
});
</script>