<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-language" content="vi" />
<meta name="revisit-after" content="1 days" />
<meta name="robots" content="noodp,index,follow" />
<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>

<?php echo $this->google_analytic; ?>

<link rel="SHORTCUT ICON" href="<?php echo $this->baseUrl().TEMPLATE ?>/images/favicon.ico" type="image/x-icon" />
<link rel="icon" href="<?php echo $this->baseUrl().TEMPLATE ?>/images/favicon.ico" type="image/gif" />
<link href="<?php echo $this->baseUrl().TEMPLATE ?>/css/dosvn.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="wrapper">
		<div id="header">
        	<div id="header-left"><a href="<?php echo $this->baseUrl()?>/"><img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/logo.png" alt="Logo" /></a></div><!--End header left-->
            <div class="lang"><a href="<?php echo $this->baseUrl()?>/" title="Tiếng Việt">Tiếng Việt <img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/vn.gif" alt="Việt Nam" /></a> <a href="<?php echo $this->baseUrl() ?>/en" title="English">English <img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/en.gif" alt="English" /></a></div>
           	<div class="clear"></div>
        </div><!--End header-->
		    <ul class="nav">
        		<?php 
        			$folders = $this->menubar();
					foreach($folders as $models){		
						$target = ($models['target']=='') ? '' : ' target="'.$models['target'].'"';
						$select =($this->module==$models['url']) ? ' class="select-nav"': '';
						echo '<li><a '.$select.' href="'.$this->baseUrl().'/'.LANGURL.$models['url'].'" title="'.$models['module'.LANG].'"'.$target.'>'.$models['module'.LANG].'</a></li>';
					}
				?>
            </ul>
     	 <div class="clear"></div>
       <div id="banner">
			<img src="<?php echo $this->baseUrl().TEMPLATE ?>/images/banner.jpg" alt="banner" title="architecture" />
        </div><!--End banner-->
        <div id="content">
        	<div id="left-content">
			<?php if(isset($this->menu_about)): ?>
				<h1 class="title-left"><span><?php echo $this->lang['about'] ?></span></h1>
	            <ul class="sub-pro">
	            	<?php 
						foreach($this->menu_about as $value){
							echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'about'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
						}
					?>
	            </ul>
	        <?php endif;?>
				
			<?php if(isset($this->menu_services)): ?>
				<h1 class="title-left"><span><?php echo $this->lang['services'] ?></span></h1>
	            <ul class="sub-pro">
	            	<?php 
						foreach($this->menu_services as $value){
							echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'services'.'/index/view/id/'.$value['record_id'].'/'.$this->noneUnicode($value['title'.LANG]).'" title="'.$this->escape($value['title'.LANG]).'">'.$this->escape($value['title'.LANG]).'</a></li>';
						}
					?>
	            </ul>
	        <?php endif;?>	
				
			<?php if(isset($this->menu_news)): ?>
				<h1 class="title-left"><span><?php echo $this->lang['news'] ?></span></h1>
				<ul class="sub-pro">
					<?php 
						foreach($this->menu_news as $value){
							echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.'news'.'/index/cat/id/'.$value['cat_id'].'/'.$this->noneUnicode($value['cat_title'.LANG]).'" title="'.$this->escape($value['cat_title'.LANG]).'">'.$this->escape($value['cat_title'.LANG]).'</a></li>';
						}
					?>
				</ul>
			<?php endif;?>	
				
				
				
				
				
                <h1 class="title-left"><span>HỖ TRỢ TRỰC TUYẾN</span></h1>
				<ul class="support">
						<?php foreach ($this->menu_support as $value): ?>
							<li><?php echo $value['support_name'] ?></li>
							<li><a href="ymsgr:sendim?<?php echo $value['support_value'] ?>&amp;m=<?php echo $this->lang['welcome_chat']?>" title="Chat <?php echo $value['support_value'] ?>"><img src="http://opi.yahoo.com/online?u=<?php echo $value['support_value'] ?>&amp;m=g&amp;t=2&amp;l=us" alt="<?php echo $value['support_value'] ?>" /></a></li>
						<?php endforeach;?>
				</ul>
			
				<h1 class="title-left"><span>THỐNG KÊ TRUY CẬP</span></h1>
				<ul class="statistics">
					<li>Truy cập trong ngày: <?php echo $this->onlinetoday?></li>
					<li>Đang online: <?php echo $this->online?></li>
					<li>Tổng lượt truy cập: <?php echo $this->onlinetotal?></li>
				</ul>
            </div><!--End left content-->	
        	<div id="right-content">
            	<?php echo $this->layout()->content ?>
            </div><!--End right content-->   <div class="clear"></div>
        </div><!--End content-->
    <div id="footer">
        <ul class="nav-fter">
        		<?php 
					foreach($this->menubar() as $models){		
						$target = ($models['target']=='') ? '' : ' target="'.$models['target'].'"';		
						echo '<li><a href="'.$this->baseUrl().'/'.LANGURL.$models['url'].'" title="'.$models['module'.LANG].'"'.$target.'>'.$models['module'.LANG].'</a></li>';
					}
				?>
            </ul>
        <div class="frame-info">
          <?php echo $this->contact_home['content'] ?>
    	</div> <!--End frame info-->
    </div><!--End footer-->
</div><!--End wrapper-->
</body>
</html>

