<h3 class="marginb3"><strong>Công việc đã tạo</strong></h3>
<table>
	<thead>
		<tr>
			<th class="txt60">Mã CV</th>
			<th>Tên công việc</th>
			<th>Người thực hiện</th>
			<th>Ngày bắt đầu</th>
			<th>Ngày kết thúc</th>
			<th>Trạng thái</th>
			<th>Tiến độ thời gian</th>
			<th>Thao tác</th>
		</tr>
	</thead>

	<tbody>
		<?php if($this->listjobs):?>
		  	<?php
		  		$i=0;
				foreach ($this->listjobs as $job) {
				    $i++;
					?>
				  	<tr	<?php if($i%2==0) echo 'class="alt"';?>  >
						<td><?php echo $job['job_id']?></td>
						<td><a href="<?php echo $this->baseUrl()?>/job/list/view/id/<?php echo $job['job_id']?>"><?php echo $job['job_title']?></a></td>
						<td><?php echo $job['reciever']?></td>
						<td><?php echo $job['start_date']?></td>		
						<td><?php echo $job['last_date']?></td>
						<td><?php echo $job['status']?></td>		
						<td><?php echo $job['time']?></td>
						<td><a href="<?php echo $this->baseUrl()?>/job/update/index/id/<?php echo $job['job_id']?>"><strong>Sửa</strong></a> - <a href="<?php echo $this->baseUrl()?>/job/delete/index/id/<?php echo $job['job_id']?>"><strong>Xóa</strong></a></td>
					</tr>  
			<?php }?>
		<?php else:?>
			<tr><td colspan="6">Bạn không có việc nào yêu cầu cả</td></tr>
		<?php endif;?>
	</tbody>
</table>
<?php	
	echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
?>