<h1 class="title-left"><span><a href="<?php echo $this->baseUrl() ?>/the-gioi-doanh-nhan" title='<?php echo $this->lang[$this->module]?>'><?php echo $this->lang[$this->module]?></a></span></h1>
<div class="frame-tent-left">
	<?php if(is_array($this->item)): ?>
 		<h2 class="title-masuring"><?php echo $this->item['title']?></h2>
        <?php echo $this->item['content'] ?>        
    <?php endif;?>
	
	<div>
		<form action="" method="post" enctype="multipart/form-data" id="frmcomment" name="frmcomment">
			<p>
				<label>Tiêu đề:</label>
				<input type="text" name="commenttitle" id="commenttitle" value="" />  
			</p>
			<p>
				<label>Email:</label>
				<input type="text" name="commentemail" id="commentemail" value="" />  
			</p>
			<p>
				<label>Nội dung:</label>
				<textarea cols="80" rows="10" name="commentcontent" id="commentcontent"></textarea> 
			</p>
			<p>
				<input type="submit" name="btncomment" value="  Gởi nhận xét  " />
			</p>
		</form>
	</div>
    
    <?php if($this->otherItem){ ?>
    	<h2 class="title-others">Các Tin khác</h2>
		<ul class="sub-others">
    	<?php
    		$i=0; foreach ($this->otherItem as $value){	if($i++ % 2==0) {?>
        	<li>
        		<a href="<?php echo $this->baseUrl() ?>/the-gioi-doanh-nhan/<?php echo $value['tag'] ?>.html" title='<?php echo $value['title']?>'>
        			<?php echo $value['title']?>
        		</a>
        	</li>    
        	<?php }else{ ?>
        	<li><p>
        		<a href="<?php echo $this->baseUrl() ?>/the-gioi-doanh-nhan/<?php echo $value['tag'] ?>.html" title='<?php echo $value['title']?>'>
        			<?php echo $value['title']?>
        		</a>
        	</p></li>   
        <?php }}?>
        </ul>
     <?php }?>
</div><!--End frame tent-->
<div class="bd-bt-tenf-left"></div>