<div class="product-content">
	<b class="b1"></b><b class="b2"></b><b class="b3"></b><b class="b4"></b>
	<div class="contentb">
		<div class="content-conner-panel">
            <div class="product-panel-detail" style="text-align: center;">
            	<h3>Liên hệ thành công!</h3><p>E-mail của quý khách đã được gửi đến chúng tôi thành công.<br />Chúng tôi sẽ có phản hồi cho quý khách trong thời gian sớm nhất.<br /><br />Chân thành cảm ơn quý khách!</p>
            </div>
		</div>
	</div>
	<b class="b4"></b><b class="b3"></b><b class="b2"></b><b class="b1"></b>
</div>