<h1 class="title-right"><span><?php echo $this->lang['product'] ?> &raquo; <?php echo $this->productdetail['title'.LANG] ?></span></h1>
<div class="bg-pr">
	<div class="bd-top-pr"></div>
		<div class="tent-right">
			<?php if($this->productdetail['pic_full']):?>
				<div style="text-align:center"><img src="<?php echo $this->baseUrl()?>/public/userfiles/images/product/<?php echo $this->productdetail['pic_full']?>" alt="<?php echo $this->productdetail['title'.LANG] ?>" /></div>
			<?php endif;?>
			<?php echo html_entity_decode($this->productdetail['detail'.LANG]) ?>
		</div>
	<div class="bd-bt-pr"></div>
</div><!--End bg pr-->

<?php if($this->productcat): ?>
<h1 class="title-right"><span><?php echo $this->lang['product_other']?></span></h1>
<div class="bg-pr">
	<div class="bd-top-pr"></div>
			<div class="bg-product">
				<?php 
					if(is_array($this->productcat))
					foreach ($this->productcat as $value): ?>
					<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/product/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg';?>			
					<div class="product">
						<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/view/id/<?php echo $value['record_id'] ?>/<?php echo $this->noneUnicode($value['title'.LANG])?>" title="<?php echo $value['title'.LANG]?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" alt="<?php echo $value['title'.LANG]?>" title="<?php echo $value['title'.LANG]?>" /></a>
						<h2><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>product/index/view/id/<?php echo $value['record_id'] ?>/<?php echo $this->noneUnicode($value['title'.LANG])?>" title="<?php echo $value['title'.LANG]?>"><?php echo $value['title'.LANG]?></a></h2>
						<p><?php echo number_format($value['unit'], 0 , ',' , '.' )?> VNĐ</p>
					</div>
				<?php endforeach;
				else echo $this->productcat;?>
				<div class="clear"></div>
			</div>
	<div class="bd-bt-pr"></div>
</div><!--End bg pr-->
<?php endif; ?>