<div class="content">
	<?php if(count($this->error) > 0): ?>
		<ul class="error-li">
			<?php 
			foreach ($this->error as $value){
				echo '<li>'.$value.'</li>';
			}
			?>
		</ul>
	<?php endif; ?>
	<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
	<fieldset>
		<legend>Thay đổi mật khẩu</legend>
		<p>
			<label for="passold">Mật khẩu cũ <span class="error">*</span></label>
			<input type="password" name="passold" id="passold" value="<?php echo $this->item['passold']?>" maxlength="45" class="txt-large" />
		</p>
		<p>
			<label for="passnew">Mật khẩu mới <span class="error">*</span></label>
			<input type="password" name="passnew" id="passnew" value="<?php echo $this->item['passnew']?>" maxlength="45" class="txt-large" />
		</p>
		<p>
			<label for="repassnew">Nhập lại mật khẩu mới <span class="error">*</span></label>
			<input type="password" name="repassnew" id="repassnew" value="<?php echo $this->item['repassnew']?>" maxlength="45" class="txt-large" />
		</p>
		<p>
			<input type="submit" name="submit" value="  <?php echo $this->lang['sys_edit'] ?>  " class="login" /> <a href="javascript:history.back()" class="login-a" title="<?php echo $this->lang['sys_cancel'] ?>"><?php echo $this->lang['sys_cancel'] ?></a>
		</p>
	</fieldset>
	</form>
</div>