<div class="content">
	<?php if(count($this->error) > 0): ?>
		<ul class="error-li">
			<?php 
			foreach ($this->error as $value){
				echo '<li>'.$value.'</li>';
			}
			?>
		</ul>
	<?php endif; ?>
	<script type="text/javascript">
	$(document).ready(function(){
	    $("#add-rows").click(function(){
	        $(".rows").before('<p><label>Config web</label><input name="web_namenew[]" value="" maxlength="45" class="txt-large" /> <input name="web_valuenew[]" value="" maxlength="250" class="txt-large" /></p>');
	        return false;
	    });
	});
	</script>
	<form action="" method="post" enctype="multipart/form-data" id="frm" name="frm">
	<fieldset>
		<legend><?php echo $this->lang['sys_web']?></legend>
		<p class="rows"><a href="#" id="add-rows"><?php echo $this->lang['sys_addrow']?></a></p>
	    <?php
	        foreach($this->items as $item){
	        	echo '<p><label>Config web</label>
	                    <input readonly="readonly" name="web_name[]" value="'.$item['web_name'].'" maxlength="45" class="txt-large" />
	                    <input name="web_value[]" value="'.$item['web_value'].'" maxlength="250" class="txt-large" />';
	        }
		?>
		<p>
			<label>&nbsp;</label>
			<input type="submit" name="btnregister" value="  <?php echo $this->lang['sys_edit'] ?>  " class="login" /> <a href="javascript:history.back()" class="login-a"><?php echo $this->lang['sys_cancel'] ?></a>
		</p>
	</fieldset>
	</form>
</div>