<h1 class="title-left"><span>Tin tức &amp; Sự kiện</span></h1>
	<div class="frame-tent-left">
		<?php if(isset($this->list_top_hits)and count($this->list_top_hits)>0):?>
			<div class="frame-focus">
				<h1 class="title-focus"><span>Tin, bài nổi bật</span></h1>
				<ul class="fucus-tent">
					<?php 
						$i=0;
						foreach ($this->list_top_hits as $value) {
							$p=($i%2==1)?'<p>':'';
							$cp=($i%2==1)?'</p>':'';
							$i++;
						?>
							<li><?php echo $p?>
								<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>news/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>">
									<?php echo $value['title'.LANG] ?>
								</a>
							<?php echo $cp?></li>                   
					<?php }?>
				</ul>
			 </div><!--End frame fucus-->  
		<?php endif;?>
		
		<?php if($this->news_item_first):?>
			<?php if($this->news_item_first['pic_thumb']):?>
				<a href="<?php echo $this->baseUrl() ?>/tin-tuc/<?php echo $this->news_item_first['tag'] ?>.html" title="<?php echo $this->news_item_first['title'.LANG] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH.'news/'.$this->news_item_first['pic_thumb'] ?>" class="imgcon"  alt="<?php echo $this->news_item_first['title'.LANG] ?>" /></a>
			<?php endif;?>
			<h2 class="title-box"><a href="<?php echo $this->baseUrl() ?>/tin-tuc/<?php echo $this->news_item_first['tag'] ?>.html" title="<?php echo $this->news_item_first['title'.LANG] ?>"><?php echo $this->news_item_first['title'.LANG] ?></a></h2>
			<?php echo $this->news_item_first['preview'.LANG] ?>
		<?php endif;?>
		
		<?php if($this->news_items):?>
		<ul class="related-news">
			<?php foreach($this->news_items as $value):?>
				<li><a href="<?php echo $this->baseUrl() ?>/tin-tuc/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title']?>"><?php echo $value['title']?></a></li>
			<?php endforeach;?>
		</ul><div class="clear"></div>
		<?php endif; ?>
	</div><!--End frame tent-->
	<div class="bd-bt-tenf-left"></div>
   
   
	   
	<h1 class="title-new"><a href="<?php echo $this->baseUrl()?>/cam-nang-khoi-su" title="<?php echo $this->lang['handbook'] ?>"><span><?php echo $this->lang['handbook'] ?></span></a></h1>
	<div class="tent-new">
	
		<?php  if(isset($this->menu_cat_handbook)):?>
			<ul class="sub-top-tent">
				<?php foreach ($this->menu_cat_handbook as $value) :?>
				 <li style="border:none"><a href="#" title=""><?php echo $value['cat_title'] ?></a></li>
				 <?php endforeach;?>
			</ul> <div class="clear"></div>
		<?php endif;?>
        
        <?php if($this->handbook_item_first): ?>
		<div class="tent-new-left">
            <h3 class="title-box-left"><a href="<?php echo $this->baseUrl()?>/cam-nang-khoi-su/<?php echo $this->handbook_item_first['tag'] ?>.html" title="<?php echo $this->handbook_item_first['title'] ?>"><?php echo $this->handbook_item_first['title'] ?></a></h3>
            <?php if($this->handbook_item_first['pic_thumb']): ?>
                <a href="<?php echo $this->baseUrl()?>/cam-nang-khoi-su/<?php echo $this->handbook_item_first['tag'] ?>.html" title="<?php echo $this->handbook_item_first['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH?>/handbook/<?php echo $this->handbook_item_first['pic_thumb'] ?>" alt="<?php echo $this->handbook_item_first['title'] ?>" style="float:left" /></a>
            <?php endif; ?>
            <?php echo $this->handbook_item_first['preview'] ?>             
		</div>
        <?php endif; ?>
		
        <?php if($this->handbook_items): ?>
        <ul class="sub-tent-new">
            <?php foreach($this->handbook_items as $value): ?>
                <?php if($value['pic_thumb']): ?>
                    <li style="list-style:none"><a href="<?php echo $this->baseUrl()?>/cam-nang-khoi-su/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH ?>/handbook/<?php echo $value['pic_thumb'] ?>" alt="<?php echo $value['title'] ?>" style="float:left"/><?php echo $value['title'] ?></a></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->baseUrl()?>/cam-nang-khoi-su/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><?php echo $value['title'] ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
		</ul>
        <?php endif; ?>
		<div class="clear"></div>
	</div><!--End tent new-->
	<div class="bd-bt-tenf-left"></div>

	<h1 class="title-new"><a href="#" title="<?php echo $this->lang['experience'] ?>"><span><?php echo $this->lang['experience'] ?></span></a></h1>
	<div class="tent-new">
		<ul class="sub-top-tent">
			<li><a href="#" title="">Kinh nghiệm</a></li>
			<li><a href="#" title="">Mẹo vặt</a></li>
			<li style="border:none"><a href="#" title="">Cảnh giác</a></li>
		</ul> <div class="clear"></div>
        
        <?php if($this->experience_item_first): ?>
		<div class="tent-new-left">
            <h3 class="title-box-left"><a href="<?php echo $this->baseUrl()?>/kinh-nghiem-thuong-truong/<?php echo $this->experience_item_first['tag'] ?>.html" title="<?php echo $this->experience_item_first['title'] ?>"><?php echo $this->experience_item_first['title'] ?></a></h3>
            <?php if($this->experience_item_first['pic_thumb']): ?>
                <a href="<?php echo $this->baseUrl()?>/kinh-nghiem-thuong-truong/<?php echo $this->experience_item_first['tag'] ?>.html" title="<?php echo $this->experience_item_first['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH?>/experience/<?php echo $this->experience_item_first['pic_thumb'] ?>" alt="<?php echo $this->experience_item_first['title'] ?>" style="float:left" /></a>
            <?php endif; ?>
            <?php echo $this->experience_item_first['preview'] ?>             
		</div>
        <?php endif; ?>
        
		<?php if($this->experience_items): ?>
        <ul class="sub-tent-new">
            <?php foreach($this->experience_items as $value): ?>
                <?php if($value['pic_thumb']): ?>
                    <li style="list-style:none"><a href="<?php echo $this->baseUrl()?>/kinh-nghiem-thuong-truong/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH ?>/experience/<?php echo $value['pic_thumb'] ?>" alt="<?php echo $value['title'] ?>" style="float:left"/><?php echo $value['title'] ?></a></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->baseUrl()?>/kinh-nghiem-thuong-truong/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><?php echo $value['title'] ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
		</ul>
        <?php endif; ?>
		<div class="clear"></div>
	</div><!--End tent new-->
	<div class="bd-bt-tenf-left"></div>
    
	<h1 class="title-new"><a href="#" title="<?php echo $this->lang['knows'] ?>"><span><?php echo $this->lang['knows'] ?></span></a></h1>
	<div class="tent-new">
		<ul class="sub-top-tent">
			<li><a href="#" title="">Sổ tay giám đốc </a></li>
			<li><a href="#" title="">Kiến thức kinh tế</a></li>
			<li style="border:none"><a href="#" title="">Kiến thức pháp luật</a></li>
		</ul><div class="clear"></div>
        
        <?php if($this->knows_item_first): ?>
		<div class="tent-new-left">
            <h3 class="title-box-left"><a href="<?php echo $this->baseUrl()?>/kien-thuc-quan-ly/<?php echo $this->knows_item_first['tag'] ?>.html" title="<?php echo $this->knows_item_first['title'] ?>"><?php echo $this->knows_item_first['title'] ?></a></h3>
            <?php if($this->knows_item_first['pic_thumb']): ?>
                <a href="<?php echo $this->baseUrl()?>/kien-thuc-quan-ly/<?php echo $this->knows_item_first['tag'] ?>.html" title="<?php echo $this->knows_item_first['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH?>/knows/<?php echo $this->knows_item_first['pic_thumb'] ?>" alt="<?php echo $this->knows_item_first['title'] ?>" style="float:left" /></a>
            <?php endif; ?>
            <?php echo $this->knows_item_first['preview'] ?>             
		</div>
        <?php endif; ?>
        
		<?php if($this->knows_items): ?>
        <ul class="sub-tent-new">
            <?php foreach($this->knows_items as $value): ?>
                <?php if($value['pic_thumb']): ?>
                    <li style="list-style:none"><a href="<?php echo $this->baseUrl()?>/kien-thuc-quan-ly/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH ?>/knows/<?php echo $value['pic_thumb'] ?>" alt="<?php echo $value['title'] ?>" style="float:left"/><?php echo $value['title'] ?></a></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->baseUrl()?>/kien-thuc-quan-ly/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><?php echo $value['title'] ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
		</ul>
        <?php endif; ?>
		<div class="clear"></div>
	</div><!--End tent new-->
	<div class="bd-bt-tenf-left"></div>
	<h1 class="title-new"><a href="#" title="<?php echo $this->lang['consulting'] ?>"><span><?php echo $this->lang['consulting'] ?></span></a></h1>
	<div class="tent-new">
		<ul class="sub-top-tent">
			<li><a href="#" title="">Pháp luật</a></li>
			<li><a href="#" title="">Tài chính &amp; Tiền tệ </a></li>
			<li><a href="#" title="">Thuế &amp; Kế toán </a></li>
			<li style="border:none"><a href="#" title="">Khởi nghiệp</a></li>
		</ul>
        <div class="clear"></div>
		
        <?php if($this->consulting_item_first): ?>
		<div class="tent-new-left">
            <h3 class="title-box-left"><a href="<?php echo $this->baseUrl()?>/goc-tu-van/<?php echo $this->consulting_item_first['tag'] ?>.html" title="<?php echo $this->consulting_item_first['title'] ?>"><?php echo $this->consulting_item_first['title'] ?></a></h3>
            <?php if($this->consulting_item_first['pic_thumb']): ?>
                <a href="<?php echo $this->baseUrl()?>/goc-tu-van/<?php echo $this->consulting_item_first['tag'] ?>.html" title="<?php echo $this->consulting_item_first['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH?>/consulting/<?php echo $this->consulting_item_first['pic_thumb'] ?>" alt="<?php echo $this->consulting_item_first['title'] ?>" style="float:left" /></a>
            <?php endif; ?>
            <?php echo $this->consulting_item_first['preview'] ?>             
		</div>
        <?php endif; ?>
		
        <?php if($this->consulting_items): ?>
        <ul class="sub-tent-new">
            <?php foreach($this->consulting_items as $value): ?>
                <?php if($value['pic_thumb']): ?>
                    <li style="list-style:none"><a href="<?php echo $this->baseUrl()?>/goc-tu-van/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH ?>/consulting/<?php echo $value['pic_thumb'] ?>" alt="<?php echo $value['title'] ?>" style="float:left"/><?php echo $value['title'] ?></a></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->baseUrl()?>/goc-tu-van/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><?php echo $value['title'] ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
		</ul>
        <?php endif; ?>
		<div class="clear"></div>
	</div><!--End tent new-->
	<div class="bd-bt-tenf-left"></div>
    
	<h1 class="title-new"><a href="#" title="<?php echo $this->lang['world-business'] ?>"><span><?php echo $this->lang['world-business'] ?></span></a></h1>
	<div class="tent-new">
		<ul class="sub-top-tent">
			<li><a href="#" title="">Tiếng nói doanh nhân </a></li>
			<li><a href="#" title="">Tìm đối tác</a></li>
			<li style="border:none"><a href="#" title="">Tuyển dụng</a></li>
		</ul> <div class="clear"></div>
        
		<?php if($this->worldbusiness_item_first): ?>
		<div class="tent-new-left">
            <h3 class="title-box-left"><a href="<?php echo $this->baseUrl()?>/the-gioi-doanh-nhan/<?php echo $this->worldbusiness_item_first['tag'] ?>.html" title="<?php echo $this->worldbusiness_item_first['title'] ?>"><?php echo $this->worldbusiness_item_first['title'] ?></a></h3>
            <?php if($this->worldbusiness_item_first['pic_thumb']): ?>
                <a href="<?php echo $this->baseUrl()?>/the-gioi-doanh-nhan/<?php echo $this->worldbusiness_item_first['tag'] ?>.html" title="<?php echo $this->worldbusiness_item_first['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH?>/world-business/<?php echo $this->worldbusiness_item_first['pic_thumb'] ?>" alt="<?php echo $this->worldbusiness_item_first['title'] ?>" style="float:left" /></a>
            <?php endif; ?>
            <?php echo $this->worldbusiness_item_first['preview'] ?>             
		</div>
        <?php endif; ?>
		
        <?php if($this->worldbusiness_items): ?>
        <ul class="sub-tent-new">
            <?php foreach($this->worldbusiness_items as $value): ?>
                <?php if($value['pic_thumb']): ?>
                    <li style="list-style:none"><a href="<?php echo $this->baseUrl()?>/the-gioi-doanh-nhan/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH ?>/world-business/<?php echo $value['pic_thumb'] ?>" alt="<?php echo $value['title'] ?>" style="float:left"/><?php echo $value['title'] ?></a></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->baseUrl()?>/the-gioi-doanh-nhan/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><?php echo $value['title'] ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
		</ul>
        <?php endif; ?>
		<div class="clear"></div>
	</div><!--End tent new-->
	<div class="bd-bt-tenf-left"></div>
    
	<h1 class="title-new"><a href="#" title="<?php echo $this->lang['corporate-culture'] ?>"><span><?php echo $this->lang['corporate-culture'] ?></span></a></h1>
	<div class="tent-new">
		<?php if($this->corporateculture_item_first): ?>
		<div class="tent-new-left">
            <h3 class="title-box-left"><a href="<?php echo $this->baseUrl()?>/van-hoa-doanh-nghiep/<?php echo $this->corporateculture_item_first['tag'] ?>.html" title="<?php echo $this->corporateculture_item_first['title'] ?>"><?php echo $this->corporateculture_item_first['title'] ?></a></h3>
            <?php if($this->corporateculture_item_first['pic_thumb']): ?>
                <a href="<?php echo $this->baseUrl()?>/van-hoa-doanh-nghiep/<?php echo $this->corporateculture_item_first['tag'] ?>.html" title="<?php echo $this->corporateculture_item_first['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH?>/corporate-culture/<?php echo $this->corporateculture_item_first['pic_thumb'] ?>" alt="<?php echo $this->corporateculture_item_first['title'] ?>" style="float:left" /></a>
            <?php endif; ?>
            <?php echo $this->corporateculture_item_first['preview'] ?>             
		</div>
        <?php endif; ?>
		
        <?php if($this->corporateculture_items): ?>
        <ul class="sub-tent-new">
            <?php foreach($this->corporateculture_items as $value): ?>
                <?php if($value['pic_thumb']): ?>
                    <li style="list-style:none"><a href="<?php echo $this->baseUrl()?>/van-hoa-doanh-nghiep/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH ?>/corporate-culture/<?php echo $value['pic_thumb'] ?>" alt="<?php echo $value['title'] ?>" style="float:left"/><?php echo $value['title'] ?></a></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->baseUrl()?>/van-hoa-doanh-nghiep/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><?php echo $value['title'] ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
		</ul>
        <?php endif; ?>
		<div class="clear"></div>
	</div><!--End tent new-->
	<div class="bd-bt-tenf-left"></div>
    
	<h1 class="title-new"><a href="#" title="<?php echo $this->lang['entertainment'] ?>"><span><?php echo $this->lang['entertainment'] ?></span></a></h1>
	<div class="tent-new">
		<ul class="sub-top-tent">
			<li><a href="#" title="">Tranh - ảnh vui</a></li>
			<li style="border:none"><a href="#" title="">Truyện vui</a></li>
		</ul> <div class="clear"></div>
        
		<?php if($this->entertainment_item_first): ?>
		<div class="tent-new-left">
            <h3 class="title-box-left"><a href="<?php echo $this->baseUrl()?>/giai-tri/<?php echo $this->entertainment_item_first['tag'] ?>.html" title="<?php echo $this->entertainment_item_first['title'] ?>"><?php echo $this->entertainment_item_first['title'] ?></a></h3>
            <?php if($this->entertainment_item_first['pic_thumb']): ?>
                <a href="<?php echo $this->baseUrl()?>/giai-tri/<?php echo $this->entertainment_item_first['tag'] ?>.html" title="<?php echo $this->entertainment_item_first['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH?>/entertainment/<?php echo $this->entertainment_item_first['pic_thumb'] ?>" alt="<?php echo $this->entertainment_item_first['title'] ?>" style="float:left" /></a>
            <?php endif; ?>
            <?php echo $this->entertainment_item_first['preview'] ?>             
		</div>
        <?php endif; ?>
		
        <?php if($this->entertainment_items): ?>
        <ul class="sub-tent-new">
            <?php foreach($this->entertainment_items as $value): ?>
                <?php if($value['pic_thumb']): ?>
                    <li style="list-style:none"><a href="<?php echo $this->baseUrl()?>/giai-tri/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><img src="<?php echo $this->baseUrl().IMAGES_PATH ?>/entertainment/<?php echo $value['pic_thumb'] ?>" alt="<?php echo $value['title'] ?>" style="float:left"/><?php echo $value['title'] ?></a></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->baseUrl()?>/giai-tri/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><?php echo $value['title'] ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
		</ul>
        <?php endif; ?>
		<div class="clear"></div>
	</div><!--End tent new-->
	<div class="bd-bt-tenf-left"></div>