<h1 class="title-left"><span><a href="<?php echo $this->baseUrl() ?>/kien-thuc-quan-ly" title="<?php echo $this->lang[$this->module]?>"><?php echo $this->lang[$this->module]?></a> &raquo; <a href="<?php echo $this->detailcat['tag'] ?>" title="<?php echo $this->detailcat['cat_title'] ?>"><?php echo $this->detailcat['cat_title'] ?></a></span></h1>
<div class="frame-tent-left">
	<?php if($this->items):?>
	 <?php foreach ($this->items as $value):?>
		<?php $picthumb = ($value['pic_thumb']!='') ? IMAGES_PATH.$this->module.'/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg'; ?>
	 		<div class="masuring">
				<a href="<?php echo $this->baseUrl() ?>/kien-thuc-quan-ly/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>">
					<img src="<?php echo $this->baseUrl().$picthumb ?>" class="imgcon" style="float:left" alt="<?php echo $value['title'] ?>" /></a>
                <h2 class="title-masuring"><a href="<?php echo $this->baseUrl() ?>/kien-thuc-quan-ly/<?php echo $value['tag'] ?>.html" title="<?php echo $value['title'] ?>"><?php echo $value['title'] ?></a></h2>
     			<?php echo $value['preview'] ?>
     		</div><div class="clear"></div>
		<?php endforeach;?>
		<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
	<?php else: ?>
		<?php echo $this->lang['norecord'] ?>
	<?php endif;?>
</div><!--End frame tent-->
<div class="bd-bt-tenf-left"></div>