<h1>Đã xảy ra lỗi:</h1> 
<p><?php echo  $this->message ?></p> 
<? if ('development' == APPLICATION_ENV): ?> 
<h1>Exception information:</h1> 
<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p> 

<h1>Stack trace:</h1> 
    <pre><?php echo $this->exception->getTraceAsString() ?> 
</pre> 

<h1>Request Parameters:</h1> 
    <pre><?php var_dump($this->request->getParams()) ?></pre> 
<? endif ?>