<h1 class="title-right"><span><?php echo $this->lang[$this->module]?></span></h1>
<div class="frame-tent-right">	
	<?php if(is_array($this->list_news_new)):?>
	 <?php foreach ($this->list_news_new as $value):?>
		<?php $picthumb = ($value['pic_thumb']!='') ? IMAGES_PATH.$this->module.'/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg'; ?>
	 		<div class="masuring">
				<div class="frame-img"><a href="<?php echo $this->baseUrl().'/'.LANGURL.$this->module ?>/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>">
					<img src="<?php echo $this->baseUrl().$picthumb ?>" class="imgcon" style="float:left; alt="<?php echo $value['title'.LANG] ?>" /></a>
                  </div> 
                <h2 class="title-masuring"><a href="<?php echo $this->baseUrl().'/'.LANGURL.$this->module ?>/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h2>
     			<?php echo $value['preview'.LANG] ?>
     		</div><div class="clear"></div>
		<?php endforeach;?>
	<?php else: ?>
		<?php echo $this->list_news_new?>
	<?php endif;?>	
</div><!--End frame tent-->

