<div class="content-conner">
	<?php if(isset($this->menu_services)): ?>
	<?php foreach($this->menu_services as $value): ?>
		<div class="services-panel">
			<b class="b1"></b><b class="b2"></b><b class="b3"></b><b class="b4"></b>
			<div class="contentb">
				<div class="services-font">
					<h1 class="title-services"><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>/services/index/view/id/<?php echo $value['record_id'] ?>/<?php echo $this->noneUnicode($value['title'.LANG])?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h1>
					<?php echo html_entity_decode($value['preview'.LANG]) ?>
					<a class="link-services" href="<?php echo $this->baseUrl().'/'.LANGURL ?>/services/index/view/id/<?php echo $value['record_id'] ?>/<?php echo $this->noneUnicode($value['title'.LANG])?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $this->lang['detail'.LANG] ?></a>
				</div>
			</div>
			<b class="b4"></b><b class="b3"></b><b class="b2"></b><b class="b1"></b>
		</div>
	<?php endforeach; ?>
	<?php endif; ?>
	<div style="clear:both"></div>
</div>