<h2><?php echo $this->lang['gallery']?> &raquo; <?php echo $this->infocat['cat_title'.LANG]?></h2>
<?php if(is_array($this->listsubcat)):?>
	<div id="listfood2">
		<ul>
			<?php foreach ($this->listsubcat as $value):
				$pic = ($value['pic_thumb']) ? $this->baseUrl().'/public/userfiles/images/gallery_cat/'.$value['pic_thumb'] : $this->baseUrl().TEMPLATE.'/images/no-gallery-thumb.jpg';
			?>
			<li>
				<a href="<?php echo $this->baseUrl().'/'.LANGURL.'gallery'.'/index/cat/id/'.$value['cat_id'].'/'.$this->noneUnicode($value['cat_title'.LANG]).'" title="'.$this->escape($value['cat_title'.LANG]) ?>"><img src="<?php echo $pic?>" alt="<?php echo $value['cat_title'.LANG]?>" /></a>
				<h6><?php echo $value['cat_title'.LANG]?></h6>
			</li>
			<?php endforeach;?>
		</ul>
	</div>
<?php else: ?>
	<div id="listfood"><!--Danh sách món ăn-->
		<?php if(is_array($this->items)): ?>
		<ul>
			<?php foreach ($this->items as $value):
				$pic = ($value['pic_thumb']) ? $this->baseUrl().'/public/userfiles/images/gallery/'.$value['pic_thumb'] : $this->baseUrl().TEMPLATE.'/images/no-gallery-thumb.jpg';
				$pic_full = ($value['pic_full']) ? $this->baseUrl().'/public/userfiles/images/gallery/'.$value['pic_full'] : $this->baseUrl().TEMPLATE.'/images/no-gallery-thumb.jpg';
			?>
			<li>
				<a href="<?php echo $pic_full?>"><img src="<?php echo $pic?>" alt="<?php echo $value['title'.LANG]?>" /></a>
			</li>
			<?php endforeach;?>
		</ul>
		<script type="text/javascript">
		    $(function() {
		        $('#listfood a').lightBox({imageLoading: '<?php echo $this->baseUrl().TEMPLATE?>/images/lightbox-ico-loading.gif', imageBtnClose:'<?php echo $this->baseUrl().TEMPLATE?>/images/lightbox-btn-close.gif', imageBtnPrev: '<?php echo $this->baseUrl().TEMPLATE?>/images/lightbox-btn-prev.gif', imageBtnNext: '<?php echo $this->baseUrl().TEMPLATE?>/images/lightbox-btn-next.gif', imageBlank: '<?php echo $this->baseUrl().TEMPLATE?>/images/lightbox-blank.gif'});
		    });
		</script>
		<?php else: ?>
			<p><?php echo $this->items; ?></p>
		<?php endif;?>
	</div><!--END Danh sách món ăn-->
<?php endif;?>
<?php	
	echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
?>