<h1 class="title-box"><span><?php echo $this->lang[$this->module] ?> </span></h1>
<div class="frame-tent-right">
    <?php if(is_array($this->list_news_new)):?>
        <?php foreach ($this->list_news_new as $value):?>
            <?php
                $picthumb = ($value['pic_thumb'] != '') ? '/public/userfiles/images/' . $this->module . '/' . $value['pic_thumb'] : TEMPLATE . '/images/no-images.jpg';
                $url = (LANGURL != '') ? '/' . LANGURL . '/' . $this->module : '/' . $this->module;
            ?>
            <div class="masuring">
                <div class="frame-img"> <a href="<?php echo $this->baseUrl() . $url ?>/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title' . LANG] ?>"><img src="<?php echo $this->baseUrl() . $picthumb ?>" alt="<?php echo $value['title' . LANG] ?>" /></a></div>
                <h2 class="title-masuring"><a href="<?php echo $this->baseUrl() . $url ?>/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title' . LANG] ?>"><?php echo $value['title' . LANG] ?></a></h2>
                <?php echo $value['preview' . LANG] ?>
            </div><div class="clear"></div>
        <?php endforeach; ?>
    <?php else: ?>
        <?php echo $this->list_news_new?>
    <?php endif; ?>
</div>

<?php     if(DEBUG_MODE)  var_dump($this->list_news_new);?>	