<div class="aboutBox-detail">
	<div class="title"><?php echo $this->lang['news']?></div>
	<?php if(is_array($this->list_news_new)):?>
		<ul class="news-list">
		<?php foreach ($this->list_news_new as $value):?>
			<?php $picthumb = ($value['pic_thumb']!='') ? '/public/userfiles/images/news/'.$value['pic_thumb'] : TEMPLATE.'/images/no-images.jpg'; ?>
				<li>
					<a href="<?php echo $this->baseUrl().'/'.LANGURL ?>news/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><img src="<?php echo $this->baseUrl().$picthumb ?>" alt="<?php echo $value['title'.LANG] ?>" /></a>
					<h2><a href="<?php echo $this->baseUrl().'/'.LANGURL ?>news/index/view/id/<?php echo $value['record_id'] ?>" title="<?php echo $value['title'.LANG] ?>"><?php echo $value['title'.LANG] ?></a></h2>
					<?php echo html_entity_decode($value['preview'.LANG]) ?>
				</li>
		<?php endforeach;?>
		</ul>
	<?php else: ?>
		<?php echo $this->list_news_new?>
	<?php endif;?>
</div>