<div class="content">
	<ul class="modals"><li><a href="<?php echo $this->baseUrl().$this->currentController ?>/addcat" title="<?php echo $this->lang['sys_add'] ?>"><img src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/add.png" alt="<?php echo $this->lang['sys_add'] ?>" /><span><?php echo $this->lang['sys_add'] ?></span></a></li></ul><div class="clear"></div>
	<form name="frm" id="frm" action="" method="post">
	<input type="hidden" name="factive" value="" />
	<table>
	<thead>
		<tr>
			<th><input onclick="javascript: select_switch(this.checked);" type="checkbox" name="checkall" /></th>
	        <th><?php echo $this->lang['namecat'] ?></th>
			<th><?php echo $this->lang['productnum'] ?></th>
			<th><?php echo $this->lang['sys_order'] ?></th>
			<th><?php echo $this->lang['action'] ?></th>
		</tr>
	</thead>
	<tbody>
	<?php
		if(is_array($this->items)){
			$numitem = new Solution_Model_Solution();
			$k = 1;
		    foreach($this->items as $value){
		    	if($value['cat_enable'] == 0){
		    		$rowclass = ' class="disable"';
		    	}else{
		        	$rowclass = ($k%2==0) ? '' : ' class="alt"';
		    	}
		        echo '<tr'.$rowclass.'>
		               <td><input type="checkbox" name="ids[]" value="'.$value['cat_id'].'" /></td>
		               <td><b>'.$value['title_prefix'].$value['cat_title'.LANG].'</b></td>
		               <td>'.$numitem->countItembyCatID($value['cat_id']).'</td>
		               <td><a href="'.$this->baseUrl().$this->currentController.'/catup/id/'.$value['cat_id'].'"><img src="'.$this->baseUrl().TEMPLATE_ADMIN.'/images/up.gif" alt="Up" /></a> <a href="'.$this->baseUrl().$this->currentController.'/catdown/id/'.$value['cat_id'].'"><img src="'.$this->baseUrl().TEMPLATE_ADMIN.'/images/down.gif" alt="Down" /></a></td>
		               <td><a href="editcat/id/'.$value['cat_id'].'" title="'.$this->lang['sys_edit'].'">'.$this->lang['sys_edit'].'</a> <a href="delcat/id/'.$value['cat_id'].'" title="'.$this->lang['sys_delete'].'">'.$this->lang['sys_delete'].'</a></td>
		            </tr>';
		        $k++;
		    }
		}else{
			echo '<tr><td colspan="5">'.$this->items.'</td></tr>';	
		}
	?>
	
	</tbody>
	</table>
	
	<div class="control-button"><img src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/visible.png" alt="<?php echo $this->lang['sys_active'] ?>" align="left" /> <a href="javascript:submit_list('enable', '');" title="<?php echo $this->lang['sys_active'] ?>"><?php echo $this->lang['sys_active'] ?></a></div>
	<div class="control-button"><img src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/images/hidden.png" alt="<?php echo $this->lang['sys_hidden'] ?>" align="left" /> <a href="javascript:submit_list('disable', '');" title="<?php echo $this->lang['sys_hidden'] ?>"><?php echo $this->lang['sys_hidden'] ?></a></div>
	<script type="text/javascript" src="<?php echo $this->baseUrl().TEMPLATE_ADMIN ?>/js/common.js"></script>
	</form><div class="clear"></div>
</div>